// AUTO-GENERATED FILE — DO NOT EDIT
// Updated: 2026-02-14T03:30:29.528Z

export const activeManagers = [
  {
    "roster": 1,
    "shortName": "Ray",
    "fullName": "Ray Long",
    "status": "Active",
    "teamName": "Prestigio Mundial",
    "tookOver": null,
    "location": "Richmond, VA",
    "bio": "Greatest Commish Ever (self-proclaimed). Wannabe paper champ. Bargain draft hunter. Trade wizard. The respectable half of Prestigio Mundial.",
    "photo": "/managers/Ray.png",
    "fantasyStart": 2011,
    "favoriteTeam": "ATL",
    "mode": "Rebuild",
    "rival": {
      "name": "Wade",
      "image": "/managers/Wade.png"
    },
    "favoritePlayer": 9509,
    "valuePosition": "RB",
    "rookieOrVets": "Vets",
    "philosophy": "Make sure you have more money left than everyone else when the draft or season ends.",
    "preferredContact": "Text",
    "contactValue": "8046471100",
    "sleeperId": "342828350391230464",
    "record": "60-64",
    "currentWinnings": 0,
    "role": "Commissioner",
    "coOwner": {
      "fullName": "Jeffrey Hudgins"
    },
    "championships": 0,
    "podiums": 4,
    "bestFinish": "3rd",
    "toiletBowls": 1,
    "tradeAggression": 9
  },
  {
    "roster": 2,
    "shortName": "JD",
    "fullName": "JD Dowling",
    "status": "Active",
    "teamName": "The Art of War",
    "tookOver": null,
    "location": "Richmond, VA",
    "bio": "Husband, Father, Architect, Artist, DJ. Lost 4 Championships and only 1 W.",
    "photo": "/managers/JD.png",
    "fantasyStart": 2012,
    "favoriteTeam": "WAS",
    "mode": "Win Now",
    "rival": {
      "name": "Tommy",
      "image": "/managers/Tommy.png"
    },
    "favoritePlayer": 254,
    "valuePosition": "WR",
    "rookieOrVets": "Vets",
    "philosophy": "To crush your enemies, see them driven before you, and to hear the lamentation of their women.",
    "preferredContact": "Sleeper",
    "contactValue": "9174821170",
    "sleeperId": "342850391018356736",
    "record": "57-69",
    "currentWinnings": 30,
    "championships": 1,
    "podiums": 6,
    "bestFinish": "1st",
    "toiletBowls": 1,
    "tradeAggression": 5
  },
  {
    "roster": 3,
    "shortName": "Jordan",
    "fullName": "Jordan Maslyn",
    "status": "Active",
    "teamName": "London Calling",
    "tookOver": 2017,
    "location": "London, UK",
    "bio": "I’ve played fantasy since like 2010. I like bikepacking, tabletop games and video games. 2024 League Champion.",
    "photo": "/managers/Jordan.jpg",
    "fantasyStart": 2017,
    "favoriteTeam": "MIN",
    "mode": "Win Now",
    "rival": {
      "name": "Dave",
      "image": "/managers/Dave.png"
    },
    "favoritePlayer": 6794,
    "valuePosition": "RB",
    "rookieOrVets": "Vets",
    "philosophy": "I’m not here for a long time. I’m here for a good time.",
    "preferredContact": "Text",
    "contactValue": "9492352486",
    "sleeperId": "341412060426436608",
    "record": "59-65",
    "currentWinnings": 0,
    "coOwner": {
      "fullName": "Landon Elliott"
    },
    "championships": 1,
    "podiums": 2,
    "bestFinish": "1st",
    "toiletBowls": 1,
    "tradeAggression": 7
  },
  {
    "roster": 4,
    "shortName": "Tommy",
    "fullName": "Tommy Moore",
    "status": "Active",
    "teamName": "The Shepherd",
    "tookOver": null,
    "location": "Shreveport, LA",
    "bio": "Therapist, Pastor, Avid Magic the Gathering player and historically successful fantasy footballer.",
    "photo": "/managers/Tommy.png",
    "fantasyStart": 2012,
    "favoriteTeam": "NO",
    "mode": "Dynasty",
    "rival": {
      "name": "Dave",
      "image": "/managers/Dave.png"
    },
    "favoritePlayer": 12481,
    "valuePosition": "WR",
    "rookieOrVets": "Vets",
    "philosophy": "Trade every player with every owner and kick Dave’s ass.",
    "preferredContact": "Text",
    "contactValue": "3184640061",
    "sleeperId": "342849293037608960",
    "record": "60-65",
    "currentWinnings": 0,
    "championships": 5,
    "podiums": 8,
    "bestFinish": "1st",
    "toiletBowls": 2,
    "tradeAggression": 10
  },
  {
    "roster": 5,
    "shortName": "Stan",
    "fullName": "Stan Schoppe",
    "status": "Active",
    "teamName": "Tax Season",
    "tookOver": 2025,
    "location": "Richmond, VA",
    "bio": "I am a huge sports fan. My favorite sports are football and hockey. Accountant by day, fantasy rookie by night.",
    "photo": "/managers/Stan.jpg",
    "fantasyStart": 2025,
    "favoriteTeam": "GB",
    "mode": "Win Now",
    "rival": {
      "name": "Rashad",
      "image": "/managers/Rashad.png"
    },
    "favoritePlayer": 8161,
    "valuePosition": "RB",
    "rookieOrVets": "Vets",
    "philosophy": "Win BIG or go home!",
    "preferredContact": "Text",
    "contactValue": "5404136532",
    "sleeperId": "1260048448384667648",
    "record": "7-9",
    "currentWinnings": 0,
    "championships": 0,
    "podiums": 0,
    "bestFinish": "12th",
    "toiletBowls": 1,
    "tradeAggression": 2
  },
  {
    "roster": 6,
    "shortName": "Wade",
    "fullName": "Wade Cameron",
    "status": "Active",
    "teamName": "The Wildcard",
    "tookOver": null,
    "location": "Raleigh, NC",
    "bio": "Professional wild card menace. I've been to three finals and won one in 2019.",
    "photo": "/managers/Wade.png",
    "fantasyStart": 2011,
    "favoriteTeam": "CAR",
    "mode": "Rebuild",
    "rival": {
      "name": "Tommy",
      "image": "/managers/Tommy.png"
    },
    "favoritePlayer": 1181,
    "valuePosition": "K",
    "rookieOrVets": "Rookies",
    "philosophy": "Pick good players, mostly.",
    "preferredContact": "Text",
    "contactValue": "8046980260",
    "sleeperId": "342838548870762496",
    "record": "68-58",
    "currentWinnings": 0,
    "role": "Asst. to the Commish",
    "championships": 1,
    "podiums": 3,
    "bestFinish": "1st",
    "toiletBowls": 1,
    "tradeAggression": 9
  },
  {
    "roster": 7,
    "shortName": "Doug",
    "fullName": "Doug Fordham",
    "status": "Active",
    "teamName": "Hall Pass",
    "tookOver": 2019,
    "location": "Richmond, VA",
    "bio": "Assistant Principal. JMU alum. Perennial middle-of-the-pack fantasy owner.",
    "photo": "/managers/Doug.jpg",
    "fantasyStart": 2019,
    "favoriteTeam": "NYG",
    "mode": "Rebuild",
    "rival": {
      "name": "Dave",
      "image": "/managers/Dave.png"
    },
    "favoritePlayer": 12508,
    "valuePosition": "RB",
    "rookieOrVets": "Rookies",
    "philosophy": "Draft well. Don't trade. Finish 6th.",
    "preferredContact": "Sleeper",
    "contactValue": "9083038965",
    "sleeperId": "73400761740312576",
    "record": "53-59",
    "currentWinnings": 0,
    "championships": 0,
    "podiums": 1,
    "bestFinish": "3rd",
    "toiletBowls": 1,
    "tradeAggression": 1
  },
  {
    "roster": 8,
    "shortName": "Travis",
    "fullName": "Travis Miller",
    "status": "Active",
    "teamName": "Kissed by a Freckle",
    "tookOver": null,
    "location": "Richmond, VA",
    "bio": "Roanoke native. Baseball lifer. When you see that fat freckley face blow a kiss, then you know.",
    "photo": "/managers/Travis.png",
    "fantasyStart": 2012,
    "favoriteTeam": "WAS",
    "mode": "Win Now",
    "rival": {
      "name": "Ray",
      "image": "/managers/Ray.png"
    },
    "favoritePlayer": 4137,
    "valuePosition": "RB",
    "rookieOrVets": "Vets",
    "philosophy": "Don’t get voodoo-ed",
    "preferredContact": "Text",
    "contactValue": "8043991599",
    "sleeperId": "342831451382841344",
    "record": "58-65",
    "currentWinnings": 0,
    "championships": 0,
    "podiums": 3,
    "bestFinish": "2nd",
    "toiletBowls": 2,
    "tradeAggression": 4
  },
  {
    "roster": 9,
    "shortName": "Rashad",
    "fullName": "Rashad Gresham",
    "status": "Active",
    "teamName": "The Gresham Empire",
    "tookOver": 2022,
    "location": "Richmond, VA",
    "bio": "Drug lord and author of a series of children’s books.",
    "photo": "/managers/Rashad.png",
    "fantasyStart": 2022,
    "favoriteTeam": "WAS",
    "mode": "Win Now",
    "rival": {
      "name": "Tommy",
      "image": "/managers/Tommy.png"
    },
    "favoritePlayer": 3973,
    "valuePosition": "WR",
    "rookieOrVets": "Rookies",
    "philosophy": "Score. Win. Don’t get hurt… and most importanty FUCK TAYLOR SWIFT",
    "preferredContact": "Sleeper",
    "contactValue": "8046475495",
    "sleeperId": "864186418971418624",
    "record": "23-42",
    "currentWinnings": 0,
    "championships": 0,
    "podiums": 0,
    "bestFinish": "12th",
    "toiletBowls": 1,
    "tradeAggression": 5
  },
  {
    "roster": 10,
    "shortName": "Brian",
    "fullName": "Brian Stevens",
    "status": "Active",
    "teamName": "Buckeye Nation",
    "tookOver": null,
    "location": "Columbus, OH",
    "bio": "Dedicated strategist and Buckeye lifer. Built through the draft. 2018 Champion.",
    "photo": "/managers/Brian.png",
    "fantasyStart": 2016,
    "favoriteTeam": "CLE",
    "mode": "Rebuild",
    "rival": {
      "name": "Tommy",
      "image": "/managers/Tommy.png"
    },
    "favoritePlayer": 3973,
    "valuePosition": "WR",
    "rookieOrVets": "Rookies",
    "philosophy": "Consistency is the key to longevity.",
    "preferredContact": "Text",
    "contactValue": "6145658100",
    "sleeperId": "343129212162523136",
    "record": "67-59",
    "currentWinnings": 0,
    "championships": 1,
    "podiums": 4,
    "bestFinish": "1st",
    "toiletBowls": 1,
    "tradeAggression": 6
  },
  {
    "roster": 11,
    "shortName": "Aaron",
    "fullName": "Aaron Hawkins",
    "status": "Active",
    "teamName": "Hawkins Heroes",
    "tookOver": 2025,
    "location": "Richmond, VA",
    "bio": "Coaching my sons youth sports teams. 2025 League Champion.",
    "photo": "/managers/Aaron.png",
    "fantasyStart": 2025,
    "favoriteTeam": "SF",
    "mode": "Win Now",
    "rival": {
      "name": "Stan",
      "image": "/managers/Stan.jpg"
    },
    "favoritePlayer": 5991,
    "valuePosition": "WR",
    "rookieOrVets": "Vets",
    "philosophy": "Finish First or Last",
    "preferredContact": "Sleeper",
    "contactValue": "4342823654",
    "sleeperId": "583513420586848256",
    "record": "11-5",
    "currentWinnings": 0,
    "championships": 1,
    "podiums": 1,
    "bestFinish": "1st",
    "toiletBowls": 0,
    "tradeAggression": 10
  },
  {
    "roster": 12,
    "shortName": "Dave",
    "fullName": "David Besedich",
    "status": "Active",
    "teamName": "The Bearded One",
    "tookOver": 2019,
    "location": "Richmond, VA",
    "bio": "I grow beards with dick like aromas. 2021 League Champion.",
    "photo": "/managers/Dave.png",
    "fantasyStart": 2019,
    "favoriteTeam": "DET",
    "mode": "Win Now",
    "rival": {
      "name": "Tommy",
      "image": "/managers/Tommy.png"
    },
    "favoritePlayer": 12481,
    "valuePosition": "RB",
    "rookieOrVets": "Vets",
    "philosophy": "Raw Dog Everybody",
    "preferredContact": "Text",
    "contactValue": "6155574118",
    "sleeperId": "466663208728391680",
    "record": "67-46",
    "currentWinnings": 0,
    "championships": 1,
    "podiums": 4,
    "bestFinish": "1st",
    "toiletBowls": 0,
    "tradeAggression": 7
  }
] as const;
