import { RetiredManager, ManagerStatus, DraftPreference, TeamCode } from "@/lib/types/Manager";

export const retiredManagers: RetiredManager[] = [
  {
    shortName: "Chris",
    fullName: "Chris Barras",
    status: ManagerStatus.Retired,
    teamName: "Receding Zuerlein",
    photo: "/managers/Chris.png",
    role: "The Creator",
    bio: "The League Founder. Chris created the River City FFL in 2011 and served as the original architect of our league's culture.",
    philosophy: "The Founder.",
    favoriteTeam: TeamCode.TB,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2011,
    record: "8-4",
    championships: 0,
    podiums: 1, // 2012 Runner-Up
    bestFinish: "2nd"
  },
  {
    shortName: "Gordie",
    fullName: "Gordie Gahagan",
    status: ManagerStatus.Retired,
    teamName: "Freakshow Freaks",
    photo: "/managers/Gordie.png",
    bio: "The First Champion. Gordie dominated the inaugural 2011 season and set the bar for the original league era.",
    philosophy: "First to win it all.",
    favoriteTeam: TeamCode.GB,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2011,
    championships: 1, // 2011 Champ
    podiums: 2, // 2011 Champ, 2014 Runner-Up
    bestFinish: "1st"
  },
  {
    shortName: "Bryan",
    fullName: "Bryan Doane",
    status: ManagerStatus.Retired,
    teamName: "Drinkin' Irish",
    photo: "/managers/Bryan.png",
    bio: "2012 League Champion. A steady hand and a fierce competitor during the foundation years of the league.",
    philosophy: "Draft well, manage better.",
    favoriteTeam: TeamCode.WAS,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2011,
    championships: 1, // 2012 Champ
    podiums: 2, // 2012 Champ, 2013 3rd Place
    bestFinish: "1st"
  },
  {
    shortName: "Garet",
    fullName: "Garet Prior",
    status: ManagerStatus.Retired,
    teamName: "The Land of Cleve",
    photo: "/managers/Garet.png",
    bio: "2014 League Champion. Garet executed one of the most clinical runs in league history to secure his ring.",
    philosophy: "Veni, Vidi, Vici.",
    favoriteTeam: TeamCode.CLE,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2013,
    championships: 1, // 2014 Champ
    podiums: 1,
    bestFinish: "1st"
  },
  {
    shortName: "Keith",
    fullName: "Keith Polarek",
    status: ManagerStatus.Retired,
    teamName: "Team Polarek",
    photo: "/managers/Keith.png",
    bio: "2015 League Champion. Keith was the ultimate grinder, constantly finding ways to win close matchups.",
    philosophy: "Never quit.",
    favoriteTeam: TeamCode.WAS,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2011,
    championships: 1, // 2015 Champ
    podiums: 2, // 2015 Champ, 2014 3rd Place
    bestFinish: "1st"
  },
  {
    shortName: "James",
    fullName: "James Minnix",
    status: ManagerStatus.Retired,
    teamName: "Hyde the Russell Sprouts",
    photo: "/managers/James.png",
    bio: "A fierce competitor who reached the mountain top three times without the ring. The best to never win it.",
    philosophy: "Stay aggressive.",
    favoriteTeam: TeamCode.PIT,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2011,
    championships: 0,
    podiums: 3, // 2013, 2016, 2017 Podiums
    bestFinish: "2nd"
  },
  {
    shortName: "Landon",
    fullName: "Landon Elliott",
    status: ManagerStatus.Retired,
    teamName: "Special Brownies",
    photo: "/managers/Landon.png",
    bio: "Original co-owner of the Brownies. Landon walked so Jordan could run. Fearless in his approach.",
    philosophy: "Swing big or go home.",
    favoriteTeam: TeamCode.CLE,
    rookieOrVets: DraftPreference.Rookies,
    location: "Richmond, VA",
    fantasyStart: 2013,
    record: "49-47",
    championships: 0,
    podiums: 1,
    bestFinish: "2nd",
    toiletBowls: 3
  },
  {
    shortName: "Zach",
    fullName: "Zach Woolard",
    status: ManagerStatus.Retired,
    teamName: "Saved by the Zach",
    photo: "/managers/Zach.png",
    bio: "Founding member. Secured the 3rd place podium in the very first season of the league.",
    philosophy: "Go big every week.",
    favoriteTeam: TeamCode.WAS,
    rookieOrVets: DraftPreference.Rookies,
    location: "Richmond, VA",
    fantasyStart: 2011,
    championships: 0,
    podiums: 1, // 2011 3rd Place
    bestFinish: "3rd",
    toiletBowls: 1
  },
  {
    shortName: "Nicholas",
    fullName: "Nicholas Bates",
    status: ManagerStatus.Retired,
    teamName: "Master DeBatesr",
    photo: "/managers/Nicholas.png",
    bio: "A sharp mind who secured a 3rd place finish in 2012.",
    philosophy: "Let others make mistakes.",
    favoriteTeam: TeamCode.GB,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2012,
    championships: 0,
    podiums: 1, // 2012 3rd Place
    bestFinish: "3rd"
  },
  {
    shortName: "Rachel",
    fullName: "Rachel Woolard",
    status: ManagerStatus.Retired,
    teamName: "Zach's 2nd Team",
    photo: "/managers/Rachel.jpg",
    bio: "One of the league's original members and most unpredictable drafters.",
    philosophy: "Chaos creates opportunity.",
    favoriteTeam: TeamCode.WAS,
    rookieOrVets: DraftPreference.Rookies,
    location: "Richmond, VA",
    fantasyStart: 2014,
    championships: 0,
    podiums: 0,
    bestFinish: "11th"
  },
  {
    shortName: "Ricky",
    fullName: "Ricky Taylor",
    status: ManagerStatus.Retired,
    teamName: "Ricky Crickets",
    photo: "/managers/Ricky.png",
    bio: "A steady hand during the early league years.",
    philosophy: "Trust your gut.",
    favoriteTeam: TeamCode.WAS,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2012,
    record: "6-6",
    championships: 0,
    podiums: 0,
    bestFinish: "9th"
  },
  {
    shortName: "Patrick",
    fullName: "Patrick Leahey",
    status: ManagerStatus.Retired,
    teamName: "Deebow & Arrow",
    photo: "/managers/Patrick.jpg",
    bio: "A cerebral manager who competed in the mid-2010s era.",
    philosophy: "Play the long game.",
    favoriteTeam: TeamCode.WAS,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2013,
    record: "12-17",
    championships: 0,
    podiums: 0,
    bestFinish: "4th"
  },
  {
    shortName: "Darren",
    fullName: "Darren Kusaj",
    status: ManagerStatus.Retired,
    teamName: "Team Kusaj",
    photo: null,
    bio: "A founding member with a fiery spirit from the inaugural season.",
    philosophy: "Play with heart.",
    favoriteTeam: TeamCode.WAS,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2011,
    championships: 0,
    podiums: 0,
    bestFinish: "10th"
  },
  {
    shortName: "Billy",
    fullName: "Billy Biddle",
    status: ManagerStatus.Retired,
    teamName: "Brilly",
    photo: "/managers/Billy.png",
    bio: "A fearless drafter who always brought a unique energy to the draft room.",
    philosophy: "Shock the room.",
    favoriteTeam: TeamCode.ATL,
    rookieOrVets: DraftPreference.Rookies,
    location: "Richmond, VA",
    fantasyStart: 2013,
    record: "55-41",
    championships: 0,
    podiums: 0,
    bestFinish: "4th"
  },
  {
    shortName: "Adam",
    fullName: "Adam Lind",
    status: ManagerStatus.Retired,
    teamName: "Hotub Jellyfish",
    photo: "/managers/Adam.png",
    bio: "A technician who recently retired after several competitive seasons.",
    philosophy: "Maximize every slot.",
    favoriteTeam: TeamCode.SF,
    rookieOrVets: DraftPreference.Vets,
    location: "Richmond, VA",
    fantasyStart: 2011,
    record: "17-16",
    championships: 0,
    podiums: 1,
    bestFinish: "3rd"
  }
];
