import crypto from "node:crypto";
import type { ShadowValidationMetrics } from "./promotion";

export const VALIDATION_HISTORY_SCHEMA = "river-city-predictor-validation-v1" as const;
export type ValidationHistoryRecord = Readonly<{ schemaVersion: typeof VALIDATION_HISTORY_SCHEMA; validationId: string; season: number; throughWeek: number; shadowResultId: string; inputEvidenceChecksums: readonly string[]; metrics: ShadowValidationMetrics; evaluatedAt: string }>;
export type ValidationHistoryStore = { read(validationId: string): Promise<ValidationHistoryRecord | null>; create(record: ValidationHistoryRecord): Promise<"CREATED" | "DUPLICATE"> };
export function buildValidationHistoryRecord(input: Omit<ValidationHistoryRecord, "schemaVersion" | "validationId">): ValidationHistoryRecord { const base = { ...input, schemaVersion: VALIDATION_HISTORY_SCHEMA }; return { ...base, validationId: crypto.createHash("sha256").update(JSON.stringify(base)).digest("hex") }; }
export class MemoryValidationHistoryStore implements ValidationHistoryStore { private readonly records = new Map<string, ValidationHistoryRecord>(); async read(id: string) { return this.records.get(id) ?? null; } async create(record: ValidationHistoryRecord) { const existing = this.records.get(record.validationId); if (existing) { if (JSON.stringify(existing) !== JSON.stringify(record)) throw new Error("Validation history conflict."); return "DUPLICATE"; } this.records.set(record.validationId, record); return "CREATED"; } }
export class CloudStorageValidationHistoryStore implements ValidationHistoryStore {
  private path(record: Pick<ValidationHistoryRecord, "season" | "throughWeek" | "validationId">) { return `river-city/predictor/validation/${record.season}/week-${String(record.throughWeek).padStart(2, "0")}/${record.validationId}.json`; }
  async read(validationId: string) { const { getFirebaseStorageBucket } = await import("@/lib/firebaseAdmin"); const [files] = await getFirebaseStorageBucket().getFiles({ prefix: "river-city/predictor/validation/" }); const file = files.find(candidate => candidate.name.endsWith(`/${validationId}.json`)); if (!file) return null; return JSON.parse((await file.download())[0].toString("utf8")) as ValidationHistoryRecord; }
  async create(record: ValidationHistoryRecord) { const { getFirebaseStorageBucket } = await import("@/lib/firebaseAdmin"); const file = getFirebaseStorageBucket().file(this.path(record)); try { await file.save(JSON.stringify(record), { resumable: false, preconditionOpts: { ifGenerationMatch: 0 }, metadata: { contentType: "application/json", metadata: { schemaVersion: record.schemaVersion, shadowResultId: record.shadowResultId } } }); return "CREATED"; } catch { const existing = await this.read(record.validationId); if (existing && JSON.stringify(existing) === JSON.stringify(record)) return "DUPLICATE"; throw new Error("Validation history conflict."); } }
}
