"use client";

import { useState } from "react";

function rank(value: number | undefined) { return value == null ? "—" : `#${value}`; }
function contributionForPlayer(team: any, playerId: string, component: string) { return team.components?.[component]?.find((item: any) => item.playerId === playerId); }

function ContributionTable({ contribution }: { contribution: any }) {
  return <div className="overflow-x-auto"><table className="min-w-[760px] text-left text-xs"><thead><tr className="border-b text-[11px] uppercase tracking-wide text-slate-500"><th className="p-2">PLAYER</th><th className="p-2">POS</th><th className="p-2">FROZEN EVIDENCE</th><th className="p-2">STARTER ROLE</th><th className="p-2">POSITION ROOM</th><th className="p-2">DEPTH</th><th className="p-2">FLEX CONTEXT</th></tr></thead><tbody>{contribution.allPlayers.map((player: any) => { const starter = contributionForPlayer(contribution, player.playerId, "STARTING LINEUP"); const flex = contributionForPlayer(contribution, player.playerId, "FLEX DIAGNOSTIC"); const depth = contributionForPlayer(contribution, player.playerId, "DEPTH"); const rooms = ["QB ROOM", "RB ROOM", "WR ROOM", "TE ROOM"].filter((component) => contributionForPlayer(contribution, player.playerId, component)).join(" · "); return <tr key={player.playerId} className="border-b last:border-0"><td className="p-2 font-medium">{player.playerName}</td><td className="p-2">{player.position}</td><td className="p-2">{player.evidenceScore?.toFixed?.(2) ?? "—"}</td><td className="p-2">{starter?.role ?? "—"}</td><td className="p-2">{rooms || "—"}</td><td className="p-2">{depth?.role ?? "—"}</td><td className="p-2">{flex?.role ?? "—"}</td></tr>; })}</tbody></table></div>;
}

export default function V2PreviewClient({ review: initialReview, initialFrozen = false }: { review: any; initialFrozen?: boolean }) {
  const [review, setReview] = useState(initialReview);
  const [message, setMessage] = useState("");
  const [frozenSnapshotId, setFrozenSnapshotId] = useState(initialFrozen ? initialReview.snapshot.snapshotId : "");
  const [isFrozen, setIsFrozen] = useState(initialFrozen);
  const [isFreezing, setIsFreezing] = useState(false);
  async function freeze() {
    setIsFreezing(true); setMessage("Freezing review snapshot…");
    try {
      const response = await fetch("/api/commish/post-draft/v2", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "freeze-v2-snapshot" }) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error ?? "V2 snapshot freeze failed.");
      const snapshotId = result.snapshot?.snapshot?.snapshotId;
      if (!snapshotId) throw new Error("Freeze succeeded without a snapshot ID.");
      setFrozenSnapshotId(snapshotId);
      setIsFrozen(true);
const persistedResponse = await fetch(`/api/commish/post-draft/v2?snapshotId=${encodeURIComponent(snapshotId)}`, { method: "GET", cache: "no-store" });
      const persistedResult = await persistedResponse.json();
      if (persistedResponse.ok && persistedResult.review) setReview(persistedResult.review);
      setMessage(`V2 REVIEW SNAPSHOT FROZEN · Snapshot ID: ${snapshotId}`);
    } catch (error) { setMessage(error instanceof Error ? error.message : "V2 snapshot freeze failed."); }
    finally { setIsFreezing(false); }
  }
  const rowFor = (franchiseId: string, collection: any[]) => collection.find((row) => row.franchiseId === franchiseId);
  const overviewRows = review.formulaC.map((row: any) => ({ row, team: rowFor(row.franchiseId, review.snapshot.teams), quality: rowFor(row.franchiseId, review.quality.teams), auction: rowFor(row.franchiseId, review.auctionEfficiency.teams) }));
  return <>
    <header><p className="text-sm font-semibold uppercase tracking-wide text-orange-700">Commissioner only · Live shadow calculation</p><h1 className="text-3xl font-bold">Draft Report Card V2 Preview</h1><p className="mt-2 text-slate-600">V2 is a frozen draft-night roster-quality diagnostic. It has not replaced V1 and has no final letter grade.</p></header>
    <section className="mt-4 grid gap-4 rounded-lg border bg-white p-4 text-sm md:grid-cols-2"><div><h2 className="font-bold">DRAFT QUALITY — FORMULA C</h2><p>50% Starting Lineup</p><p>35% Position Group</p><p>15% Useful Depth</p></div><div><h2 className="font-bold">POSITION GROUP</h2><p>10% QB · 30% RB · 40% WR · 20% TE</p><p className="mt-2 font-medium">FLEX</p><p>Diagnostic only — no independent Draft Quality weight.</p></div></section>
    <section className="mt-4 rounded-lg border bg-white p-4 text-sm"><div>Snapshot ID: <code>{review.snapshot.snapshotId}</code></div><div>Input checksum: <code>{review.snapshot.inputChecksum}</code></div><div>Evidence as-of: {review.snapshot.evidenceAsOf}</div><div>Models: {Object.values(review.snapshot.modelVersions).join(" · ")}</div><div className="mt-2 font-semibold text-amber-800">{review.provenance.warning}</div><p>{review.provenance.message}</p>{isFrozen ? <p className="mt-3 font-semibold text-green-800">FROZEN SNAPSHOT EXISTS</p> : <button type="button" disabled={isFreezing} onClick={freeze} className="mt-3 rounded bg-orange-600 px-4 py-2 font-semibold text-white disabled:opacity-60">FREEZE V2 SNAPSHOT</button>}{message && <p aria-live="polite" className="mt-2">{message}</p>}{frozenSnapshotId && <p className="mt-2"><a className="font-semibold text-orange-700 underline" href={`/api/commish/post-draft/v2?snapshotId=${encodeURIComponent(frozenSnapshotId)}`}>VIEW FROZEN SNAPSHOT</a></p>}</section>
    <section className="mt-4 hidden overflow-x-auto rounded-lg border bg-white md:block"><table className="min-w-[1120px] text-left text-sm"><caption className="p-3 text-left text-xs text-slate-500">FLEX* is diagnostic only.</caption><thead><tr className="border-b text-xs uppercase tracking-wide text-slate-500">{["Rank", "Current Team", "Draft-Time Team", "Draft Quality", "Starting Lineup", "QB", "RB", "WR", "TE", "Depth", "FLEX*", "Auction Efficiency"].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody>{overviewRows.map(({ row, team, quality, auction }: any) => <tr key={row.franchiseId} className="border-b"><td className="p-3">{rank(row.draftQualityRank)}</td><td className="p-3 font-semibold">{team.currentDisplayName}<div className="font-mono text-[10px] font-normal text-slate-500">{row.franchiseId}</div>{team.historicalDraftTimeTeamName !== team.currentDisplayName && <div className="text-xs font-normal text-slate-500">Drafted as: {team.historicalDraftTimeTeamName}</div>}</td><td className="p-3">{team.historicalDraftTimeTeamName}</td><td className="p-3">{rank(row.draftQualityRank)}</td><td className="p-3">{rank(quality.components.startingLineup.leagueRank)}</td><td className="p-3">{rank(quality.components.qbRoom.leagueRank)}</td><td className="p-3">{rank(quality.components.rbRoom.leagueRank)}</td><td className="p-3">{rank(quality.components.wrRoom.leagueRank)}</td><td className="p-3">{rank(quality.components.teRoom.leagueRank)}</td><td className="p-3">{rank(quality.components.depth.leagueRank)}</td><td className="p-3">{rank(quality.components.flex.leagueRank)}</td><td className="p-3">{rank(auction?.auctionEfficiency.leagueRank)}</td></tr>)}</tbody></table></section>
    <section className="mt-4 space-y-3 md:hidden">{overviewRows.map(({ row, team, quality, auction }: any) => <article key={row.franchiseId} className="rounded-lg border bg-white p-4"><h2 className="font-bold">{team.currentDisplayName}</h2><p className="font-mono text-xs text-slate-500">{row.franchiseId}</p><p className="text-xs text-slate-500">Drafted as: {team.historicalDraftTimeTeamName}</p><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span>Draft Quality {rank(row.draftQualityRank)}</span><span>Starter {rank(quality.components.startingLineup.leagueRank)}</span><span>QB {rank(quality.components.qbRoom.leagueRank)}</span><span>RB {rank(quality.components.rbRoom.leagueRank)}</span><span>WR {rank(quality.components.wrRoom.leagueRank)}</span><span>TE {rank(quality.components.teRoom.leagueRank)}</span><span>Depth {rank(quality.components.depth.leagueRank)}</span><span>Auction {rank(auction?.auctionEfficiency.leagueRank)}</span></div></article>)}</section>
    <section className="mt-4 grid gap-4 md:grid-cols-2">{review.snapshot.teams.map((team: any) => { const quality = rowFor(team.franchiseId, review.quality.teams); const contribution = rowFor(team.franchiseId, review.contributionMap); const auction = rowFor(team.franchiseId, review.auctionEfficiency.teams); return <details key={team.franchiseId} className="rounded-lg border bg-white p-4"><summary className="cursor-pointer font-semibold">{team.currentDisplayName} · {team.franchiseId}</summary><div className="mt-3 grid grid-cols-2 gap-2 text-sm md:grid-cols-5"><span>DRAFT QUALITY {rank(quality.draftQuality.leagueRank)}</span><span>STARTING LINEUP {rank(quality.components.startingLineup.leagueRank)}</span><span>POSITION GROUP QB {rank(quality.components.qbRoom.leagueRank)} · RB {rank(quality.components.rbRoom.leagueRank)} · WR {rank(quality.components.wrRoom.leagueRank)} · TE {rank(quality.components.teRoom.leagueRank)}</span><span>DEPTH {rank(quality.components.depth.leagueRank)}</span><span>AUCTION EFFICIENCY {rank(auction?.auctionEfficiency.leagueRank)}</span></div><p className="mt-3 text-sm"><b>BIGGEST STRENGTH</b> {quality.biggestStrength} · <b>BIGGEST WEAKNESS</b> {quality.biggestWeakness}</p><ContributionTable contribution={contribution} /><details className="mt-3"><summary className="cursor-pointer text-xs font-semibold">VIEW RAW DIAGNOSTIC</summary><pre className="mt-2 max-h-80 overflow-auto rounded bg-slate-50 p-3 text-xs">{JSON.stringify(contribution.components, null, 2)}</pre></details></details>; })}</section>
  </>;
}
