function rank(value: number | undefined) { return value == null ? "—" : `#${value}`; }
function contributionForPlayer(team: any, playerId: string, component: string) { return team.components?.[component]?.find((item: any) => item.playerId === playerId); }
function summaryLabel(value: string | undefined) { return value?.replace(" — ", " · ") ?? "—"; }

function ContributionTable({ contribution }: { contribution: any }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[680px] table-fixed text-left text-xs"><colgroup><col className="w-[23%]" /><col className="w-[8%]" /><col className="w-[14%]" /><col className="w-[19%]" /><col className="w-[18%]" /><col className="w-[18%]" /></colgroup><thead><tr className="border-b text-[11px] uppercase tracking-wide text-slate-500"><th className="p-2">PLAYER</th><th className="p-2">POS</th><th className="p-2">FROZEN EVIDENCE</th><th className="p-2">STARTER ROLE</th><th className="p-2">POSITION ROOM</th><th className="p-2">DEPTH / FLEX</th></tr></thead><tbody>{contribution.allPlayers.map((player: any) => { const starter = contributionForPlayer(contribution, player.playerId, "STARTING LINEUP"); const flex = contributionForPlayer(contribution, player.playerId, "FLEX DIAGNOSTIC"); const depth = contributionForPlayer(contribution, player.playerId, "DEPTH"); const rooms = ["QB ROOM", "RB ROOM", "WR ROOM", "TE ROOM"].filter((component) => contributionForPlayer(contribution, player.playerId, component)).join(" · "); return <tr key={player.playerId} className="border-b align-top last:border-0"><td className="break-words p-2 font-medium">{player.playerName}</td><td className="p-2">{player.position}</td><td className="p-2">{player.evidenceScore?.toFixed?.(2) ?? "—"}</td><td className="break-words p-2">{starter?.role ?? "—"}</td><td className="break-words p-2">{rooms || "—"}</td><td className="break-words p-2">{depth?.role ?? "—"}{flex ? <><br /><span className="text-slate-500">{flex.role}</span></> : ""}</td></tr>; })}</tbody></table></div>;
}

export default function V2PreviewClient({ review: initialReview, initialFrozen = false }: { review: any; initialFrozen?: boolean }) {
  const review = initialReview;
  const frozenSnapshotId = initialFrozen ? initialReview.snapshot.snapshotId : "";
  const rowFor = (franchiseId: string, collection: any[]) => collection.find((row) => row.franchiseId === franchiseId);
  const overviewRows = review.formulaC.map((row: any) => ({ row, team: rowFor(row.franchiseId, review.snapshot.teams), quality: rowFor(row.franchiseId, review.quality.teams), auction: rowFor(row.franchiseId, review.auctionEfficiency.teams), final: rowFor(row.franchiseId, review.finalGrades) }));
  return <>
    <header><p className="text-sm font-semibold uppercase tracking-wide text-orange-700">Commissioner only · Frozen V2 preview</p><h1 className="text-3xl font-bold">Draft Report Card V2 Preview</h1><p className="mt-2 max-w-4xl text-slate-600">Grades compare each completed draft-night roster and auction execution with the other 2026 River City teams. Draft Quality drives 85% of the evaluation and Auction Efficiency contributes 15%. Grades are league-relative and are not absolute cross-season football ratings.</p></header>
    <section className="mt-4 grid gap-3 rounded-lg border bg-white p-4 text-sm md:grid-cols-2"><div><h2 className="font-bold">DRAFT QUALITY — FORMULA C</h2><p>50% Starting Lineup · 35% Position Group · 15% Useful Depth</p></div><div><h2 className="font-bold">POSITION GROUP</h2><p>10% QB · 30% RB · 40% WR · 20% TE</p><p className="mt-1 text-slate-600"><b>FLEX</b> diagnostic only — no independent Draft Quality weight.</p></div></section>
    <section className="mt-4 rounded-lg border bg-white px-4 py-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-semibold text-green-800">FROZEN SNAPSHOT EXISTS</p>{frozenSnapshotId && <a className="font-semibold text-orange-700 underline" href={`/api/commish/post-draft/v2?snapshotId=${encodeURIComponent(frozenSnapshotId)}`}>VIEW FROZEN SNAPSHOT</a>}</div><details className="mt-2"><summary className="cursor-pointer text-xs font-semibold uppercase tracking-wide text-slate-600">VIEW SNAPSHOT DETAILS</summary><div className="mt-3 grid gap-1 text-xs text-slate-600 md:grid-cols-2"><div>Snapshot ID: <code>{review.snapshot.snapshotId}</code></div><div>Input checksum: <code>{review.snapshot.inputChecksum}</code></div><div>Evidence as-of: {review.snapshot.evidenceAsOf}</div><div>Models: {Object.values(review.snapshot.modelVersions).join(" · ")}</div></div><div className="mt-3 font-semibold text-amber-800">{review.provenance.warning}</div><p className="mt-1 text-slate-600">{review.provenance.message}</p></details></section>
    <section className="mt-4 hidden overflow-x-auto rounded-lg border bg-white md:block"><table className="w-full min-w-[980px] table-fixed text-left text-sm"><colgroup><col className="w-[5%]" /><col className="w-[19%]" /><col className="w-[8%]" /><col className="w-[9%]" /><col className="w-[10%]" /><col className="w-[10%]" /><col className="w-[19.5%]" /><col className="w-[19.5%]" /></colgroup><caption className="p-3 text-left text-xs text-slate-500">Report-card overview · FLEX remains available in expanded diagnostics only.</caption><thead><tr className="border-b text-xs uppercase tracking-wide text-slate-500">{["Rank", "Team", "Grade", "Score", "Draft Quality", "Auction Efficiency", "Biggest Strength", "Biggest Weakness"].map((heading) => <th key={heading} className="p-3">{heading}</th>)}</tr></thead><tbody>{overviewRows.map(({ row, team, quality, auction, final }: any) => <tr key={row.franchiseId} className="border-b align-top last:border-0"><td className="p-3 font-semibold">{rank(final?.overallRank)}</td><td className="break-words p-3 font-semibold">{team.currentDisplayName}<div className="font-mono text-[10px] font-normal text-slate-500">{row.franchiseId}</div>{team.historicalDraftTimeTeamName !== team.currentDisplayName && <div className="text-xs font-normal text-slate-500">Drafted as: {team.historicalDraftTimeTeamName}</div>}</td><td className="p-3 text-xl font-bold">{final?.grade ?? "—"}</td><td className="p-3 font-semibold">{final?.methodDScore?.toFixed(2) ?? "—"}</td><td className="p-3">DQ {rank(row.draftQualityRank)}</td><td className="p-3">AE {rank(auction?.auctionEfficiency.leagueRank)}</td><td className="break-words p-3">{summaryLabel(quality.biggestStrength)}</td><td className="break-words p-3">{summaryLabel(quality.biggestWeakness)}</td></tr>)}</tbody></table></section>
    <section className="mt-4 space-y-3 md:hidden"><h2 className="text-sm font-bold uppercase tracking-wide text-slate-600">Report-card overview</h2>{overviewRows.map(({ row, team, quality, auction, final }: any) => <article key={row.franchiseId} className="rounded-lg border bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{team.currentDisplayName}</h2><p className="font-mono text-xs text-slate-500">{row.franchiseId}</p>{team.historicalDraftTimeTeamName !== team.currentDisplayName && <p className="text-xs text-slate-500">Drafted as: {team.historicalDraftTimeTeamName}</p>}</div><div className="text-right"><div className="text-2xl font-bold">{final?.grade ?? "—"}</div><div className="text-xs font-semibold text-slate-600">SCORE {final?.methodDScore?.toFixed(2) ?? "—"}</div></div></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><span>Overall {rank(final?.overallRank)}</span><span>DQ {rank(row.draftQualityRank)}</span><span>AE {rank(auction?.auctionEfficiency.leagueRank)}</span><span>{summaryLabel(quality.biggestStrength)}</span><span>{summaryLabel(quality.biggestWeakness)}</span></div></article>)}</section>
    <section className="mt-5"><h2 className="mb-3 text-lg font-bold">Expanded team reports</h2><div className="grid gap-4 md:grid-cols-2">{review.snapshot.teams.map((team: any) => { const formula = rowFor(team.franchiseId, review.formulaC); const quality = rowFor(team.franchiseId, review.quality.teams); const contribution = rowFor(team.franchiseId, review.contributionMap); const auction = rowFor(team.franchiseId, review.auctionEfficiency.teams); const final = rowFor(team.franchiseId, review.finalGrades); return <details key={team.franchiseId} className="rounded-lg border bg-white p-4"><summary className="cursor-pointer font-semibold">{team.currentDisplayName} · {team.franchiseId}</summary><div className="mt-4 rounded-md bg-slate-50 p-3"><div className="grid grid-cols-2 gap-3 sm:grid-cols-5"><div><div className="text-[11px] font-semibold uppercase text-slate-500">Grade</div><div className="text-2xl font-bold">{final?.grade ?? "—"}</div></div><div><div className="text-[11px] font-semibold uppercase text-slate-500">Score</div><div className="text-xl font-semibold">{final?.methodDScore?.toFixed(2) ?? "—"}</div></div><div><div className="text-[11px] font-semibold uppercase text-slate-500">Overall rank</div><div className="font-semibold">{rank(final?.overallRank)}</div></div><div><div className="text-[11px] font-semibold uppercase text-slate-500">DQ rank</div><div className="font-semibold">{rank(formula?.draftQualityRank)}</div></div><div><div className="text-[11px] font-semibold uppercase text-slate-500">AE rank</div><div className="font-semibold">{rank(auction?.auctionEfficiency.leagueRank)}</div></div></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm sm:grid-cols-5"><span>STARTING LINEUP {rank(quality.components.startingLineup.leagueRank)}</span><span>POSITION GROUP QB {rank(quality.components.qbRoom.leagueRank)} · RB {rank(quality.components.rbRoom.leagueRank)} · WR {rank(quality.components.wrRoom.leagueRank)} · TE {rank(quality.components.teRoom.leagueRank)}</span><span>DEPTH {rank(quality.components.depth.leagueRank)}</span><span>FLEX {rank(quality.components.flex.leagueRank)} <small className="text-slate-500">(diagnostic)</small></span><span>AUCTION EFFICIENCY {rank(auction?.auctionEfficiency.leagueRank)}</span></div><p className="mt-4 text-sm"><b>BIGGEST STRENGTH</b> {summaryLabel(quality.biggestStrength)} · <b>BIGGEST WEAKNESS</b> {summaryLabel(quality.biggestWeakness)}</p><div className="mt-4"><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-600">Player evidence</h3><ContributionTable contribution={contribution} /></div><details className="mt-4"><summary className="cursor-pointer text-xs font-semibold">VIEW RAW DIAGNOSTIC</summary><pre className="mt-2 max-h-80 overflow-auto rounded bg-slate-50 p-3 text-xs">{JSON.stringify(contribution.components, null, 2)}</pre></details></details>; })}</div></section>
  </>;
}
