function rank(value: number | undefined) { return value == null ? "—" : `#${value}`; }
function rowFor(franchiseId: string, collection: any[]) { const row = collection.find((item) => item.franchiseId === franchiseId); if (!row) throw new Error(`V2 preview is missing data for ${franchiseId}.`); return row; }
function summaryLabel(value: string | undefined) { return value?.replace(" — ", " · ") ?? "—"; }

function ReportMetric({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) {
  return <div><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className={emphasis ? "text-lg font-bold text-slate-950" : "font-semibold text-slate-800"}>{value}</div></div>;
}

function ContributionTable({ contribution }: { contribution: any }) {
  return <div className="grid gap-2 md:grid-cols-2">{contribution.allPlayers.map((player: any) => <ContributionRow key={player.playerId} contribution={contribution} player={player} />)}</div>;
}

function contributionForPlayer(team: any, playerId: string, component: string) { return team.components?.[component]?.find((item: any) => item.playerId === playerId); }
function ContributionRow({ contribution, player }: { contribution: any; player: any }) { const starter = contributionForPlayer(contribution, player.playerId, "STARTING LINEUP"); const flex = contributionForPlayer(contribution, player.playerId, "FLEX DIAGNOSTIC"); const depth = contributionForPlayer(contribution, player.playerId, "DEPTH"); const roomRows = ["QB ROOM", "RB ROOM", "WR ROOM", "TE ROOM"].map((component) => ({ component, row: contributionForPlayer(contribution, player.playerId, component) })).filter(({ row }) => row); return <article className="min-w-0 rounded-lg border border-slate-200 bg-white p-3 text-xs shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><h4 className="break-normal font-bold text-slate-950">{player.playerName}</h4><p className="mt-0.5 text-slate-500">{player.position ?? "—"}</p></div><div className="shrink-0 text-right"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Frozen evidence</p><p className="text-lg font-black text-slate-950">{player.evidenceScore?.toFixed?.(2) ?? "—"}</p></div></div><div className="mt-3 flex flex-wrap gap-2 border-t border-slate-100 pt-3"><div className="min-w-[9rem] flex-1"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Starter role</p><p className="mt-1 font-semibold text-slate-800">{starter?.role ?? "—"}</p></div><div className="min-w-[9rem] flex-1"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Position room</p>{roomRows.length ? <div className="mt-1 flex flex-wrap gap-1">{roomRows.map(({ component, row }: any) => <span key={component} className="rounded-full bg-slate-100 px-2 py-1 font-semibold text-slate-700">{component}: {row.role}</span>)}</div> : <p className="mt-1 font-semibold text-slate-800">—</p>}</div><div className="min-w-[9rem] flex-1"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Depth / FLEX</p><p className="mt-1 font-semibold text-slate-800">{depth?.role ?? "—"}{flex ? ` · ${flex.role}` : ""}</p></div></div></article>; }

export default function V2PreviewClient({ review, initialFrozen = false }: { review: any; initialFrozen?: boolean }) {
  const overviewRows = review.formulaC.map((row: any) => ({ row, team: rowFor(row.franchiseId, review.snapshot.teams), quality: rowFor(row.franchiseId, review.quality.teams), auction: rowFor(row.franchiseId, review.auctionEfficiency.teams), final: rowFor(row.franchiseId, review.finalGrades) }));
  return <>
    <header className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b-4 border-orange-500 bg-slate-950 px-5 py-5 text-white sm:px-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-orange-300">Commissioner only · Frozen V2 preview</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">2026 Draft Report Cards</h1><p className="mt-1 text-lg font-medium text-slate-200">River City FFL · Post-Draft Grades</p><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-400">12 teams · $200 auction · frozen evaluation</p></div><div className="px-5 py-4 sm:px-8"><p className="max-w-4xl text-sm leading-6 text-slate-600">Grades compare each completed draft-night roster and auction execution with the other 2026 River City teams. Draft Quality drives 85% of the evaluation and Auction Efficiency contributes 15%. Grades are league-relative and are not absolute cross-season football ratings.</p></div></header>

    <section className="mt-4 rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm shadow-sm"><details><summary className="cursor-pointer font-bold text-slate-800">HOW GRADES WORK</summary><div className="mt-3 grid gap-3 text-slate-600 sm:grid-cols-2"><div><p><b>Draft Quality</b> = 85%</p><p>50% Starting Lineup · 35% Position Group · 15% Useful Depth</p></div><div><p><b>Auction Efficiency</b> = 15%</p><p>Position Group: 10% QB · 30% RB · 40% WR · 20% TE</p><p>FLEX is diagnostic only. Grades are league-relative within 2026.</p></div></div></details></section>

    <section className="mt-4 rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-bold text-green-800">FROZEN SNAPSHOT EXISTS</p>{initialFrozen && <a className="font-semibold text-orange-700 underline" href={`/api/commish/post-draft/v2?snapshotId=${encodeURIComponent(review.snapshot.snapshotId)}`}>VIEW FROZEN SNAPSHOT</a>}</div><details className="mt-2"><summary className="cursor-pointer text-xs font-semibold uppercase tracking-wide text-slate-500">VIEW SNAPSHOT DETAILS</summary><div className="mt-3 grid gap-1 text-xs text-slate-600 sm:grid-cols-2"><div>Snapshot ID: <code>{review.snapshot.snapshotId}</code></div><div>Input checksum: <code>{review.snapshot.inputChecksum}</code></div><div>Evidence as-of: {review.snapshot.evidenceAsOf}</div><div>Models: {Object.values(review.snapshot.modelVersions).join(" · ")}</div></div><div className="mt-3 font-semibold text-amber-800">{review.provenance.warning}</div><p className="mt-1 text-slate-600">{review.provenance.message}</p></details></section>

    <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-orange-700">The report card</p><h2 className="text-2xl font-black tracking-tight text-slate-950">Every team. Every grade.</h2></div><p className="hidden text-xs text-slate-500 sm:block">Ordered by overall rank</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{overviewRows.map(({ row, team, quality, auction, final }: any) => <details key={row.franchiseId} className="draft-report-disclosure group min-w-0 open:col-span-full"><summary data-report-card-summary="true" className="cursor-pointer list-none overflow-hidden rounded-xl border border-slate-200 bg-white p-5 shadow-sm outline-none transition-shadow hover:shadow-md focus-visible:ring-2 focus-visible:ring-orange-500 focus-visible:ring-inset group-open:border-orange-300 group-open:ring-1 group-open:ring-orange-200"><div className="flex items-start justify-between gap-3"><div><span className="inline-flex rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{rank(final.overallRank)} OVERALL</span><h3 className="mt-3 break-words text-lg font-black uppercase tracking-wide text-slate-950">{team.currentDisplayName}</h3>{team.historicalDraftTimeTeamName !== team.currentDisplayName && <p className="text-xs text-slate-500">Drafted as: {team.historicalDraftTimeTeamName}</p>}</div><div className="text-right"><div className="text-5xl font-black leading-none text-orange-600">{final.grade}</div><div className="mt-1 text-sm font-bold text-slate-700">{final.methodDScore.toFixed(2)} SCORE</div></div></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-slate-100 pt-4"><ReportMetric label="Draft Quality" value={`DQ ${rank(row.draftQualityRank)}`} /><ReportMetric label="Auction Efficiency" value={`AE ${rank(auction.auctionEfficiency.leagueRank)}`} /></div><div className="mt-4 grid gap-2 border-t border-slate-100 pt-4 text-xs"><div><span className="font-bold uppercase tracking-wide text-orange-700">Strength</span><p className="mt-0.5 font-semibold text-slate-800">{summaryLabel(quality.biggestStrength)}</p></div><div><span className="font-bold uppercase tracking-wide text-slate-500">Needs work</span><p className="mt-0.5 font-semibold text-slate-800">{summaryLabel(quality.biggestWeakness)}</p></div></div><div className="mt-5 flex items-center justify-between text-xs font-bold uppercase tracking-wide text-orange-700"><span>View report</span><span className="transition-transform group-open:rotate-90" aria-hidden="true">→</span></div></summary><div data-full-team-report="true" className="mt-4 min-w-0 rounded-xl border border-slate-200 bg-slate-50 p-5 shadow-sm"><TeamReport team={team} formula={row} quality={quality} auction={auction} final={final} contribution={rowFor(team.franchiseId, review.contributionMap)} /></div></details>)}</div></section>
  </>;
}

function TeamReport({ team, formula, quality, auction, final, contribution }: { team: any; formula: any; quality: any; auction: any; final: any; contribution: any }) {
  return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Full team report</p><h3 className="text-xl font-black text-slate-950">{team.currentDisplayName}</h3>{team.historicalDraftTimeTeamName !== team.currentDisplayName && <p className="text-xs text-slate-500">Drafted as: {team.historicalDraftTimeTeamName}</p>}</div><div className="text-right"><span className="text-3xl font-black text-orange-600">{final.grade}</span><p className="text-xs font-semibold text-slate-600">{final.methodDScore.toFixed(2)} score · {rank(final.overallRank)} overall rank</p></div></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-lg border border-slate-200 bg-white p-3 sm:grid-cols-5"><ReportMetric label="DQ rank" value={rank(formula.draftQualityRank)} emphasis /><ReportMetric label="AE rank" value={rank(auction.auctionEfficiency.leagueRank)} emphasis /><ReportMetric label="Starting lineup" value={rank(quality.components.startingLineup.leagueRank)} /><ReportMetric label="Depth" value={rank(quality.components.depth.leagueRank)} /><ReportMetric label="FLEX*" value={rank(quality.components.flex.leagueRank)} /></div><div className="mt-4"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Position report · league ranks</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><ReportMetric label="QB" value={rank(quality.components.qbRoom.leagueRank)} /><ReportMetric label="RB" value={rank(quality.components.rbRoom.leagueRank)} /><ReportMetric label="WR" value={rank(quality.components.wrRoom.leagueRank)} /><ReportMetric label="TE" value={rank(quality.components.teRoom.leagueRank)} /></div><p className="mt-2 text-[11px] text-slate-500">* FLEX is diagnostic only.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg border-l-4 border-orange-500 bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-orange-700">Biggest strength</p><p className="mt-1 font-bold text-slate-900">{summaryLabel(quality.biggestStrength)}</p></div><div className="rounded-lg border-l-4 border-slate-400 bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">Biggest weakness</p><p className="mt-1 font-bold text-slate-900">{summaryLabel(quality.biggestWeakness)}</p></div></div><div className="mt-5"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Player evidence</p><ContributionTable contribution={contribution} /></div><details className="mt-4"><summary className="cursor-pointer text-xs font-semibold text-slate-600">VIEW RAW DIAGNOSTIC</summary><pre className="mt-2 max-h-80 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(contribution.components, null, 2)}</pre></details></div>;
}
