import Link from "next/link";
import SiteShell from "@/components/SiteShell";
import { anonymousCurrentMember, getCurrentMember } from "@/lib/auth/currentMember";
import { getCanonicalPowerRankings } from "@/lib/powerRankings/canonicalPowerRankings";
import { calibratingOutcome } from "@/lib/predictor/predictorContract";
import { getPredictorCalibrationProgress } from "@/lib/predictor/calibrationStatus";
import type { PredictorCalibrationProgress } from "@/lib/predictor/predictorContract";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const futureFields = ["Projected Finish", "Playoff Odds", "Championship Odds"] as const;

function ErrorState() {
  return <main className="min-h-screen bg-[#f7f8fa] px-4 py-8 text-slate-950 dark:bg-[#0a0a0a] dark:text-white"><div className="mx-auto max-w-3xl rounded-2xl border border-red-600/20 bg-white p-10 text-center shadow-sm dark:bg-white/5"><p className="text-xs font-black uppercase tracking-[0.2em] text-red-600">Predictions unavailable</p><p className="mt-3 text-sm font-bold leading-relaxed text-slate-600 dark:text-white/65">Current roster or published evidence data could not be loaded.</p></div></main>;
}

function CalibrationValue({ label }: { label: string }) {
  return <div className="rounded-xl border border-dashed border-orange-300 bg-orange-50/60 p-4 dark:border-orange-500/30 dark:bg-orange-500/5"><p className="text-[9px] font-black uppercase tracking-widest text-slate-500 dark:text-white/45">{label}</p><p className="mt-2 text-sm font-black uppercase tracking-wide text-orange-600">Calibrating</p></div>;
}

function ProgressRow({ label, value }: { label: string; value: string }) {
  return <p className="flex justify-between gap-4 border-b border-orange-200/70 pb-3 last:border-0 last:pb-0 dark:border-orange-500/20"><span className="font-black uppercase tracking-wide">{label}</span><span className="text-right font-black uppercase text-orange-600">{value}</span></p>;
}

export default async function PredictorPage() {
  let report;
  try { report = await getCanonicalPowerRankings(); } catch (error) { console.error("Predictions report failed", error); return <SiteShell activePath="/predictor"><ErrorState /></SiteShell>; }
  let progress: PredictorCalibrationProgress;
  try { progress = await getPredictorCalibrationProgress(); } catch { progress = { readiness: "CALIBRATING", projectedStandingsStatus: "UNAVAILABLE", probabilityStatus: "CALIBRATING", playerSamples: 0, playerSampleTarget: 50, teamSamples: 0, teamSampleTarget: 12, eligibleWeeks: [], excludedWeeks: [{ week: 1, reason: "PATH C: no authoritative pregame projection baseline" }], projectionBaselines: [{ week: 1, status: "MISSING" }, { week: 2, status: "CAPTURED" }], actualEvidence: [{ week: 1, status: "CAPTURED" }, { week: 2, status: "WAITING" }], residualEvidence: [{ week: 1, status: "MISSING" }, { week: 2, status: "MISSING" }], positionCoverage: {}, bucketCoverage: {}, latestEvidenceAt: null, nextEvent: "Waiting for the next finalized Sleeper week", explanation: "Probabilities remain hidden until valid residual evidence satisfies the approved calibration policy." }; }
  const member = await getCurrentMember().catch(() => anonymousCurrentMember);
  const ownerTeam = member.authenticated && member.franchiseName ? report.teams.find((team) => team.teamName.trim().toLowerCase() === member.franchiseName?.trim().toLowerCase()) : undefined;
  const outcome = calibratingOutcome;
  return <SiteShell activePath="/predictor"><main className="min-h-screen bg-[#f7f8fa] px-4 py-8 text-slate-950 dark:bg-[#0a0a0a] dark:text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1600px] space-y-6">
    <header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-[#121212] sm:p-8"><Link href="/" className="inline-flex min-h-10 items-center rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-xs font-black uppercase tracking-widest text-slate-600 hover:border-orange-600 hover:text-orange-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-orange-600 dark:border-white/15 dark:bg-white/5 dark:text-white/65">← Back to Home</Link><div className="mt-6 max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-600">RIVER CITY PREDICTOR</p><h1 className="mt-2 text-4xl font-black uppercase italic leading-none tracking-tight sm:text-5xl">WHAT ARE MY CHANCES?</h1><p className="mt-4 text-sm font-medium leading-7 text-slate-600 dark:text-white/65">See where every team stands today and how the season outlook will evolve as real 2026 results come in.</p><div className="mt-5"><span className="rounded-full bg-orange-600 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-white">SIMULATOR CALIBRATING</span></div></div></header>
    <section className="rounded-2xl border border-orange-200 bg-orange-50/50 p-5 shadow-sm dark:border-orange-500/20 dark:bg-orange-500/5" aria-label="Predictor calibration progress"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-600">Simulator Calibration</p><h2 className="mt-1 text-2xl font-black uppercase italic">Evidence earns the outlook</h2></div><span className="rounded-full bg-orange-600 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-white">{progress.readiness}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><ProgressRow label="Projection baseline" value={progress.projectionBaselines.find(row => row.week === 2)?.status === "CAPTURED" ? "Week 2 · Captured" : "Waiting"} /><ProgressRow label="Player samples" value={`${progress.playerSamples} / ${progress.playerSampleTarget}`} /><ProgressRow label="Team samples" value={`${progress.teamSamples} / ${progress.teamSampleTarget}`} /><ProgressRow label="Eligible weeks" value={String(progress.eligibleWeeks.length)} /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><ProgressRow label="Week 1" value="Excluded · Path C" /><ProgressRow label="Next" value={progress.nextEvent} /></div><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-white/60">{progress.explanation} Current evidence is read-only; no odds are generated in calibration mode.</p></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#121212]" aria-label="Your Predictor snapshot"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-600">Your Predictor Snapshot</p><h2 className="mt-1 text-2xl font-black uppercase italic">{ownerTeam?.teamName ?? "Owner outlook"}</h2></div>{ownerTeam ? <p className="rounded-full bg-slate-100 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-slate-600 dark:bg-white/10 dark:text-white/60">Power Rank #{ownerTeam.leagueRelativeRank}</p> : <Link href="/member/login?returnTo=%2Fpredictor" className="rounded-full bg-orange-600 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-white">Sign in for your snapshot</Link>}</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{futureFields.map((label) => <CalibrationValue key={label} label={label} />)}</div><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-white/60">{ownerTeam ? "Your future-season outlook will populate as the Predictor collects enough finalized 2026 evidence." : "Sign in to connect this view to your River City team. Future-season outlooks remain unavailable while calibration is in progress."}</p></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#121212]" aria-label="League-wide Predictor outlook"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-600">League-wide Outlook</p><h2 className="mt-1 text-2xl font-black uppercase italic">Every franchise, one view</h2></div><Link href="/power-rankings" className="text-[10px] font-black uppercase tracking-widest text-fuchsia-700 dark:text-fuchsia-300">View Power Rankings →</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-left"><thead><tr className="border-b border-slate-200 text-[9px] font-black uppercase tracking-widest text-slate-500 dark:border-white/10"><th className="px-3 py-3">Team</th><th className="px-3 py-3">Power Rank</th><th className="px-3 py-3">Projected Finish</th><th className="px-3 py-3">Playoff Odds</th><th className="px-3 py-3">Championship Odds</th></tr></thead><tbody>{report.teams.map((team) => <tr key={team.franchiseId} className="border-b border-slate-100 dark:border-white/5"><th className="px-3 py-4 text-sm font-black uppercase">{team.teamName}</th><td className="px-3 py-4 text-sm font-black">#{team.leagueRelativeRank}</td><td className="px-3 py-4 text-xs font-black uppercase text-orange-600">{outcome.projectedFinish === null ? "Calibrating" : outcome.projectedFinish}</td><td className="px-3 py-4 text-xs font-black uppercase text-orange-600">{outcome.playoffProbability === null ? "Calibrating" : outcome.playoffProbability}</td><td className="px-3 py-4 text-xs font-black uppercase text-orange-600">{outcome.championshipProbability === null ? "Calibrating" : outcome.championshipProbability}</td></tr>)}</tbody></table></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#121212]"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-600">How Predictor Works</p><h2 className="mt-1 text-2xl font-black uppercase italic">Outcomes will earn their way here</h2><ol className="mt-4 space-y-3 text-sm leading-6 text-slate-600 dark:text-white/60"><li><span className="font-black text-slate-950 dark:text-white">01.</span> Weekly player projections establish expected team scoring.</li><li><span className="font-black text-slate-950 dark:text-white">02.</span> River City&apos;s real schedule and playoff rules determine possible paths.</li><li><span className="font-black text-slate-950 dark:text-white">03.</span> As finalized 2026 results accumulate, the model calibrates uncertainty.</li><li><span className="font-black text-slate-950 dark:text-white">04.</span> Once calibration is sufficient, projected standings and season odds will populate here.</li></ol></article><article className="rounded-2xl border border-orange-200 bg-orange-50/50 p-5 shadow-sm dark:border-orange-500/20 dark:bg-orange-500/5"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-600">Calibration Status</p><h2 className="mt-1 text-2xl font-black uppercase italic">The model is learning the season</h2><div className="mt-4 space-y-3 text-sm"><p className="flex justify-between gap-4 border-b border-orange-200/70 pb-3 dark:border-orange-500/20"><span className="font-black uppercase tracking-wide">Expected Score Engine</span><span className="font-black uppercase text-emerald-600">Ready</span></p><p className="flex justify-between gap-4 border-b border-orange-200/70 pb-3 dark:border-orange-500/20"><span className="font-black uppercase tracking-wide">Projection Coverage</span><span className="font-black uppercase text-emerald-600">Ready</span></p><p className="flex justify-between gap-4"><span className="font-black uppercase tracking-wide">2026 Calibration Data</span><span className="font-black uppercase text-orange-600">In progress</span></p></div><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-white/60">Weekly projections are live. Season probabilities will unlock after enough real 2026 projection-vs-result data is collected.</p></article></section>
  </div></main></SiteShell>;
}
