import Link from "next/link";
import SiteShell from "@/components/SiteShell";
import { getCanonicalPowerRankings } from "@/lib/powerRankings/canonicalPowerRankings";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const componentLabels = [["starters", "STARTERS"], ["depth", "DEPTH"], ["qb", "QB"], ["rb", "RB"], ["wr", "WR"], ["te", "TE"], ["flex", "FLEX"]] as const;
function freshnessDate(value: string | null | undefined) {
  if (!value) return "unavailable";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "unavailable" : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(date);
}
function ownerFriendlyExplanation(value: string) {
  const match = value.match(/^(.+?) \d+(?:\.\d+)?\/100 \(league rank (\d+)\/\d+\)$/);
  return match ? { label: match[1], rank: `#${match[2]} IN LEAGUE` } : { label: value, rank: null };
}

function ErrorState() { return <main className="min-h-screen bg-[#f7f8fa] px-4 py-8 text-slate-950 dark:bg-[#0a0a0a] dark:text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl rounded-2xl border border-red-600/20 bg-white p-10 text-center shadow-sm dark:bg-white/5"><p className="text-xs font-black uppercase tracking-[0.2em] text-red-600">Predictions unavailable</p><p className="mt-3 text-sm font-bold leading-relaxed text-slate-600 dark:text-white/65">Current roster or published evidence data could not be loaded.</p></div></main>; }

export default async function PredictorPage() {
  let report;
  try { report = await getCanonicalPowerRankings(); } catch (error) { console.error("Predictions report failed", error); return <SiteShell activePath="/predictor"><ErrorState /></SiteShell>; }
  const tierCounts = report.teams.reduce<Record<string, number>>((counts, team) => ({ ...counts, [team.tier]: (counts[team.tier] ?? 0) + 1 }), {});
  const fantasyCalcFreshness = report.evidenceFreshness.find((source) => source.source === "FANTASYCALC_REDRAFT")?.generatedAt;
  const rosFreshness = report.evidenceFreshness.find((source) => source.source === "ROS_CONSENSUS")?.generatedAt;
  return <SiteShell activePath="/predictor"><main className="min-h-screen bg-[#f7f8fa] px-4 py-8 text-slate-950 dark:bg-[#0a0a0a] dark:text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-[1600px] space-y-6">
    <header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-[#121212] sm:p-8"><Link href="/" className="inline-flex min-h-10 items-center rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-xs font-black uppercase tracking-widest text-slate-600 hover:border-orange-600 hover:text-orange-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-orange-600 dark:border-white/15 dark:bg-white/5 dark:text-white/65">← Back to Home</Link><div className="mt-6 max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-600">2026 Preseason Power Rankings</p><h1 className="mt-2 text-4xl font-black uppercase italic leading-none tracking-tight sm:text-5xl">How does the league stack up?</h1><p className="mt-4 text-sm font-medium leading-7 text-slate-600 dark:text-white/65">A league-relative preseason ranking based on current rosters, optimized starters, depth, FantasyCalc Redraft, and ROS consensus.</p><div className="mt-5 flex flex-wrap items-center gap-3 text-[10px] font-black uppercase tracking-widest"><span className="rounded-full bg-orange-600 px-3 py-2 text-white">Model: Preseason Strength v1</span><span className="text-slate-500 dark:text-white/45">Preseason roster ranking — not a projected record or win probability.</span></div></div></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5" aria-label="Prediction tier distribution">{[["TITLE CONTENDER", "Title Contenders"], ["CONTENDER", "Contenders"], ["PLAYOFF CALIBER", "Playoff Caliber"], ["BUBBLE", "Bubble"], ["LONG SHOT", "Long Shots"]].map(([key, label]) => <div key={key} className="rounded-xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-[#121212]"><p className="text-[9px] font-black uppercase tracking-widest text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-orange-600">{tierCounts[key] ?? 0}</p></div>)}</section>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" aria-label="2026 preseason roster predictions">{report.teams.map((team) => { const strength = ownerFriendlyExplanation(team.biggestStrength); const weakness = ownerFriendlyExplanation(team.biggestWeakness); return <article key={team.franchiseId} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#121212]"><div className="flex items-start gap-3"><span className="shrink-0 text-4xl font-black italic leading-none text-slate-300 dark:text-white/20">#{team.leagueRelativeRank}</span><div className="min-w-0 flex-1"><h2 className="break-words text-xl font-black uppercase italic leading-tight tracking-tight">{team.teamName}</h2><div className="mt-3 flex flex-wrap items-center gap-2"><p className="inline-flex rounded-full bg-orange-600 px-2.5 py-1.5 text-[9px] font-black uppercase tracking-widest text-white">{team.tier}</p><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">{team.confidence} confidence</p></div></div></div>{team.confidence !== "HIGH" && <p className="mt-3 text-xs leading-5 text-slate-500 dark:text-white/50">Some roster players lack complete current-value or ROS coverage.</p>}<div className="mt-4 grid grid-cols-2 gap-2 border-y border-slate-100 py-4 dark:border-white/10 sm:grid-cols-4">{componentLabels.map(([key, label]) => <div key={key}><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">{label}</p><p className="mt-0.5 text-xl font-black leading-none">#{team.components[key].leagueRank ?? "—"}</p></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-[9px] font-black uppercase tracking-widest text-emerald-600">Biggest Strength</p><p className="mt-1 text-sm font-black uppercase leading-5">{strength.label}</p>{strength.rank && <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-slate-500">{strength.rank}</p>}</div><div><p className="text-[9px] font-black uppercase tracking-widest text-red-600">Biggest Weakness</p><p className="mt-1 text-sm font-black uppercase leading-5">{weakness.label}</p>{weakness.rank && <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-slate-500">{weakness.rank}</p>}</div></div></article>; })}</section>
    <aside className="rounded-2xl border border-slate-200 bg-white p-5 text-sm leading-6 text-slate-600 shadow-sm dark:border-white/10 dark:bg-[#121212] dark:text-white/60"><p><span className="font-black text-slate-900 dark:text-white">Evidence:</span> current rosters, current redraft market evidence, ROS consensus, optimized starters, and capped depth.</p><p className="mt-2"><span className="font-black text-slate-900 dark:text-white">Freshness:</span> FantasyCalc {freshnessDate(fantasyCalcFreshness)}; ROS {freshnessDate(rosFreshness)}.</p><p className="mt-2">Predictions are a preseason roster comparison. K/DEF do not materially affect preseason strength. Missing data affects confidence, not an automatic strength penalty.</p><p className="mt-2">Draft Report Card measures auction execution; Predictions measures current roster strength. This page does not project records or win probabilities.</p><p className="mt-2 text-xs">Predictions update when current roster and evidence inputs update in future versions.</p></aside>
  </div></main></SiteShell>;
}
