"use client";

import { useMemo, useState } from "react";
import type { PostDraftPublication } from "@/lib/postDraftPublicationTypes";
import type { PostDraftRecapDraft } from "@/lib/postDraftRecap";

export default function PostDraftRecapClient({ initialRecaps, initialPublications }: { initialRecaps: PostDraftRecapDraft[]; initialPublications: PostDraftPublication[] }) {
  const [recaps, setRecaps] = useState(initialRecaps);
  const [publications, setPublications] = useState(initialPublications);
  const [selectedId, setSelectedId] = useState(initialRecaps[0]?.recapId ?? "");
  const [draft, setDraft] = useState<Record<string, unknown>>(initialRecaps[0] ?? {});
  const [message, setMessage] = useState("");
  const selected = useMemo(() => recaps.find((item) => item.recapId === selectedId) ?? null, [recaps, selectedId]);
  const active = publications.find((item) => item.publicationKind === "league" && item.status === "published") ?? null;
  const history = publications.filter((item) => item.publicationKind === "league");
  const call = async (body: Record<string, unknown>) => { const response = await fetch("/api/commish/post-draft", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Request failed."); return payload; };
  const create = async () => { const snapshotId = initialRecaps[0]?.snapshotId; if (!snapshotId) { setMessage("Capture a locked snapshot before creating the league recap."); return; } try { const payload = await call({ action: "create-recap", snapshotId }); setRecaps((items) => [payload.recap, ...items]); setSelectedId(payload.recap.recapId); setDraft(payload.recap); setMessage("League recap draft created from locked public data."); } catch (error) { setMessage(error instanceof Error ? error.message : "Recap creation failed."); } };
  const save = async () => { if (!selected) return; try { const payload = await call({ action: "save-recap", recapId: selected.recapId, expectedRevision: selected.revision, input: draft }); setRecaps((items) => items.map((item) => item.recapId === selected.recapId ? payload.recap : item)); setDraft(payload.recap); setMessage("Commissioner-editable fields saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Recap save failed."); } };
  const transition = async (to: "in_review" | "approved") => { if (!selected) return; try { const payload = await call({ action: "transition-recap", recapId: selected.recapId, expectedRevision: selected.revision, to }); setRecaps((items) => items.map((item) => item.recapId === selected.recapId ? payload.recap : item)); setDraft(payload.recap); setMessage(`Recap moved to ${to}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Transition failed."); } };
  const preview = async () => { if (!selected) return; try { await call({ action: "preview-recap", recapId: selected.recapId }); setMessage("Preview generated through serializePublicLeagueRecap."); } catch (error) { setMessage(error instanceof Error ? error.message : "Preview failed."); } };
  const publish = async () => { if (!selected) return; try { const payload = await call({ action: "publish-recap", recapId: selected.recapId, expectedRevision: selected.revision }); setPublications((items) => [payload.publication, ...items.map((item) => item.publicationId === payload.publication.supersedes ? { ...item, status: "superseded" } : item)]); setMessage("Approved recap published as an immutable revision."); } catch (error) { setMessage(error instanceof Error ? error.message : "Publication failed."); } };
  const unpublish = async () => { if (!active) return; try { const payload = await call({ action: "unpublish-recap", publicationId: active.publicationId }); setPublications((items) => items.map((item) => item.publicationId === active.publicationId ? payload.publication : item)); setMessage("Recap unpublished; history preserved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unpublish failed."); } };
  const rollback = async (publicationId: string) => { try { const payload = await call({ action: "rollback-recap", publicationId }); setPublications((items) => items.map((item) => item.publicationId === payload.publication.publicationId ? payload.publication : item)); setMessage("Historical recap restored."); } catch (error) { setMessage(error instanceof Error ? error.message : "Rollback failed."); } };
  const edit = (key: string, value: unknown) => setDraft((current) => ({ ...current, [key]: value }));
  const deterministic = selected?.deterministic;
  return <section className="mx-auto mt-6 max-w-7xl space-y-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#121212]">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.3em] text-orange-600">Commissioner-only · league recap</p><h2 className="mt-1 text-2xl font-black uppercase italic">League Recap</h2><p className="mt-1 text-xs text-slate-500">Deterministic public facts are read-only; narrative fields are commissioner-editable.</p></div><button type="button" onClick={create} className="min-h-11 rounded-xl bg-orange-600 px-4 text-xs font-black uppercase tracking-widest text-white">Create recap draft</button></div>
    {recaps.length > 0 && <div className="grid gap-5 lg:grid-cols-[15rem_1fr]"><aside className="grid content-start gap-2">{recaps.map((recap) => <button key={recap.recapId} type="button" onClick={() => { setSelectedId(recap.recapId); setDraft(recap); }} className="rounded-xl border border-slate-900/10 p-3 text-left text-xs font-bold dark:border-white/10">{recap.season} League Recap<span className="mt-1 block text-[10px] text-slate-500">Revision {recap.revision} · {recap.status}</span></button>)}</aside>
      <div><div className="flex flex-wrap gap-2"><button type="button" onClick={save} className="min-h-10 rounded-xl bg-[#071a33] px-3 text-[10px] font-black uppercase tracking-widest text-white">Save Draft</button><button type="button" onClick={preview} className="min-h-10 rounded-xl border border-slate-900/20 px-3 text-[10px] font-black uppercase tracking-widest">Preview</button>{selected?.status === "draft" && <button type="button" onClick={() => transition("in_review")} className="min-h-10 rounded-xl border border-orange-600 px-3 text-[10px] font-black uppercase tracking-widest text-orange-700">Send to Review</button>}{selected?.status === "in_review" && <button type="button" onClick={() => transition("approved")} className="min-h-10 rounded-xl bg-emerald-700 px-3 text-[10px] font-black uppercase tracking-widest text-white">Approve</button>}{selected?.status === "approved" && <button type="button" onClick={publish} className="min-h-10 rounded-xl bg-orange-600 px-3 text-[10px] font-black uppercase tracking-widest text-white">Publish</button>}{active && <button type="button" onClick={unpublish} className="min-h-10 rounded-xl border border-orange-600 px-3 text-[10px] font-black uppercase tracking-widest text-orange-700">Unpublish</button>}</div>
        {message && <p role="status" className="mt-3 rounded-xl bg-orange-600/10 p-3 text-sm font-semibold text-orange-800">{message}</p>}
        <div className="mt-4 rounded-xl border border-slate-900/10 p-4 text-xs dark:border-white/10"><p className="font-black uppercase tracking-widest">{active ? `PUBLISHED · revision ${active.revision}` : "No active published recap"}</p><p className="mt-1 text-slate-500">Source: {selected?.snapshotId ?? "No recap draft"} · coverage {selected?.coverage.status ?? "N/A"}</p>{history.filter((item) => item.status !== "published").map((item) => <button key={item.publicationId} type="button" onClick={() => rollback(item.publicationId)} className="mt-2 mr-2 min-h-9 rounded-lg border border-slate-900/20 px-3 text-[10px] font-black uppercase tracking-widest">Roll Back Revision {item.revision}</button>)}</div>
        {selected && deterministic && <><div className="mt-5 rounded-xl border border-slate-900/10 p-4 dark:border-white/10"><h3 className="text-[10px] font-black uppercase tracking-widest">Deterministic / Read-Only</h3><p className="mt-2 text-xs text-slate-500">Draft Grade leaderboard, bargains, reaches, spending trends, position trends, and Early Power Rankings are fixed from the locked snapshot.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{deterministic.draftGradeLeaderboard.map((row) => <p key={row.franchiseId} className="text-sm font-semibold">{row.teamName}: {row.grade ?? "N/A"}</p>)}</div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-xs font-black uppercase tracking-widest">Title<input value={String(draft.title ?? "")} onChange={(event) => edit("title", event.target.value)} className="min-h-10 rounded-lg border border-slate-900/10 p-2 text-sm normal-case tracking-normal dark:border-white/10 dark:bg-white/[0.04]" /></label><label className="grid gap-2 text-xs font-black uppercase tracking-widest">Dek / Summary<textarea value={String(draft.dek ?? "")} onChange={(event) => edit("dek", event.target.value)} rows={3} className="rounded-lg border border-slate-900/10 p-2 text-sm normal-case tracking-normal dark:border-white/10 dark:bg-white/[0.04]" /></label><label className="grid gap-2 text-xs font-black uppercase tracking-widest">Opening Commissioner Take<textarea value={String(draft.openingCommissionerTake ?? "")} onChange={(event) => edit("openingCommissionerTake", event.target.value)} rows={3} className="rounded-lg border border-slate-900/10 p-2 text-sm normal-case tracking-normal dark:border-white/10 dark:bg-white/[0.04]" /></label><label className="grid gap-2 text-xs font-black uppercase tracking-widest">Team One-Liners (JSON)<textarea value={JSON.stringify(draft.teamOneLiners ?? [], null, 2)} onChange={(event) => { try { edit("teamOneLiners", JSON.parse(event.target.value)); } catch { /* wait for valid JSON */ } }} rows={5} className="rounded-lg border border-slate-900/10 p-2 text-sm normal-case tracking-normal dark:border-white/10 dark:bg-white/[0.04]" /></label><label className="grid gap-2 text-xs font-black uppercase tracking-widest">Notable Draft Decisions<textarea value={Array.isArray(draft.notableDraftDecisions) ? (draft.notableDraftDecisions as string[]).join("\n") : ""} onChange={(event) => edit("notableDraftDecisions", event.target.value.split("\n"))} rows={4} className="rounded-lg border border-slate-900/10 p-2 text-sm normal-case tracking-normal dark:border-white/10 dark:bg-white/[0.04]" /></label><label className="grid gap-2 text-xs font-black uppercase tracking-widest">Closing Commissioner Take<textarea value={String(draft.closingTake ?? "")} onChange={(event) => edit("closingTake", event.target.value)} rows={3} className="rounded-lg border border-slate-900/10 p-2 text-sm normal-case tracking-normal dark:border-white/10 dark:bg-white/[0.04]" /></label></div></>}</div></div>}
  </section>;
}
