import type { CanonicalPowerRankings } from "@/lib/powerRankings/types";

const components = [["starters", "STARTERS"], ["depth", "DEPTH"], ["qb", "QB"], ["rb", "RB"], ["wr", "WR"], ["te", "TE"], ["flex", "FLEX"]] as const;

function explanation(value: string) {
  const match = value.match(/^(.+?) \d+(?:\.\d+)?\/100 \(league rank (\d+)\/\d+\)$/);
  return { label: match?.[1] ?? value, rank: match ? `#${match[2]} IN LEAGUE` : null };
}

export default function PowerRankingsDetail({ report }: { report: CanonicalPowerRankings }) {
  const tiers = report.teams.reduce<Record<string, number>>((counts, team) => ({ ...counts, [team.tier]: (counts[team.tier] ?? 0) + 1 }), {});
  return <>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5" aria-label="Power Rankings tier distribution">{[["TITLE CONTENDER", "Title Contenders"], ["CONTENDER", "Contenders"], ["PLAYOFF CALIBER", "Playoff Caliber"], ["BUBBLE", "Bubble"], ["LONG SHOT", "Long Shots"]].map(([key, label]) => <div key={key} className="rounded-xl border border-slate-200 bg-white px-4 py-3 dark:border-white/10 dark:bg-[#121212]"><p className="text-[9px] font-black uppercase tracking-widest text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-orange-600">{tiers[key] ?? 0}</p></div>)}</section>
    <section aria-label="Detailed current Power Rankings"><div className="mb-4"><p className="text-sm leading-6 text-slate-600 dark:text-white/60">All 12 current roster-strength rankings, with contender tier, confidence, lineup and depth context, positional diagnostics, and strengths and weaknesses.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{report.teams.map((team) => { const strength = explanation(team.biggestStrength); const weakness = explanation(team.biggestWeakness); return <article key={team.franchiseId} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#121212]"><div className="flex items-start gap-3"><span className="shrink-0 text-4xl font-black italic leading-none text-slate-300 dark:text-white/20">#{team.leagueRelativeRank}</span><div className="min-w-0 flex-1"><h2 className="break-words text-xl font-black uppercase italic leading-tight tracking-tight">{team.teamName}</h2><div className="mt-3 flex flex-wrap items-center gap-2"><p className="inline-flex rounded-full bg-orange-600 px-2.5 py-1.5 text-[9px] font-black uppercase tracking-widest text-white">{team.tier}</p><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">{team.confidence} confidence</p></div></div></div>{team.confidence !== "HIGH" && <p className="mt-3 text-xs leading-5 text-slate-500 dark:text-white/50">Some roster players lack complete current-value or ROS coverage.</p>}<div className="mt-4 grid grid-cols-2 gap-2 border-y border-slate-100 py-4 dark:border-white/10 sm:grid-cols-4">{components.map(([key, label]) => <div key={key}><p className="text-[9px] font-black uppercase tracking-widest text-slate-400">{label}</p><p className="mt-0.5 text-xl font-black leading-none">#{team.components[key].leagueRank ?? "—"}</p></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-[9px] font-black uppercase tracking-widest text-emerald-600">Biggest Strength</p><p className="mt-1 text-sm font-black uppercase leading-5">{strength.label}</p>{strength.rank && <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-slate-500">{strength.rank}</p>}</div><div><p className="text-[9px] font-black uppercase tracking-widest text-red-600">Biggest Weakness</p><p className="mt-1 text-sm font-black uppercase leading-5">{weakness.label}</p>{weakness.rank && <p className="mt-1 text-[10px] font-black uppercase tracking-widest text-slate-500">{weakness.rank}</p>}</div></div></article>; })}</div></section>
    <aside className="rounded-2xl border border-slate-200 bg-white p-5 text-sm leading-6 text-slate-600 shadow-sm dark:border-white/10 dark:bg-[#121212] dark:text-white/60"><p><span className="font-black text-slate-900 dark:text-white">Methodology:</span> {report.semantics}</p><p className="mt-2"><span className="font-black text-slate-900 dark:text-white">Model:</span> {report.modelVersion}; evidence refreshed {new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(report.generatedAt))}.</p><p className="mt-2">Current roster strength only. K/DEF do not materially affect this ranking, and missing data affects confidence rather than applying an automatic penalty.</p></aside>
  </>;
}
