export type ArchivedProposalStatus = "passed" | "failed" | "tied" | "unclear" | "informational";

export interface ArchivedVoteTotals {
  yes?: number;
  no?: number;
  absent?: number;
}

export interface ArchivedOptionCount {
  label: string;
  count: number;
}

export interface ArchivedProposal {
  id: string;
  year: number;
  title: string;
  status: ArchivedProposalStatus;
  description: string;
  sourceFile: string;
  section?: string;
  category?: string;
  sponsor?: string;
  voteTotals?: ArchivedVoteTotals;
  options?: ArchivedOptionCount[];
  winningOption?: string;
  notes?: string;
}

export interface LegislativeArchiveSession {
  year: number;
  title: string;
  notes?: string;
  proposals: ArchivedProposal[];
}

export const LEGISLATIVE_ARCHIVE_YEARS = [2026, 2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018] as const;

const SOURCE_2018 = "2018 League Changes (Responses).xlsx";
const SOURCE_2019 = "2019 River City Rule Suggestions (Responses).xlsx";
const SOURCE_2020 = "3_31_20 - Owners Meeting Vote.docx";
const SOURCE_2021_WINTER = "2021_03_09_Winter_Owners_Meeting.xlsx";
const SOURCE_2021_ABSENTEE = "2021 Winter Owner's Meeting Absentee Ballot (Responses).xlsx";
const SOURCE_2021_SPRING = "2021_05_12_Spring_Owner's_Meeting.xlsx";
const SOURCE_2022 = "2022 River City Fantasy Football League Meeting (Responses).xlsx";
const SOURCE_2023 = "2023 Offseason Voting (Responses).xlsx";
const SOURCE_2024 = "2024 Offseason Voting (Responses).xlsx";
const SOURCE_2025 = "2025 Offseason Voting (Responses).xlsx";

export const LEGISLATIVE_ARCHIVE: LegislativeArchiveSession[] = [
  {
    year: 2026,
    title: "2026 Legislative Session",
    notes: "Digitized from the current Legislative Hub records available in this app. Historical records are informational only.",
    proposals: [
      {
        id: "2026-roster-continuity-clause",
        year: 2026,
        title: "Roster Continuity Clause",
        status: "passed",
        section: "4.3 Keepers",
        category: "Keepers",
        sponsor: "Jordan Maslyn",
        sourceFile: "Current Legislative Hub Firestore records",
        voteTotals: { yes: 9, no: 1 },
        description:
          "Allow keeper eligibility for any player drafted and held on the original owner's roster for the duration of the season, regardless of starting lineup status.",
        notes: "Matched to the finalized live proposal confirmed for the 2026 session.",
      },
      {
        id: "2026-authority-hardline",
        year: 2026,
        title: "Don't Be A Bitch Rule",
        status: "passed",
        section: "1.4 Authority",
        category: "Authority",
        sponsor: "Doug Fordham",
        sourceFile: "Current Legislative Hub Firestore records",
        voteTotals: { yes: 10, no: 0 },
        description:
          "All confirmed roster moves, including waivers, trades, free agency, and FAAB bids, are final and non-reversible. Owner errors, misclicks, or accidental overbidding are not grounds for commissioner intervention or league appeals.",
        notes: "Matched to the finalized live proposal confirmed for the 2026 session.",
      },
    ],
  },
  {
    year: 2025,
    title: "2025 Legislative Session",
    notes: "Normalized from the 2025 offseason voting response file.",
    proposals: [
      {
        id: "2025-draft-date",
        year: 2025,
        title: "2025 Draft Date",
        status: "informational",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sourceFile: SOURCE_2025,
        winningOption: "August 15-17 weekend",
        options: [
          { label: "August 15-17 weekend", count: 7 },
          { label: "Friday August 29-31 (Labor Day Weekend)", count: 4 },
          { label: "Either option is good", count: 1 },
        ],
        description: "Owners selected the August 15-17 weekend as the preferred 2025 draft window.",
      },
      {
        id: "2025-draft-location",
        year: 2025,
        title: "Different Draft Location",
        status: "failed",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sourceFile: SOURCE_2025,
        voteTotals: { yes: 5, no: 7 },
        description: "Proposal to move the 2025 draft to a different location instead of keeping it in Richmond.",
      },
      {
        id: "2025-aaron-team-name",
        year: 2025,
        title: "Aaron Team Name",
        status: "informational",
        category: "League Culture",
        sourceFile: SOURCE_2025,
        description:
          "Open-ended naming prompt for Aaron's team. Responses included several one-off names and did not produce a clear ballot-style winner.",
        notes: "This is a culture/housekeeping item, not a constitution rule vote.",
      },
      {
        id: "2025-remove-offseason-faab-trading",
        year: 2025,
        title: "Remove Offseason FAAB-for-Player Trading",
        status: "passed",
        section: "5.2 Trading",
        category: "FAAB / Trading",
        sourceFile: SOURCE_2025,
        voteTotals: { yes: 12, no: 0 },
        description: "Remove trading of FAAB for players prior to the draft.",
      },
      {
        id: "2025-keeper-handling",
        year: 2025,
        title: "Keeper Handling",
        status: "failed",
        section: "4.3 Keepers",
        category: "Keepers",
        sourceFile: SOURCE_2025,
        options: [
          { label: "No change to the current keeper rule", count: 7 },
          { label: "No keep the current keeper rule", count: 1 },
          { label: "Only keep 2 keepers based on drafted/free-agent players", count: 3 },
          { label: "Keep 2 players, plus $20 value increase for players acquired from another team", count: 1 },
        ],
        winningOption: "No change to the current keeper rule",
        description: "Proposed keeper changes did not beat the current keeper rule.",
        notes: "Two current-rule responses were worded differently and are treated together as an 8-4 current-rule result.",
      },
      {
        id: "2025-rookie-hazing-beer-rule",
        year: 2025,
        title: "Change Rookie Hazing Rule for Beer Purchase",
        status: "passed",
        section: "2.1 Rookie Hazing",
        category: "League Culture",
        sourceFile: SOURCE_2025,
        voteTotals: { yes: 9, no: 2 },
        description:
          "Modify rookie hazing so the rookie buys the champion and Toilet Bowl loser a drink at the draft location.",
        notes: "One response was blank.",
      },
    ],
  },
  {
    year: 2024,
    title: "2024 Legislative Session",
    notes: "Normalized from the 2024 offseason voting response file.",
    proposals: [
      {
        id: "2024-draft-date",
        year: 2024,
        title: "2024 Draft Date",
        status: "informational",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sourceFile: SOURCE_2024,
        winningOption: "Friday August 30th at 5pm",
        options: [
          { label: "Friday August 30th at 5pm (Labor Day Weekend)", count: 10 },
          { label: "The weekend before", count: 1 },
          { label: "Billy Biddle", count: 1 },
        ],
        description: "Owners selected Friday August 30th at 5pm for the 2024 draft.",
      },
      {
        id: "2024-keeper-lock-date",
        year: 2024,
        title: "Keeper Lock Date",
        status: "passed",
        section: "4.3 Keepers",
        category: "Keepers",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 8, no: 4 },
        description: "Move the keeper lock date to when the draft starts instead of one week before the draft.",
      },
      {
        id: "2024-drop-keeper-new-player-value",
        year: 2024,
        title: "Drop Keeper if New Player Affects Value",
        status: "tied",
        section: "4.3 Keepers",
        category: "Keepers",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 6, no: 6 },
        description:
          "Whether an owner can drop a keeper if a new player is added during the offseason and affects keeper value.",
      },
      {
        id: "2024-remove-toilet-bowl-payment",
        year: 2024,
        title: "Remove Toilet Bowl Payment Portion",
        status: "passed",
        section: "2.2 Last Place Punishment",
        category: "Punishment / Finance",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 12, no: 0 },
        description: "Remove the payment portion of the Toilet Bowl loser punishment.",
      },
      {
        id: "2024-auctioneer-dinner-split",
        year: 2024,
        title: "Split Auctioneer Dinner and Drinks",
        status: "passed",
        section: "6.1 Draft Details",
        category: "Draft / Finance",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 12, no: 0 },
        description: "All owners split the cost for the auctioneer's dinner and drinks on draft night.",
        winningOption: "Yes - $5",
      },
      {
        id: "2024-wednesday-waiver-time",
        year: 2024,
        title: "Wednesday Waiver Time",
        status: "failed",
        section: "5.1 Free Agency (FAAB)",
        category: "Waivers",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 2, no: 10 },
        description: "Proposal to move Wednesday morning waivers to 3am ET instead of 12pm ET.",
      },
      {
        id: "2024-keeper-limit-2025",
        year: 2024,
        title: "Modify Keeper Amount Starting in 2025",
        status: "passed",
        section: "4.3 Keepers",
        category: "Keepers",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 7, no: 5 },
        description: "Move to 2 keepers max and 1 per position starting in 2025.",
      },
      {
        id: "2024-fourth-third-place-payouts",
        year: 2024,
        title: "Remove 4th Place Payout and Reduce 3rd Place",
        status: "passed",
        section: "11 Financial Transparency",
        category: "Finance",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 12, no: 0 },
        description: "Remove the 4th place payout and reduce 3rd place to the entry fee.",
      },
      {
        id: "2024-division-winner-payout",
        year: 2024,
        title: "Division Winner Payout",
        status: "passed",
        section: "11 Financial Transparency",
        category: "Finance",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 9, no: 3 },
        description: "Pay each division winner $25.",
      },
      {
        id: "2024-high-score-regardless-recap",
        year: 2024,
        title: "High Score Payout Regardless of Recap",
        status: "passed",
        section: "11 Financial Transparency",
        category: "Finance",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 11, no: 1 },
        description: "Pay high score regardless of recap status.",
      },
      {
        id: "2024-borderline-trade-veto-flag",
        year: 2024,
        title: "Borderline Trade Veto Flag",
        status: "passed",
        section: "5.2 Trading",
        category: "Trading",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 9, no: 3 },
        description: "Use 1 veto flag per person per season on borderline sketchy or unfair trades.",
      },
      {
        id: "2024-every-two-years-draft-trip",
        year: 2024,
        title: "Every-Two-Years Draft Trip",
        status: "passed",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sourceFile: SOURCE_2024,
        voteTotals: { yes: 11, no: 1 },
        description: "Try to plan an every-two-years draft trip with a Zoom option.",
      },
    ],
  },
  {
    year: 2023,
    title: "2023 Legislative Session",
    notes: "Normalized from the 2023 offseason voting response file. One reseeding item includes manual annotations in the vote column.",
    proposals: [
      {
        id: "2023-remove-loser-bracket-payout",
        year: 2023,
        title: "Remove Loser Bracket Payout",
        status: "passed",
        section: "11 Financial Transparency",
        category: "Finance / Postseason",
        sourceFile: SOURCE_2023,
        voteTotals: { yes: 12, no: 0 },
        description: "Remove the Loser Bracket payout.",
      },
      {
        id: "2023-remove-fourth-place-payout",
        year: 2023,
        title: "Remove 4th Place Payout",
        status: "failed",
        section: "11 Financial Transparency",
        category: "Finance",
        sourceFile: SOURCE_2023,
        voteTotals: { yes: 4, no: 8 },
        description: "Proposal to remove the 4th place payout.",
      },
      {
        id: "2023-draft-trading",
        year: 2023,
        title: "Trade Players or Draft Dollars During Draft",
        status: "failed",
        section: "5.2 Trading",
        category: "Draft / Trading",
        sourceFile: SOURCE_2023,
        voteTotals: { yes: 3, no: 9 },
        description: "Proposal to allow owners to trade players and/or draft dollars during the draft.",
      },
      {
        id: "2023-sunday-waiver-rule",
        year: 2023,
        title: "Sunday Waiver Rule",
        status: "failed",
        section: "5.1 Free Agency (FAAB)",
        category: "Waivers",
        sourceFile: SOURCE_2023,
        options: [
          { label: "Current waivers rule retained", count: 7 },
          { label: "Free Agency all day", count: 3 },
          { label: "Waivers to FA after clearing once", count: 2 },
        ],
        winningOption: "Current waivers rule retained",
        description: "Proposed Sunday waiver changes did not beat the current waiver rule.",
      },
      {
        id: "2023-playoffs-start-week-14",
        year: 2023,
        title: "Playoffs Start Week 14",
        status: "failed",
        section: "8.1 Playoffs",
        category: "Postseason",
        sourceFile: SOURCE_2023,
        voteTotals: { yes: 0, no: 12 },
        winningOption: "Week 15 retained",
        description: "Proposal to start playoffs in Week 14 failed; Week 15 remained the current rule.",
      },
      {
        id: "2023-winners-bracket-reseeding",
        year: 2023,
        title: "Winner's Bracket Reseeding",
        status: "unclear",
        section: "8.1 Playoffs",
        category: "Postseason",
        sourceFile: SOURCE_2023,
        voteTotals: { yes: 7, no: 5 },
        description: "Whether Sleeper should reseed the winner's bracket so the highest seed always plays the lowest seed.",
        notes:
          "The form responses show 7 Yes / 5 No, but the same column also contains manual annotation rows with owner names and changed-vote notes. Preserve as unclear until reconciled.",
      },
      {
        id: "2023-toilet-bowl-cap",
        year: 2023,
        title: "Toilet Bowl Loser Cap",
        status: "passed",
        section: "2.2 Last Place Punishment",
        category: "League Culture / Punishment",
        sourceFile: SOURCE_2023,
        options: [
          { label: "$30 or 3 drinks, whichever is greater", count: 7 },
          { label: "$50 cap", count: 5 },
        ],
        winningOption: "$30 or 3 drinks, whichever is greater",
        description: "Set the Toilet Bowl loser cap at $30 or 3 drinks, whichever is greater.",
      },
      {
        id: "2023-one-off-flexibility",
        year: 2023,
        title: "One-Off Situation Flexibility",
        status: "passed",
        section: "9 Issue Resolution Process",
        category: "Governance",
        sponsor: "Jordan & Travis",
        sourceFile: SOURCE_2023,
        options: [
          { label: "New operating procedure to be drafted by Jordan & Travis", count: 9 },
          { label: "Leave as is", count: 3 },
        ],
        winningOption: "New operating procedure to be drafted by Jordan & Travis",
        description: "Create a new operating procedure for flexible handling of unique one-off situations.",
        notes: "Sponsor inferred from the selected option text naming Jordan & Travis as drafters.",
      },
    ],
  },
  {
    year: 2022,
    title: "2022 Legislative Session",
    notes: "Normalized from the 2022 River City Fantasy Football League Meeting response file.",
    proposals: [
      {
        id: "2022-draft-weekend",
        year: 2022,
        title: "Draft Weekend",
        status: "informational",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sponsor: "Tommy",
        sourceFile: SOURCE_2022,
        options: [
          { label: "Sep 2/3", count: 7 },
          { label: "Aug 12/13", count: 5 },
        ],
        winningOption: "Sep 2/3",
        description: "Owners selected Sep 2/3 for the draft weekend.",
      },
      {
        id: "2022-draft-faab-trading",
        year: 2022,
        title: "Trade FAAB During or Before Draft",
        status: "failed",
        section: "5.2 Trading",
        category: "FAAB / Draft Trading",
        sponsor: "Doug",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 2, no: 10 },
        description: "Proposal to allow teams to trade players and/or FAAB dollars during or before the draft.",
      },
      {
        id: "2022-in-season-faab-trading",
        year: 2022,
        title: "Allow In-Season FAAB Trading",
        status: "passed",
        section: "5.2 Trading",
        category: "FAAB / Trading",
        sponsor: "Doug & Tommy",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 8, no: 4 },
        description: "Allow FAAB trading during the season, not during the offseason.",
      },
      {
        id: "2022-free-agents-between-games",
        year: 2022,
        title: "Acquire Free Agents After Noon Before 4pm",
        status: "tied",
        section: "5.1 Free Agency (FAAB)",
        category: "Free Agency",
        sponsor: "JD",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 6, no: 6 },
        description: "Whether owners can acquire free agents after the noon game and before the 4pm game.",
      },
      {
        id: "2022-two-ir-spots",
        year: 2022,
        title: "Increase IR to 2 Spots",
        status: "passed",
        section: "4.2.1 IR Enforcement",
        category: "Rosters / IR",
        sponsor: "Ray",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 7, no: 5 },
        description: "Increase the IR spot from 1 player to 2 players.",
      },
      {
        id: "2022-dst-individual-st-touchdowns",
        year: 2022,
        title: "D/ST and Individual ST Touchdown Scoring",
        status: "passed",
        section: "4.4 Scoring System",
        category: "Scoring",
        sponsor: "Jordan",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 10, no: 2 },
        description: "Allow both the D/ST and individual special teams player to get points if they score a touchdown.",
      },
      {
        id: "2022-zero-dollar-bids",
        year: 2022,
        title: "$0 Free Agent Bids",
        status: "passed",
        section: "5.1 Free Agency (FAAB)",
        category: "FAAB",
        sponsor: "Tommy",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 8, no: 4 },
        description: "Allow $0 bids on free agents.",
      },
      {
        id: "2022-playoff-reseeding",
        year: 2022,
        title: "Playoff Reseeding",
        status: "failed",
        section: "8.1 Playoffs",
        category: "Postseason",
        sponsor: "Ray",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 5, no: 7 },
        description: "Proposal to reseed the playoffs so the higher seed plays the lower seed each round.",
      },
      {
        id: "2022-toilet-bowl-hazing",
        year: 2022,
        title: "Toilet Bowl Loser Bracket Hazing",
        status: "passed",
        section: "2.2 Last Place Punishment",
        category: "Postseason / Punishment",
        sponsor: "Doug",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 11, no: 1 },
        description: "Use the Toilet Bowl option in the loser bracket and make that loser the one hazed for the upcoming season.",
      },
      {
        id: "2022-last-place-number-one-nomination",
        year: 2022,
        title: "Last Place Gets #1 Nomination",
        status: "passed",
        section: "6.2 Nomination Order",
        category: "Draft",
        sponsor: "Ray",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 10, no: 2 },
        description: "Give the last place regular season team the #1 nomination in the upcoming draft.",
      },
      {
        id: "2022-sleeper-settings-allowance",
        year: 2022,
        title: "Sleeper Settings Default Allowance",
        status: "passed",
        section: "1.5 Sleeper Rule Allowances",
        category: "Governance",
        sponsor: "JD",
        sourceFile: SOURCE_2022,
        voteTotals: { yes: 8, no: 4 },
        description: "If the selected Sleeper settings allow something, the league should allow it unless a local rule says otherwise.",
      },
    ],
  },
  {
    year: 2021,
    title: "2021 Legislative Session",
    notes:
      "Normalized from the winter owners meeting and spring follow-up. The absentee ballot is treated as a duplicate/reference source for sponsor wording and longer option labels.",
    proposals: [
      {
        id: "2021-rules-overhaul",
        year: 2021,
        title: "Rules Overhaul",
        status: "failed",
        category: "Governance",
        sponsor: "Tommy & The Champ",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 1, no: 10 },
        description: "Proposal to burn down the existing rules and use Sleeper rules by default.",
        notes: `Duplicate/reference source: ${SOURCE_2021_ABSENTEE}.`,
      },
      {
        id: "2021-keeper-free-agent-eligibility",
        year: 2021,
        title: "Free Agent Keeper Eligibility",
        status: "failed",
        section: "4.3 Keepers",
        category: "Keepers",
        sponsor: "Landon, Travis, Dave & The Champ",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 3, no: 8 },
        description: "Whether players picked up from free agency can be used as keepers the following year.",
        notes: `Duplicate/reference source: ${SOURCE_2021_ABSENTEE}.`,
      },
      {
        id: "2021-remove-position-cap",
        year: 2021,
        title: "Remove Position Cap",
        status: "passed",
        section: "4.2 Roster Structure",
        category: "Rosters",
        sponsor: "Dave",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 10, no: 1 },
        description: "Remove position caps from rosters.",
      },
      {
        id: "2021-preseason-trades",
        year: 2021,
        title: "Preseason Trades",
        status: "unclear",
        section: "5.2 Trading",
        category: "Trading",
        sponsor: "Tommy",
        sourceFile: SOURCE_2021_WINTER,
        options: [
          { label: "Allow Unlimited", count: 4 },
          { label: "Declare prior to preseason", count: 1 },
          { label: "Table Preseason", count: 1 },
          { label: "Reset Rosters every 3 years - Keepers", count: 1 },
        ],
        winningOption: "Allow Unlimited",
        description: "Preseason trade options were voted on, with Allow Unlimited receiving the most votes.",
        notes: "Spreadsheet includes extra non-owner option rows, so preserve as unclear until meeting minutes confirm final passage.",
      },
      {
        id: "2021-faab-enforcement",
        year: 2021,
        title: "Free Agency Bidding Enforcement",
        status: "passed",
        section: "5.1 Free Agency (FAAB)",
        category: "FAAB",
        sponsor: "Ray",
        sourceFile: SOURCE_2021_WINTER,
        options: [
          { label: "If $1+, commissioner gives owner option", count: 7 },
          { label: "Allow $0 bid, player costs $12 to keep", count: 2 },
          { label: "If $0, commissioner removes player", count: 2 },
        ],
        winningOption: "If $1+, commissioner gives owner option",
        description: "Adopted the FAAB enforcement option where the commissioner gives the owner an option if the owner has $1+ FAAB.",
      },
      {
        id: "2021-trade-deadline",
        year: 2021,
        title: "Trade Deadline",
        status: "passed",
        section: "5.2 Trading",
        category: "Trading",
        sponsor: "Tommy, Brian, Travis, Dave & The Champ",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 10, no: 1 },
        winningOption: "Match up with Sleeper / Week 9",
        description: "Move the trade deadline to match the Sleeper app timing, recorded as Week 9.",
      },
      {
        id: "2021-sleeper-auto-accept",
        year: 2021,
        title: "Sleeper Auto Accept",
        status: "passed",
        section: "5.2 Trading",
        category: "Trading",
        sponsor: "Dave",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 11, no: 0 },
        description: "Use Sleeper auto-accept for in-season trades.",
      },
      {
        id: "2021-trade-clarification",
        year: 2021,
        title: "In-Season Trade Rule Clarification",
        status: "failed",
        section: "5.2 Trading",
        category: "Trading",
        sponsor: "Ray",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 4, no: 8 },
        winningOption: "No, wait",
        description: "Proposal to allow starting a newly acquired player if they had not already played lost to waiting until the following week.",
      },
      {
        id: "2021-new-ir-rule",
        year: 2021,
        title: "New IR Rule",
        status: "passed",
        section: "4.2.1 IR Enforcement",
        category: "Rosters / IR",
        sponsor: "Brian",
        sourceFile: SOURCE_2021_WINTER,
        options: [
          { label: "Opt 4", count: 7 },
          { label: "Opt 2", count: 2 },
          { label: "Opt 3", count: 2 },
        ],
        winningOption: "Opt 4",
        description: "Adopted IR Option 4 from the winter meeting summary.",
        notes: "The final tally sheet uses option shorthand; the absentee ballot provides longer option text but does not conclusively map Opt 4.",
      },
      {
        id: "2021-active-lineup",
        year: 2021,
        title: "Active Lineup Requirement",
        status: "passed",
        section: "7.3 Owner Responsibilities",
        category: "Lineups",
        sponsor: "Ray & The Champ",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 7, no: 4 },
        description: "Require owners to have a player in each of the 8 starting lineup positions.",
      },
      {
        id: "2021-additional-punishment",
        year: 2021,
        title: "Additional Punishment Rule",
        status: "passed",
        section: "2.2 Last Place Punishment",
        category: "Punishment",
        sponsor: "Doug",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 9, no: 1 },
        description: "Add an additional punishment rule beyond existing last-place consequences.",
      },
      {
        id: "2021-owner-conduct",
        year: 2021,
        title: "Owner Conduct Rules",
        status: "failed",
        section: "10.2 Conduct Expectations",
        category: "Conduct",
        sponsor: "Ray",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 2, no: 7 },
        description: "Proposal to add a snippet around owner conduct for new owners and verbal agreement from current owners.",
      },
      {
        id: "2021-best-interest-clause",
        year: 2021,
        title: "Best Interest Clause",
        status: "failed",
        section: "1.4 Authority Boundaries",
        category: "Governance",
        sponsor: "Ray",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 1, no: 8 },
        description: "Proposal to add a formal best-interest clause.",
      },
      {
        id: "2021-sleeper-rule-documentation",
        year: 2021,
        title: "Sleeper Rule Documentation",
        status: "unclear",
        section: "1.5 Sleeper Rule Allowances",
        category: "Governance",
        sponsor: "Ray",
        sourceFile: SOURCE_2021_WINTER,
        options: [
          { label: "Do whatever you want", count: 4 },
          { label: "No", count: 3 },
          { label: "Yes", count: 2 },
        ],
        description: "Whether to document all Sleeper rules so there is no gray area or unspoken rule.",
        notes: "Result does not cleanly map to passed/failed because the leading option is informal.",
      },
      {
        id: "2021-draft-date",
        year: 2021,
        title: "2021 Draft Date",
        status: "informational",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sourceFile: SOURCE_2021_WINTER,
        options: [
          { label: "Labor Day", count: 7 },
          { label: "Don't care", count: 1 },
          { label: "Don't plan", count: 1 },
        ],
        winningOption: "Labor Day",
        description: "Owners selected Labor Day timing for the 2021 draft.",
      },
      {
        id: "2021-draft-format",
        year: 2021,
        title: "2021 Draft Format",
        status: "informational",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sourceFile: SOURCE_2021_WINTER,
        options: [
          { label: "Option based on comfort", count: 8 },
          { label: "Revisit in July", count: 1 },
        ],
        winningOption: "Option based on comfort",
        description: "Owners selected giving each owner a draft participation option based on comfort.",
      },
      {
        id: "2021-future-drafts",
        year: 2021,
        title: "Future Drafts",
        status: "informational",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sourceFile: SOURCE_2021_WINTER,
        options: [
          { label: "Punt for future", count: 4 },
          { label: "Give option", count: 2 },
          { label: "Keep in person", count: 2 },
          { label: "Fully Zoom", count: 1 },
        ],
        winningOption: "Punt for future",
        description: "Future draft format was deferred.",
      },
      {
        id: "2021-add-second-rb",
        year: 2021,
        title: "Add Another RB",
        status: "tied",
        section: "4.2 Roster Structure",
        category: "Rosters",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 2, no: 2 },
        description: "Proposal to add another running back position to the starting lineup.",
      },
      {
        id: "2021-commitment-date",
        year: 2021,
        title: "Commitment Date to Leave League",
        status: "unclear",
        section: "1.3 League Membership",
        category: "League Membership",
        sourceFile: SOURCE_2021_WINTER,
        voteTotals: { yes: 2, no: 1 },
        description: "Proposal for owners leaving the league to give advance notice before the draft.",
        notes: "Only three responses are recorded in the meeting summary.",
      },
      {
        id: "2021-spring-preseason-trade-followup",
        year: 2021,
        title: "Spring Preseason Trade Follow-Up",
        status: "unclear",
        section: "5.2 Trading",
        category: "Trading",
        sourceFile: SOURCE_2021_SPRING,
        options: [
          { label: "Opt 1", count: 5 },
          { label: "After 2nd Preseason", count: 1 },
          { label: "Allow Unlimited", count: 1 },
          { label: "Declare prior to preseason", count: 1 },
        ],
        winningOption: "Opt 1",
        description: "Spring follow-up vote on preseason trade handling.",
        notes: "Option shorthand is not defined in the sheet.",
      },
      {
        id: "2021-spring-keeper-option",
        year: 2021,
        title: "Spring Keeper Option",
        status: "unclear",
        section: "4.3 Keepers",
        category: "Keepers",
        sourceFile: SOURCE_2021_SPRING,
        options: [{ label: "Opt 1", count: 5 }],
        winningOption: "Opt 1",
        description: "Spring follow-up vote on keeper option.",
        notes: "Option shorthand is not defined in the sheet.",
      },
      {
        id: "2021-spring-league-reset",
        year: 2021,
        title: "Spring League Reset",
        status: "unclear",
        category: "Governance",
        sourceFile: SOURCE_2021_SPRING,
        options: [{ label: "Opt 2", count: 5 }],
        winningOption: "Opt 2",
        description: "Spring follow-up vote on league reset.",
        notes: "Option shorthand is not defined in the sheet.",
      },
    ],
  },
  {
    year: 2020,
    title: "2020 Legislative Session",
    notes: "Normalized from the 3/31/20 owners meeting vote document.",
    proposals: [
      {
        id: "2020-sleeper-default-faab-order",
        year: 2020,
        title: "Sleeper Default FAAB Order",
        status: "passed",
        section: "5.1 Free Agency (FAAB)",
        category: "FAAB / Waivers",
        sourceFile: SOURCE_2020,
        description: "Starting in the 2020 season, the league uses Sleeper's default FAAB order.",
        notes: "The document states this as an adopted topic but does not include explicit vote totals on this line.",
      },
      {
        id: "2020-waiver-tiebreaker",
        year: 2020,
        title: "Rolling Waiver Priority Tiebreaker",
        status: "passed",
        section: "5.1.1 Waiver Tiebreaker",
        category: "Waivers",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 8, no: 1, absent: 3 },
        description:
          "In the event of a tie, use a continuing rolling list waiver priority order originally based on draft order.",
      },
      {
        id: "2020-playoff-standings-reorganization",
        year: 2020,
        title: "Reorganize Playoff Standings",
        status: "failed",
        section: "8.1 Playoffs",
        category: "Postseason",
        sponsor: "Doug",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 1, no: 8, absent: 3 },
        description:
          "Proposal to reorganize playoff standings failed; division winners remained seeds 1-3, next best record 4th, and top two points-for teams 5th and 6th.",
      },
      {
        id: "2020-rookie-punishment-beer",
        year: 2020,
        title: "Rookie Punishment Beer Rule",
        status: "passed",
        section: "2.1 Rookie Hazing",
        category: "League Culture / Punishment",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 9, no: 1, absent: 2 },
        description: "Replace the prior rookie punishment with requiring the rookie to bring beer for everyone to drink at the draft.",
      },
      {
        id: "2020-last-place-punishment",
        year: 2020,
        title: "Last Place Punishment",
        status: "passed",
        section: "2.2 Last Place Punishment",
        category: "League Culture / Punishment",
        sourceFile: SOURCE_2020,
        description:
          "The final postseason loser finishing 12th must buy Damon food and beer prior to the draft, beginning with the 2020-2021 season.",
        notes: "Passed unanimously; exact yes count is not stated.",
      },
      {
        id: "2020-lopsided-trades",
        year: 2020,
        title: "No Lopsided Trades for Eliminated Teams",
        status: "failed",
        section: "5.2 Trading",
        category: "Trading",
        sponsor: "Ray",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 1, no: 9, absent: 2 },
        description:
          "Proposal to prohibit lopsided regular season trades by eliminated teams failed; potentially collusive trades require objection and league vote.",
      },
      {
        id: "2020-playoff-free-agent-keepers",
        year: 2020,
        title: "Playoff Free Agent Keepers",
        status: "failed",
        section: "4.3 Keepers",
        category: "Keepers / Free Agency",
        sponsor: "Doug",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 5, no: 6, absent: 1 },
        description: "Proposal to allow free-agent acquisitions in the playoffs to be keepers after the regular season ends failed.",
      },
      {
        id: "2020-playoff-player-acquisitions",
        year: 2020,
        title: "Playoff Player Acquisitions",
        status: "passed",
        section: "5.1 Free Agency (FAAB)",
        category: "Postseason / Free Agency",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 9, no: 1, absent: 2 },
        description:
          "Allow all teams with games remaining to acquire players during the playoffs; once a team's season is over, that team cannot pick up players.",
      },
      {
        id: "2020-loser-bracket-winner-draft-pick",
        year: 2020,
        title: "Loser Bracket Winner Gets #1 Pick",
        status: "passed",
        section: "6.2 Nomination Order",
        category: "Draft / Postseason",
        sourceFile: SOURCE_2020,
        description:
          "Award the loser bracket winner the number 1 pick and use snake nomination order based on final placement.",
        notes: "Passed unanimously; exact yes count is not stated.",
      },
      {
        id: "2020-two-rbs",
        year: 2020,
        title: "Two Running Backs",
        status: "failed",
        section: "4.2 Roster Structure",
        category: "Rosters",
        sponsor: "Ray",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 2, no: 8, absent: 2 },
        description: "Proposal to add a second running back spot failed.",
      },
      {
        id: "2020-offseason-keeper-limit",
        year: 2020,
        title: "Offseason Keeper Limit",
        status: "failed",
        section: "4.3 Keepers",
        category: "Keepers",
        sponsor: "Ray",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 4, no: 6, absent: 2 },
        description: "Proposal to limit offseason keepers failed; the league stayed with 1 keeper per position.",
      },
      {
        id: "2020-payout-structure",
        year: 2020,
        title: "New Payout Structure",
        status: "passed",
        section: "11 Financial Transparency",
        category: "Finance",
        sourceFile: SOURCE_2020,
        description:
          "Adopt Week 1-13 high score $10, loser bracket winner $25, 4th place $25, 3rd place $75, 2nd place $100, and champion $240.",
        notes: "Passed unanimously; exact yes count is not stated.",
      },
      {
        id: "2020-division-count",
        year: 2020,
        title: "Change to 1 or 2 Divisions",
        status: "failed",
        section: "4.1 Divisions",
        category: "Divisions",
        sponsor: "Doug",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 4, no: 6, absent: 2 },
        description: "Proposal to change to 1 or 2 divisions failed after debate; the league kept 3 divisions.",
      },
      {
        id: "2020-faab-rollover",
        year: 2020,
        title: "FAAB Rollover After Draft",
        status: "failed",
        section: "5.1 Free Agency (FAAB)",
        category: "FAAB",
        sponsor: "JD",
        sourceFile: SOURCE_2020,
        voteTotals: { yes: 4, no: 5, absent: 3 },
        description: "Proposal to roll over FAAB after the draft into the regular season failed.",
      },
      {
        id: "2020-draft-date",
        year: 2020,
        title: "2020 Draft Date",
        status: "informational",
        section: "6.1 Draft Details",
        category: "Draft Logistics",
        sourceFile: SOURCE_2020,
        winningOption: "Friday 9/4/20",
        description:
          "Owners agreed to draft on Friday 9/4/20, with dinner/happy hour near Wade's new office and Zoom as a fallback for social distancing.",
      },
    ],
  },
  {
    year: 2019,
    title: "2019 Legislative Session",
    notes: "Normalized from the 2019 River City Rule Suggestions response file.",
    proposals: [
      {
        id: "2019-rb-wr-position-cap",
        year: 2019,
        title: "Increase RB/WR Position Cap",
        status: "failed",
        section: "4.2 Roster Structure",
        category: "Rosters",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 5, no: 7 },
        description: "Proposal to increase the RB and WR position cap from 6 to 8 failed.",
      },
      {
        id: "2019-second-rb",
        year: 2019,
        title: "Add Second Starting RB",
        status: "failed",
        section: "4.2 Roster Structure",
        category: "Rosters",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 3, no: 9 },
        description: "Proposal to increase the starting RB position from 1 to 2 failed.",
      },
      {
        id: "2019-kicker-penalties",
        year: 2019,
        title: "Kicker Missed XP/FG Penalties",
        status: "failed",
        section: "4.4 Scoring System",
        category: "Scoring",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 5, no: 7 },
        description: "Proposal to penalize kickers for missed extra points or field goals failed.",
      },
      {
        id: "2019-half-ppr",
        year: 2019,
        title: "0.5 PPR Scoring",
        status: "tied",
        section: "4.4 Scoring System",
        category: "Scoring",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 6, no: 6 },
        description: "Vote on moving to 0.5 PPR ended tied.",
      },
      {
        id: "2019-move-to-sleeper",
        year: 2019,
        title: "Move from ESPN to Sleeper",
        status: "failed",
        section: "1.5 Sleeper Rule Allowances",
        category: "Platform",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 4, no: 8 },
        description: "Proposal to move from ESPN to Sleeper failed; ESPN loyalty won the vote.",
      },
      {
        id: "2019-defensive-scoring",
        year: 2019,
        title: "Change Defensive Scoring",
        status: "passed",
        section: "4.4 Scoring System",
        category: "Scoring",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 9, no: 3 },
        description: "Proposal to change defensive scoring based on NFL rule changes passed.",
      },
      {
        id: "2019-snake-draft",
        year: 2019,
        title: "Snake Draft Order",
        status: "passed",
        section: "6.2 Nomination Order",
        category: "Draft",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 10, no: 2 },
        description: "Proposal to change the draft order to snake draft passed.",
      },
      {
        id: "2019-division-tiebreakers",
        year: 2019,
        title: "Division Tiebreaker Order",
        status: "passed",
        section: "7.2 Standings",
        category: "Standings",
        sourceFile: SOURCE_2019,
        options: [
          { label: "Head to Head, Division Record, Points For", count: 8 },
          { label: "Points For, Head to Head, Division Record", count: 4 },
        ],
        winningOption: "Head to Head, Division Record, Points For",
        description: "Set division tiebreaker order to head-to-head, division record, then points for.",
      },
      {
        id: "2019-remove-divisions-if-points-for",
        year: 2019,
        title: "Remove Divisions if Points For Wins",
        status: "failed",
        section: "4.1 Divisions",
        category: "Divisions",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 5, no: 7 },
        description: "Proposal to get rid of divisions if points for became the ultimate tiebreaker failed.",
      },
      {
        id: "2019-trade-deadline",
        year: 2019,
        title: "Move Trade Deadline Earlier",
        status: "passed",
        section: "5.2 Trading",
        category: "Trading",
        sourceFile: SOURCE_2019,
        options: [
          { label: "Day after NFL deadline passes", count: 10 },
          { label: "Keep deadline where it currently is", count: 1 },
          { label: "Move deadline to Week 7", count: 1 },
        ],
        winningOption: "Day after NFL deadline passes",
        description: "Move the trade deadline to the day after the NFL deadline passes.",
      },
      {
        id: "2019-keeper-trade-same-position",
        year: 2019,
        title: "Keeper/Trade Same-Position Restriction",
        status: "failed",
        section: "4.3 Keepers",
        category: "Keepers / Trading",
        sourceFile: SOURCE_2019,
        voteTotals: { yes: 4, no: 8 },
        description:
          "Proposal to prevent an owner from dealing another player at a position after choosing to keep one player at that same position failed.",
      },
    ],
  },
  {
    year: 2018,
    title: "2018 Legislative Session",
    notes: "Normalized from the 2018 League Changes response file.",
    proposals: [
      {
        id: "2018-auction-value",
        year: 2018,
        title: "Auction Value Change",
        status: "failed",
        section: "6.1 Draft Details",
        category: "Draft / Finance",
        sourceFile: SOURCE_2018,
        voteTotals: { yes: 4, no: 7 },
        description: "Proposal to change auction value failed.",
        notes: "Source question appears to contain a typo: 'increase auction value from to $200 to $100'.",
      },
      {
        id: "2018-second-rb",
        year: 2018,
        title: "Add 2nd Running Back Position",
        status: "failed",
        section: "4.2 Roster Structure",
        category: "Rosters",
        sourceFile: SOURCE_2018,
        voteTotals: { yes: 5, no: 6 },
        description: "Proposal to add a second running back position failed.",
      },
      {
        id: "2018-passing-td-points",
        year: 2018,
        title: "Passing Touchdown Points",
        status: "failed",
        section: "4.4 Scoring System",
        category: "Scoring",
        sourceFile: SOURCE_2018,
        voteTotals: { yes: 4, no: 7 },
        winningOption: "4 points",
        description: "Proposal to move passing touchdowns to 6 points failed; 4-point passing touchdowns stayed in place.",
      },
      {
        id: "2018-ppr",
        year: 2018,
        title: "PPR Scoring",
        status: "failed",
        section: "4.4 Scoring System",
        category: "Scoring",
        sourceFile: SOURCE_2018,
        voteTotals: { yes: 4, no: 7 },
        description: "Proposal to become a PPR league if passing touchdowns stayed at 4 points failed.",
      },
      {
        id: "2018-commissioner-trade-approval",
        year: 2018,
        title: "Commissioner Immediate Trade Approval",
        status: "passed",
        section: "5.2 Trading",
        category: "Trading",
        sourceFile: SOURCE_2018,
        voteTotals: { yes: 8, no: 3 },
        description:
          "Allow the commissioner to immediately approve a trade unless someone thinks it is unfair, in which case it goes to an 8-hour GroupMe poll.",
      },
      {
        id: "2018-ir-player-trades",
        year: 2018,
        title: "IR-for-IR Player Trades",
        status: "passed",
        section: "4.2.1 IR Enforcement",
        category: "Rosters / IR",
        sourceFile: SOURCE_2018,
        voteTotals: { yes: 7, no: 4 },
        description: "Allow trading an IR player for an IR player without having to drop another rostered player.",
      },
    ],
  },
];

export function getArchiveSession(year: number): LegislativeArchiveSession {
  return LEGISLATIVE_ARCHIVE.find((session) => session.year === year) ?? LEGISLATIVE_ARCHIVE[0];
}
