import { canonicalAuctionTeams } from "@/lib/auction/canonicalTeamCatalog";
import { checksum } from "@/lib/seasonSimulator/evidenceSnapshot";

export const WEEKLY_RECAP_DRAFT_SCHEMA = "river-city-weekly-recap-draft-v1" as const;
export type RecapDraftMatchup = Readonly<{ matchupId: number; winnerFranchiseId: string; loserFranchiseId: string; winnerTeam: string; loserTeam: string; winnerScore: number; loserScore: number; margin: number; writeup: string }>;
export type WeeklyRecapDraft = Readonly<{ schemaVersion: typeof WEEKLY_RECAP_DRAFT_SCHEMA; season: number; week: number; status: "REVIEW_DRAFT"; sourceEvidenceChecksums: readonly string[]; title: string; excerpt: string; honors: Readonly<{ highScore: string; lowScore: string; closestGame: string; biggestBlowout: string; toughLuck: string }>; matchups: readonly RecapDraftMatchup[]; standings: readonly Readonly<{ franchiseId: string; teamName: string; owners: readonly string[]; record: string; pf: number; pa: number }>[]; nextWeekSchedule: readonly string[]; draftChecksum: string }>;

type DraftMatchupInput = Readonly<{ matchupId: number; first: { rosterId: number; points: number }; second: { rosterId: number; points: number } }>;

function team(rosterId: number) { const found = canonicalAuctionTeams.find(candidate => candidate.rosterId === rosterId); if (!found) throw new Error(`Unknown River City roster ${rosterId}`); return found; }

export function buildWeeklyRecapDraft(input: { season: number; week: number; matchups: readonly DraftMatchupInput[]; nextWeekSchedule?: readonly DraftMatchupInput[]; sourceEvidenceChecksums: readonly string[] }): WeeklyRecapDraft {
  if (input.matchups.length !== 6 || input.matchups.some(game => !Number.isFinite(game.first.points) || !Number.isFinite(game.second.points))) throw new Error("Recap draft requires six finalized numeric matchups.");
  const records = new Map<number, { wins: number; pf: number; pa: number }>();
  const games = input.matchups.map(game => { const first = team(game.first.rosterId); const second = team(game.second.rosterId); const winner = game.first.points >= game.second.points ? { row: game.first, franchise: first } : { row: game.second, franchise: second }; const loser = winner.franchise.rosterId === first.rosterId ? { row: game.second, franchise: second } : { row: game.first, franchise: first }; records.set(winner.franchise.rosterId, { wins: 1, pf: winner.row.points, pa: loser.row.points }); records.set(loser.franchise.rosterId, { wins: 0, pf: loser.row.points, pa: winner.row.points }); return { matchupId: game.matchupId, winnerFranchiseId: winner.franchise.franchiseId, loserFranchiseId: loser.franchise.franchiseId, winnerTeam: winner.franchise.teamName, loserTeam: loser.franchise.teamName, winnerScore: winner.row.points, loserScore: loser.row.points, margin: Number((winner.row.points - loser.row.points).toFixed(2)), writeup: `${winner.franchise.teamName} beat ${loser.franchise.teamName} ${winner.row.points.toFixed(2)}-${loser.row.points.toFixed(2)}.` }; });
  const standings = [...records.entries()].map(([rosterId, record]) => { const franchise = team(rosterId); return { franchiseId: franchise.franchiseId, teamName: franchise.teamName, owners: franchise.ownerNames, record: `${record.wins}-${record.wins ? 0 : 1}`, pf: record.pf, pa: record.pa }; }).sort((a, b) => b.record.localeCompare(a.record) || b.pf - a.pf || a.teamName.localeCompare(b.teamName));
  const high = [...games].sort((a, b) => b.winnerScore - a.winnerScore || b.loserScore - a.loserScore)[0];
  const low = [...games].sort((a, b) => a.loserScore - b.loserScore)[0];
  const closest = [...games].sort((a, b) => a.margin - b.margin)[0];
  const blowout = [...games].sort((a, b) => b.margin - a.margin)[0];
  const tough = [...games].flatMap(game => [{ team: game.winnerTeam, score: game.winnerScore, record: "1-0" }, { team: game.loserTeam, score: game.loserScore, record: "0-1" }]).filter(row => row.record === "0-1").sort((a, b) => b.score - a.score)[0];
  const base = { schemaVersion: WEEKLY_RECAP_DRAFT_SCHEMA, season: input.season, week: input.week, status: "REVIEW_DRAFT" as const, sourceEvidenceChecksums: [...input.sourceEvidenceChecksums].sort(), title: `WEEK ${input.week}: COMMISSIONER REVIEW DRAFT`, excerpt: `${high.winnerTeam} led the finalized Week ${input.week} scoreboard with ${high.winnerScore.toFixed(2)}.`, honors: { highScore: `${high.winnerTeam} ${high.winnerScore.toFixed(2)}`, lowScore: `${low.loserTeam} ${low.loserScore.toFixed(2)}`, closestGame: `${closest.winnerTeam} over ${closest.loserTeam} by ${closest.margin.toFixed(2)}`, biggestBlowout: `${blowout.winnerTeam} over ${blowout.loserTeam} by ${blowout.margin.toFixed(2)}`, toughLuck: `${tough.team} scored ${tough.score.toFixed(2)} and finished 0-1.` }, matchups: games, standings, nextWeekSchedule: (input.nextWeekSchedule ?? []).map(game => `${team(game.first.rosterId).teamName} vs ${team(game.second.rosterId).teamName}`) };
  return { ...base, draftChecksum: checksum(base) };
}

export type RecapDraftStore = { create(key: string, draft: WeeklyRecapDraft): Promise<"CREATED" | "DUPLICATE">; read(key: string): Promise<WeeklyRecapDraft | null> };
export class MemoryRecapDraftStore implements RecapDraftStore { private readonly drafts = new Map<string, WeeklyRecapDraft>(); async read(key: string) { return this.drafts.get(key) ?? null; } async create(key: string, draft: WeeklyRecapDraft) { const existing = this.drafts.get(key); if (existing) { if (existing.draftChecksum !== draft.draftChecksum) throw new Error("Recap draft conflict."); return "DUPLICATE" as const; } this.drafts.set(key, draft); return "CREATED" as const; } }
export class CloudStorageRecapDraftStore implements RecapDraftStore {
  async read(key: string) { const { getFirebaseStorageBucket } = await import("@/lib/firebaseAdmin"); const file = getFirebaseStorageBucket().file(key); const [exists] = await file.exists(); if (!exists) return null; return JSON.parse((await file.download())[0].toString("utf8")) as WeeklyRecapDraft; }
  async create(key: string, draft: WeeklyRecapDraft) { const { getFirebaseStorageBucket } = await import("@/lib/firebaseAdmin"); const file = getFirebaseStorageBucket().file(key); try { await file.save(JSON.stringify(draft), { resumable: false, preconditionOpts: { ifGenerationMatch: 0 }, metadata: { contentType: "application/json", metadata: { schemaVersion: draft.schemaVersion, checksum: draft.draftChecksum, status: draft.status } } }); return "CREATED" as const; } catch { const existing = await this.read(key); if (existing?.draftChecksum === draft.draftChecksum) return "DUPLICATE" as const; throw new Error("Recap draft conflict."); } }
}
