import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const route = readFileSync("app/api/commish/post-draft/v2/route.ts", "utf8");
const page = readFileSync("app/commish/post-draft/v2/page.tsx", "utf8");
const client = readFileSync("app/commish/post-draft/v2/V2PreviewClient.tsx", "utf8");
const persistence = readFileSync("lib/draftReportV2/persistence.ts", "utf8");
const review = readFileSync("lib/draftReportV2/review.ts", "utf8");
assert.match(route, /requireAuctionAccess\("maintenance"\)/);
assert.match(route, /freeze-v2-snapshot/);
assert.match(route, /GET/);
assert.match(page, /requireAuctionAccess\("maintenance"\)/);
assert.match(page, /readDraftReportV2ReviewSnapshot/);
assert.match(page, /hydrateMethodDResults/);
assert.match(page, /frozenReview \?\? liveReview/);
assert.match(page, /initialFrozen=\{Boolean\(frozenReview\)\}/);
assert.doesNotMatch(client, /FREEZE V2 SNAPSHOT/);
assert.match(client, /DRAFT QUALITY — FORMULA C/);
assert.match(client, /50% Starting Lineup/);
assert.match(client, /35% Position Group/);
assert.match(client, /15% Useful Depth/);
assert.match(client, /10% QB/);
assert.match(client, /30% RB/);
assert.match(client, /40% WR/);
assert.match(client, /20% TE/);
assert.match(client, /FLEX/);
assert.match(client, /diagnostic only — no independent Draft Quality weight/);
assert.match(client, /Biggest Strength/);
assert.match(client, /Biggest Weakness/);
assert.match(client, /Drafted as:/);
assert.match(client, /PLAYER/);
assert.match(client, /FROZEN EVIDENCE/);
assert.match(client, /VIEW RAW DIAGNOSTIC/);
assert.doesNotMatch(client, /V2 REVIEW SNAPSHOT FROZEN/);
assert.match(client, /FROZEN SNAPSHOT EXISTS/);
assert.match(client, /initialFrozen/);
assert.match(client, /VIEW SNAPSHOT DETAILS/);
assert.doesNotMatch(client, /method: "POST"/);
assert.doesNotMatch(client, /commish\/draft-report-v2-/);
assert.equal((client.match(/method: "POST"/g) ?? []).length, 0);
assert.doesNotMatch(client, /#\$\{[^}]+\}\/#/);
assert.doesNotMatch(client, /calculateDraftQuality|calculateAuctionEfficiency|buildDraftReportV2Snapshot/);
assert.match(review, /DRAFT_COMPLETION_TIMESTAMP_NOT_PERSISTED/);
assert.match(client, /Score/);
assert.match(client, /Overall rank/);
assert.match(client, /DQ rank/);
assert.match(client, /AE rank/);
assert.match(client, /rank\(row\.draftQualityRank\)/);
assert.match(client, /rank\(formula\?\.draftQualityRank\)/);
assert.doesNotMatch(client, /rank\(quality\.draftQuality\.leagueRank\)/);
assert.match(client, /summaryLabel/);
assert.match(client, /table-fixed/);
assert.match(client, /finalGrades/);
assert.doesNotMatch(page, /freezeDraftReportV2ReviewSnapshot|method: "POST"/);
assert.match(persistence, /draft_report_v2_review_snapshots/);
assert.match(persistence, /existing\.exists/);
assert.match(persistence, /\.create\(snapshot\)/);
assert.match(persistence, /persistedBy/);
console.log("Draft Report Card V2 commissioner preview checks passed.");
