import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync("app/commish/post-draft/v2/owner-preview/page.tsx", "utf8");
const client = readFileSync("app/commish/post-draft/v2/owner-preview/OwnerPreviewClient.tsx", "utf8");
const presentation = readFileSync("lib/draftReportV2/ownerPresentation.ts", "utf8");
const v1 = readFileSync("app/league-info/draft-report/DraftReportCardView.tsx", "utf8");

assert.match(page, /requireAuctionAccess\("maintenance"\)/);
assert.match(page, /AuctionAccessError/);
assert.match(page, /hydrateMethodDResults/);
assert.match(page, /review\.finalGrades/);
assert.match(presentation, /review\.formulaC/);
assert.match(presentation, /review\.auctionEfficiency/);
assert.match(presentation, /review\.snapshot\.teams\.map/);
assert.match(page, /readDraftReportV2ReviewSnapshot/);
assert.match(page, /frozenReview \?\? liveReview/);
assert.doesNotMatch(page, /freezeDraftReportV2ReviewSnapshot|method: "POST"|set\(/);
assert.match(client, /2026 Draft Report Card/);
assert.match(client, /Biggest strength/);
assert.match(client, /Needs work/);
assert.match(client, /STARTING CORE/);
assert.match(client, /POSITION CONTRIBUTORS/);
assert.match(client, /USEFUL DEPTH/);
assert.match(client, /FLEX CONTEXT/);
assert.match(client, /Auction execution/);
assert.match(client, /Auction Efficiency shows/);
assert.match(client, /HOW YOUR GRADE WORKS/);
assert.match(client, /Draft Quality is 85%/);
assert.match(client, /Auction Efficiency is 15%/);
assert.match(client, /Trades, waivers, injuries/);
assert.match(client, /final\.grade/);
assert.match(client, /final\.methodDScore/);
assert.match(client, /final\.overallRank/);
assert.match(client, /formula\.draftQualityRank/);
assert.match(client, /auction\.auctionEfficiency\.leagueRank/);
assert.match(client, /quality\.components\.startingLineup\.leagueRank/);
assert.match(client, /quality\.components\.depth\.leagueRank/);
assert.match(client, /quality\.components\.(qbRoom|rbRoom|wrRoom|teRoom)/);
assert.match(client, /reports\.map/);
assert.match(client, /<select/);
assert.doesNotMatch(client, /snapshotId|inputChecksum|modelVersions|evidenceAsOf|VIEW RAW|JSON\.stringify|robust-z|percentile|Method D|current roster|Power Rankings/);
assert.doesNotMatch(client, /fetch\(|\/api\/|onSubmit/);
assert.notEqual(v1.length, 0);
assert.match(v1, /Draft Report Card/);
console.log("Draft Report Card V2 owner preview checks passed.");
