import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const route = readFileSync("app/api/commish/post-draft/v2/route.ts", "utf8");
const page = readFileSync("app/commish/post-draft/v2/page.tsx", "utf8");
const client = readFileSync("app/commish/post-draft/v2/V2PreviewClient.tsx", "utf8");
const persistence = readFileSync("lib/draftReportV2/persistence.ts", "utf8");
const review = readFileSync("lib/draftReportV2/review.ts", "utf8");
assert.match(route, /requireAuctionAccess\("maintenance"\)/);
assert.match(route, /freeze-v2-snapshot/);
assert.match(route, /GET/);
assert.match(page, /requireAuctionAccess\("maintenance"\)/);
assert.match(page, /readDraftReportV2ReviewSnapshot/);
assert.match(page, /frozenReview \?\? liveReview/);
assert.match(page, /initialFrozen=\{Boolean\(frozenReview\)\}/);
assert.match(client, /FREEZE V2 SNAPSHOT/);
assert.match(client, /DRAFT QUALITY — FORMULA C/);
assert.match(client, /50% Starting Lineup/);
assert.match(client, /35% Position Group/);
assert.match(client, /15% Useful Depth/);
assert.match(client, /10% QB/);
assert.match(client, /30% RB/);
assert.match(client, /40% WR/);
assert.match(client, /20% TE/);
assert.match(client, /FLEX/);
assert.match(client, /Diagnostic only — no independent Draft Quality weight/);
assert.match(client, /Current Team/);
assert.match(client, /Draft-Time Team/);
assert.match(client, /FLEX\*/);
assert.match(client, /PLAYER/);
assert.match(client, /FROZEN EVIDENCE/);
assert.match(client, /VIEW RAW DIAGNOSTIC/);
assert.match(client, /V2 REVIEW SNAPSHOT FROZEN/);
assert.match(client, /FROZEN SNAPSHOT EXISTS/);
assert.match(client, /initialFrozen/);
assert.match(client, /isFrozen \? /);
assert.match(client, /snapshotId=\$\{encodeURIComponent\(snapshotId\)\}/);
assert.match(client, /method: "POST"/);
assert.match(client, /method: "GET"/);
assert.match(client, /persistedResponse/);
assert.match(client, /setIsFreezing\(false\)/);
assert.match(client, /catch \(error\)/);
assert.doesNotMatch(client, /commish\/draft-report-v2-/);
assert.equal((client.match(/method: "POST"/g) ?? []).length, 1);
assert.doesNotMatch(client, /#\$\{[^}]+\}\/#/);
assert.doesNotMatch(client, /calculateDraftQuality|calculateAuctionEfficiency|buildDraftReportV2Snapshot/);
assert.match(review, /DRAFT_COMPLETION_TIMESTAMP_NOT_PERSISTED/);
assert.doesNotMatch(client, /letterGrade|letter-grade field/);
assert.doesNotMatch(page, /freezeDraftReportV2ReviewSnapshot|method: "POST"/);
assert.match(persistence, /draft_report_v2_review_snapshots/);
assert.match(persistence, /existing\.exists/);
assert.match(persistence, /\.create\(snapshot\)/);
assert.match(persistence, /persistedBy/);
console.log("Draft Report Card V2 commissioner preview checks passed.");
