import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const route = readFileSync("app/api/commish/post-draft/v2/route.ts", "utf8");
const page = readFileSync("app/commish/post-draft/v2/page.tsx", "utf8");
const client = readFileSync("app/commish/post-draft/v2/V2PreviewClient.tsx", "utf8");
const persistence = readFileSync("lib/draftReportV2/persistence.ts", "utf8");
const review = readFileSync("lib/draftReportV2/review.ts", "utf8");
assert.match(route, /requireAuctionAccess\("maintenance"\)/);
assert.match(route, /freeze-v2-snapshot/);
assert.match(route, /GET/);
assert.match(page, /requireAuctionAccess\("maintenance"\)/);
assert.match(page, /readDraftReportV2ReviewSnapshot/);
assert.match(page, /hydrateMethodDResults/);
assert.match(page, /frozenReview \?\? liveReview/);
assert.match(page, /initialFrozen=\{Boolean\(frozenReview\)\}/);
assert.doesNotMatch(client, /FREEZE V2 SNAPSHOT/);
assert.match(client, /2026 Draft Report Cards/);
assert.match(client, /River City FFL · Post-Draft Grades/);
assert.match(client, /HOW GRADES WORK/);
assert.match(client, /50% Starting Lineup/);
assert.match(client, /35% Position Group/);
assert.match(client, /15% Useful Depth/);
assert.match(client, /10% QB/);
assert.match(client, /30% RB/);
assert.match(client, /40% WR/);
assert.match(client, /20% TE/);
assert.match(client, /FLEX/);
assert.match(client, /FLEX is diagnostic only/);
assert.match(client, />Strength</);
assert.match(client, />Needs work</);
assert.match(client, /Drafted as:/);
assert.match(client, /Frozen evidence/i);
assert.match(client, /VIEW RAW DIAGNOSTIC/);
assert.doesNotMatch(client, /V2 REVIEW SNAPSHOT FROZEN/);
assert.match(client, /FROZEN SNAPSHOT EXISTS/);
assert.match(client, /initialFrozen/);
assert.match(client, /VIEW SNAPSHOT DETAILS/);
assert.doesNotMatch(client, /method: "POST"/);
assert.doesNotMatch(client, /commish\/draft-report-v2-/);
assert.equal((client.match(/method: "POST"/g) ?? []).length, 0);
assert.doesNotMatch(client, /#\$\{[^}]+\}\/#/);
assert.doesNotMatch(client, /calculateDraftQuality|calculateAuctionEfficiency|buildDraftReportV2Snapshot/);
assert.match(review, /DRAFT_COMPLETION_TIMESTAMP_NOT_PERSISTED/);
assert.match(client, /Score/);
assert.match(client, /OVERALL/);
assert.match(client, /DQ rank/);
assert.match(client, /AE rank/);
assert.match(client, /rank\(row\.draftQualityRank\)/);
assert.match(client, /rank\(formula\.draftQualityRank\)/);
assert.doesNotMatch(client, /rank\(quality\.draftQuality\.leagueRank\)/);
assert.match(client, /summaryLabel/);
assert.match(client, /review\.formulaC\.map/);
assert.match(client, /overviewRows\.map/);
assert.match(client, /TeamReport team=\{team\} formula=\{row\}.*final=\{final\}/);
assert.match(client, /final\.grade/);
assert.match(client, /final\.methodDScore\.toFixed/);
assert.match(client, /final\.overallRank/);
assert.doesNotMatch(client, /<table/);
assert.doesNotMatch(client, /md:contents/);
assert.match(client, /md:grid-cols-2/);
assert.match(client, /Frozen evidence/);
assert.match(client, /Starter role/);
assert.match(client, /Position room/);
assert.match(client, /Depth \/ FLEX/);
assert.match(client, /allPlayers\.map/);
assert.match(client, /<div className="min-w-0 flex-1"><h4 className="break-normal font-bold/);
assert.doesNotMatch(client, /<h4 className="[^\"]*break-words/);
assert.match(client, /xl:grid-cols-3/);
assert.match(client, /draft-report-disclosure/);
assert.match(client, /className="draft-report-disclosure group min-w-0 open:col-span-full"/);
assert.match(client, /data-report-card-summary/);
assert.match(client, /data-full-team-report/);
assert.match(readFileSync("app/globals.css", "utf8"), /\.draft-report-disclosure\[open\]/);
assert.match(readFileSync("app/globals.css", "utf8"), /details\.draft-report-disclosure\[open\]/);
assert.match(readFileSync("app/globals.css", "utf8"), /grid-column:\s*1\s*\/\s*-1/);
assert.match(client, /View report/);
assert.match(client, /Position report/);
assert.match(client, /finalGrades/);
assert.doesNotMatch(page, /freezeDraftReportV2ReviewSnapshot|method: "POST"/);
assert.match(persistence, /draft_report_v2_review_snapshots/);
assert.match(persistence, /existing\.exists/);
assert.match(persistence, /\.create\(snapshot\)/);
assert.match(persistence, /persistedBy/);
console.log("Draft Report Card V2 commissioner preview checks passed.");
