import assert from "node:assert/strict";
import { canonicalAuctionTeams } from "../lib/auction/canonicalTeamCatalog";
import { buildDraftReportV2Snapshot, snapshotChecksum } from "../lib/draftReportV2/snapshot";
import { calculateDraftQuality } from "../lib/draftReportV2/draftQuality";
import { calculateAuctionEfficiency } from "../lib/draftReportV2/auctionEfficiency";
import { DRAFT_QUALITY_WEIGHTS, POSITION_GROUP_WEIGHTS } from "../lib/draftReportV2/types";

const requirements = { rosterPositions: ["QB", "RB", "RB", "WR", "WR", "TE", "FLEX", "BN", "BN"], requiredStarterSlots: { QB: 1, RB: 2, WR: 2, TE: 1 }, flexSlots: 1, flexEligiblePositions: ["RB", "WR", "TE"], rosterSlotCapacity: 9, source: "Sleeper league.roster_positions" as const };
const rosters = canonicalAuctionTeams.map((team, index) => ({ rosterId: team.rosterId, ownerUserId: team.managerId, teamName: team.teamName, playerIds: [`qb-${index}`, `rb-${index}-1`, `rb-${index}-2`, `wr-${index}-1`, `wr-${index}-2`, `te-${index}`, `flex-${index}`, `bench-${index}`], starterIds: [], franchiseId: team.franchiseId, ownerIds: team.ownerIds }));
const positions = ["QB", "RB", "RB", "WR", "WR", "TE", "WR", "WR"];
const players = new Map(rosters.flatMap((roster, index) => roster.playerIds.map((playerId, playerIndex) => [playerId, { playerName: playerId, position: positions[playerIndex], nflTeam: "RC", publishedValue: 10 + (12 - index) * 5 - playerIndex, adp: playerIndex + 1 }] as const)));
const acquisitions = rosters.flatMap((roster) => roster.playerIds.map((playerId, playerIndex) => ({ playerId, playerName: playerId, position: positions[playerIndex], nflTeam: "RC", rosterId: roster.rosterId, purchasePrice: playerIndex + 1, isKeeper: playerIndex === 0, pickNumber: playerIndex + 1, keeperCost: playerIndex === 0 ? 1 : null, acquisitionClassification: playerIndex === 0 ? "KEEPER" as const : "AUCTION" as const })));
const input = { season: 2026, draftId: "draft-v2-test", draftStatus: "complete", generatedAt: "2026-09-01T00:00:00.000Z", rosters, acquisitions, players, rosterRequirements: requirements };
const options = { evidenceAsOf: "2026-09-01T00:00:00.000Z", evidenceSources: [{ source: "published-player-value", runId: "values-1", generatedAt: "2026-09-01T00:00:00.000Z" }] };
const snapshot = buildDraftReportV2Snapshot(input, options);
const repeated = buildDraftReportV2Snapshot(input, options);
assert.equal(snapshot.inputChecksum, repeated.inputChecksum);
assert.equal(snapshotChecksum(snapshot), snapshotChecksum(repeated));
const regenerated = buildDraftReportV2Snapshot({ ...input, generatedAt: "2026-09-03T00:00:00.000Z" }, options);
assert.equal(snapshot.inputChecksum, regenerated.inputChecksum);
assert.equal(snapshot.teams.length, 12);
assert.equal(snapshot.modelVersions.report, "draft-report-v2");
assert.deepEqual(DRAFT_QUALITY_WEIGHTS, { startingLineup: 0.5, positionGroup: 0.35, depth: 0.15 });
assert.deepEqual(POSITION_GROUP_WEIGHTS, { QB: 0.1, RB: 0.3, WR: 0.4, TE: 0.2 });
const renamed = buildDraftReportV2Snapshot(input, { ...options, currentDisplayNames: new Map(canonicalAuctionTeams.map((team) => [team.franchiseId, `Current ${team.franchiseId}`])) });
assert.equal(snapshot.inputChecksum, renamed.inputChecksum);
const quality = calculateDraftQuality(snapshot);
assert.equal(quality.teams.length, 12);
for (const team of quality.teams) {
  const ids = team.startingLineup.flatMap((slot) => slot.playerId ? [slot.playerId] : []);
  assert.equal(new Set(ids).size, ids.length);
  assert(team.draftQuality.score !== null);
}
assert.equal(new Set(quality.teams.map((team) => team.draftQuality.leagueRank)).size, 12);
const efficiency = calculateAuctionEfficiency(snapshot);
assert.equal(efficiency.teams.length, 12);
assert.equal(efficiency.teams.every((team) => team.auctionEfficiency.leagueRank !== null), true);
const renamedQuality = calculateDraftQuality(renamed);
const renamedEfficiency = calculateAuctionEfficiency(renamed);
const scoringView = (report: typeof quality) => report.teams.map((team) => ({ franchiseId: team.franchiseId, draftQuality: team.draftQuality, components: team.components, startingLineup: team.startingLineup, biggestStrength: team.biggestStrength, biggestWeakness: team.biggestWeakness }));
assert.deepEqual(scoringView(quality), scoringView(renamedQuality));
assert.deepEqual(efficiency.teams.map(({ teamName: _teamName, ...team }) => team), renamedEfficiency.teams.map(({ teamName: _teamName, ...team }) => team));
const changedPriceInput = { ...input, acquisitions: acquisitions.map((row) => ({ ...row, purchasePrice: (row.purchasePrice ?? 0) + 100 })) };
const changedPriceSnapshot = buildDraftReportV2Snapshot(changedPriceInput, options);
assert.deepEqual(quality.teams.map((team) => team.draftQuality.score), calculateDraftQuality(changedPriceSnapshot).teams.map((team) => team.draftQuality.score));
assert.notDeepEqual(efficiency.teams.map((team) => team.referenceSurplus), calculateAuctionEfficiency(changedPriceSnapshot).teams.map((team) => team.referenceSurplus));
assert.throws(() => buildDraftReportV2Snapshot(input, { ...options, evidenceAsOf: "" }));
assert.throws(() => buildDraftReportV2Snapshot(input, { ...options, evidenceSources: [] }));
const changedEvidenceSnapshot = buildDraftReportV2Snapshot(input, { ...options, evidenceAsOf: "2026-09-02T00:00:00.000Z" });
assert.notEqual(snapshot.inputChecksum, changedEvidenceSnapshot.inputChecksum);
const changedSourcePlayer = new Map(players);
changedSourcePlayer.set("qb-0", { ...players.get("qb-0")!, publishedValue: 999 });
assert.equal(snapshot.players.find((player) => player.playerId === "qb-0")?.evidence.publishedValue, players.get("qb-0")?.publishedValue);
assert.notEqual(changedSourcePlayer.get("qb-0")?.publishedValue, snapshot.players.find((player) => player.playerId === "qb-0")?.evidence.publishedValue);
const missingInput = { ...input, players: new Map([...players].map(([id, player]) => [id, id === "te-0" ? { ...player, publishedValue: null } : player])) };
const missingSnapshot = buildDraftReportV2Snapshot(missingInput, options);
assert.equal(missingSnapshot.players.find((player) => player.playerId === "te-0")?.evidence.qualityScore, null);
console.log("Draft Report Card V2 shadow engine checks passed.");
