import assert from 'node:assert/strict';
import fs from 'node:fs';

const page = fs.readFileSync('app/history/page.tsx', 'utf8');
const explorer = fs.readFileSync('app/history/HallOfFameResumeExplorer.tsx', 'utf8');
const trophyRoom = fs.readFileSync('app/history/TrophyRoomExplorer.tsx', 'utf8');

assert.match(page, /<SiteShell activePath="\/league-info">/);
assert.match(page, /River City History/);
assert.match(page, /A league built over time/);
assert.match(page, /searchParams/);
assert.match(page, /normalizeHistoryView/);
for (const view of ['overview', 'champions', 'hall-of-fame', 'trophy-room']) assert.match(page, new RegExp(`"${view}"`));
for (const label of ['OVERVIEW', 'CHAMPIONS', 'HALL OF FAME', 'TROPHY ROOM']) assert.match(page, new RegExp(label));
assert.match(page, /aria-label="History sections"/);
assert.match(page, /aria-current=\{activeView === value \? "page"/);
assert.match(page, /value === "overview" \? "\/history"/);
assert.match(page, /`\/history\?view=\$\{value\}`/);
assert.doesNotMatch(page, /\/history\/(champions|hall-of-fame|trophy-room)/);
assert.match(page, /: "overview"/);

const overviewStart = page.indexOf('activeView === "overview"');
const championsStart = page.indexOf('activeView === "champions"');
const hallStart = page.indexOf('activeView === "hall-of-fame"');
const trophyStart = page.indexOf('activeView === "trophy-room"');
assert.ok(overviewStart >= 0 && championsStart > overviewStart && hallStart > championsStart && trophyStart > hallStart);
const overview = page.slice(page.indexOf('function Overview'), championsStart);
const champions = page.slice(championsStart, hallStart);
const hall = page.slice(hallStart, trophyStart);
const trophy = page.slice(trophyStart);
for (const marker of ['League at a glance', 'Recent champions', 'League eras', 'Historical data coverage', 'Explore more history']) assert.match(overview, new RegExp(marker));
assert.match(overview, /getHistoricalPostseasonEra\(2011\)/);
assert.match(overview, /getHistoricalPostseasonEra\(2022\)/);
assert.match(overview, /getHistoryMatchupCoverageNote\(\)/);
assert.match(overview, /CO-CHAMPIONS/);
assert.match(champions, /ChampionsClub/);
assert.doesNotMatch(champions, /HallOfFameResumeExplorer|TrophyRoomExplorer/);
assert.match(hall, /HallOfFameResumeExplorer/);
assert.doesNotMatch(hall, /ChampionsClub|TrophyRoomExplorer/);
assert.match(trophy, /TrophyRoomExplorer/);
assert.doesNotMatch(page, /Explore the Trophy Room|Visit the Trophy Room/);
assert.match(trophyRoom, /River City Trophy Room/);
assert.match(trophyRoom, /role="tablist"/);
for (const tab of ['CHAMPIONS', 'Podiums', 'Shame']) assert.match(trophyRoom, new RegExp(tab));
assert.match(trophyRoom, /getCanonicalChampionshipResults\(\)/);
assert.match(trophyRoom, /getCanonicalHallOfFameResumes\(\)/);
assert.match(trophyRoom, /finalPlacement === result\.teamCount/);
assert.match(trophyRoom, /second\.year - first\.year/);
assert.match(trophyRoom, /focus-visible:ring/);
assert.match(page, /getCanonicalChampionNames\(\)/);
assert.match(page, /getCanonicalChampionshipResults\(\)/);
assert.match(page, /getCanonicalHallOfFameResumes\(\)/);
assert.match(page, /getCompletedHistoryResults\(\)/);
assert.match(explorer, /Hall of Fame/);
assert.match(explorer, /All-Time Résumés/);
assert.match(explorer, /md:hidden/);
assert.doesNotMatch(page, /Damar Hamlin|Contextual preview|canonical authority|reviewed standings source above/);
for (const href of ['/league-info/rivalries', '/league-info/draft', '/league-info/legislative', '/league-info/payouts', '/history/version-history']) assert.match(page, new RegExp(href.replaceAll('/', '\\/')));
assert.match(page, /Return to Home/);
assert.match(page, /focus-visible:ring/);
assert.doesNotMatch(page, /role="tablist"/);

console.log('History presentation test passed');
