import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync("app/HomeClient.tsx", "utf8");
const accountMenu = readFileSync("components/MemberAccountMenu.tsx", "utf8");
const wrapper = readFileSync("app/page.tsx", "utf8");
const publicFinanceRoute = readFileSync("app/api/public-finance/summary/route.ts", "utf8");

assert.match(page, /2026 Power Rankings/);
assert.doesNotMatch(page, /Championship Odds/);
assert.match(page, /Power rankings reflect roster strength and schedule factors/);
assert.match(page, /href="\/predictor"/);
assert.match(page, /Open 2026 Matchups/);
assert.match(page, /href="\/matchups"/);
assert.doesNotMatch(page, /\$219/);
assert.doesNotMatch(page, /Upcoming Schedule/);
assert.match(page, /2026 Payouts/);
assert.match(page, /href="\/league-info\/payouts"/);
assert.match(page, /break-words text-\[9px\] font-black uppercase leading-4 tracking-widest/);
assert.doesNotMatch(page, /truncate text-\[9px\] font-black uppercase tracking-widest/);
assert.match(page, /fetch\("\/api\/public-finance\/summary"\)/);
assert.match(publicFinanceRoute, /loadPublicOperationalFinancePresentation/);
assert.doesNotMatch(publicFinanceRoute, /amountOwedCents|paymentHandle|paymentTimestamp|commissionerNote|idempotencyKey|externalReference|duesRows/);
assert.doesNotMatch(page, /calculateChampionPayout|duesAssessedCents|duesCollectedCents|projectedChampionCashCents/);
assert.doesNotMatch(page, /amountOwedCents|paymentHandle|paymentTimestamp|venmo|commissionerNote|idempotencyKey|externalReference/);
assert.match(page, /aria-label="Close league history"/);
assert.match(page, /aria-label="Close commissioner briefing"/);
assert.match(page, /role="dialog" aria-modal="true"/);
assert.match(page, /Commissioner Corner/);
assert.doesNotMatch(page, /2026 public draft status/);
assert.match(page, /2026 virtual draft/);
assert.match(page, /Virtual Draft HQ/);
assert.doesNotMatch(page, /Aug 22|Keepers lock by|authorized-only|available to all managers/i);
assert.match(page, /Keepers remain editable until the draft begins/);
assert.match(page, /Join Google Meet/);
assert.match(page, /href="https:\/\/meet\.google\.com\/hqg-cafx-mcs"/);
assert.match(page, /OPEN YOUR WAR ROOM|Open Your War Room/);
assert.match(page, /href="\/commish\/auction"/);
assert.doesNotMatch(page, /warRoomId|canonicalOwnerId|authorized_owner_emails/);
assert.match(page, /fetch\("\/api\/rsvps"/);
assert.match(page, /Reigning Champion/);
assert.match(page, /Latest Commissioner Briefing/);
assert.doesNotMatch(page, /Quick Links/);

assert.match(page, /aria-label="Home dashboard"/);
assert.match(wrapper, /getCurrentMember/);
assert.match(page, /League Member Login/);
assert.match(page, /href="\/member\/login\?returnTo=%2F"/);
assert.match(page, /MemberAccountMenu/);
assert.match(accountMenu, /My War Room/);
assert.match(page, /initialMember\.canAccessMaintenance/);
assert.doesNotMatch(page, /email|firebaseUid|canonicalOwnerId|warRoomId|rosterId|idToken/i);
assert.match(page, /lg:grid-cols-12/);
assert.match(page, /md:col-span-1 lg:col-span-4/);
assert.match(page, /md:grid-cols-2/);
assert.match(page, /className="contents" aria-label="Primary season status"/);
assert.match(page, /className="contents" aria-label="League activity and finance"/);
assert.match(page, /className="contents" aria-label="League history and recent recap"/);
assert.doesNotMatch(page, /lg:grid-cols-4|lg:grid-cols-3|lg:grid-cols-\[minmax\(0,2fr\)/);
assert.doesNotMatch(page, /(?:min-|max-)?h-\[\d+px\]/);
assert.match(page, /overflow-x-auto/);
assert.doesNotMatch(page, /overflow-x-scroll/);

console.log("Home-page fixture checks passed.");
