import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolveWeeklyFinality } from "../lib/home/weeklyFinality";
import { selectWeeklyHighScore, type WeeklyHighScoreCandidate } from "../lib/home/weeklyHighScore";
import { getWeeklySpotlightLabel } from "../lib/home/weeklySpotlight";

const completeWeek = (week: number, scoredMatchupCount = 12) => ({ week, matchupCount: 12, scoredMatchupCount });
assert.equal(resolveWeeklyFinality(1, [completeWeek(1)]).finalizedWeek, null);
assert.deepEqual(resolveWeeklyFinality(2, [completeWeek(1)]).finalizedWeeks, []);
assert.deepEqual(resolveWeeklyFinality(3, [completeWeek(1), completeWeek(2)]).finalizedWeeks, [1]);
assert.deepEqual(resolveWeeklyFinality(5, [completeWeek(1), completeWeek(2), completeWeek(3), completeWeek(4)]).finalizedWeeks, [1, 2, 3]);
assert.deepEqual(resolveWeeklyFinality(5, [completeWeek(3, 11)]).finalizedWeeks, []);
assert.equal(resolveWeeklyFinality(5, [completeWeek(1)]).statCorrectionBufferWeeks, 1);

const candidate = (franchiseId: string, points: number): WeeklyHighScoreCandidate => ({ franchiseId, teamName: franchiseId, ownerNames: [franchiseId], ownerPhoto: null, sleeperAvatar: null, points, week: 1 });
assert.deepEqual(selectWeeklyHighScore([candidate("b", 148.62), candidate("a", 148.62), candidate("c", 100)]).map((winner) => winner.franchiseId), ["a", "b"]);
assert.deepEqual(selectWeeklyHighScore([candidate("a", 148.62), candidate("b", 100)]).map((winner) => winner.franchiseId), ["a"]);
assert.equal(getWeeklySpotlightLabel("WEEK_ACTIVE", false), "2026 WEEKLY SPOTLIGHT");
assert.equal(getWeeklySpotlightLabel("WEEK_ACTIVE", true), "WEEKLY HIGH SCORE");
assert.equal(getWeeklySpotlightLabel("PLAYOFFS", true), "PLAYOFF SPOTLIGHT");
assert.equal(getWeeklySpotlightLabel("CHAMPIONSHIP_WEEK", true), "CHAMPIONSHIP SPOTLIGHT");

const home = readFileSync("app/HomeClient.tsx", "utf8");
const page = readFileSync("app/page.tsx", "utf8");
const loader = readFileSync("lib/home/liveSeasonState.ts", "utf8");
const spotlight = readFileSync("lib/home/weeklySpotlight.ts", "utf8");
assert.match(home, /href="\/league-info\/draft-report\/overview"/);
assert.match(home, /isDraftPhase && <Link href="\/commish\/auction"/);
assert.match(home, /NFL WEEK \{nflGameCenter\.week\} SCORES/);
assert.match(home, /href=\{`\/nfl\/week\/\$\{nflGameCenter\.week\}`\}/);
assert.doesNotMatch(home, /View Week \{liveSeasonState\.activeWeek\} Matchups/);
assert.match(home, /showDraftRecap = boxOneState\.state === "POST_DRAFT_PRESEASON"/);
assert.doesNotMatch(home, /showDraftRecap = liveSeasonState\.finality\.finalizedWeek === null/);
assert.match(home, /weeklyHighScore\.length > 0/);
assert.match(home, /getWeeklySpotlightLabel/);
assert.match(home, /\$10 WEEKLY WINNER/);
assert.match(home, /weeklyHighScorePrizeCents !== null/);
assert.match(loader, /weeklyHighScorePrizeCents: settlement\.prizePerWinner/);
assert.match(loader, /weeklyHighScorePrizeCents: null/);
assert.match(spotlight, /"WEEKLY HIGH SCORE"/);
assert.match(spotlight, /"2026 WEEKLY SPOTLIGHT"/);
assert.match(spotlight, /"PLAYOFF SPOTLIGHT"/);
assert.match(spotlight, /"CHAMPIONSHIP SPOTLIGHT"/);
assert.match(home, /matchups\?week=/);
assert.match(home, /publicFinance\.owedCount/);
assert.doesNotMatch(home, /publicFinance\.notPaidCount/);
assert.match(home, /Current roster-strength ranking\./);
assert.match(home, /preseason-strength-v1 model on current rosters/);
assert.match(home, /href="\/league-info\/payouts"/);
assert.match(home, /href="\/league-info\/legislative"/);
assert.match(home, /href="\/predictor"/);
assert.match(home, /href="\/power-rankings"/);
for (const role of ["NFL Game Center", "Reigning Champion", "2026 Power Rankings", "2026 Matchups", "Predictor", "Legislative Hub", "2026 Payouts", "Recent Recap"]) assert.match(home, new RegExp(`label=\"${role}\"`));
assert.match(home, /if \(label === "League History"\) return null/);
assert.match(home, /Projected Standings/);
assert.match(home, /Playoff Odds/);
assert.match(home, /Championship Odds/);
assert.match(home, /Player Samples/);
assert.match(home, /Team Samples/);
assert.match(home, /Eligible Weeks/);
assert.match(home, /predictorProgress\?\.nextEvent/);
assert.doesNotMatch(home, /Projected Finish.*\d+%|Playoff Odds.*\d+%|Championship Odds.*\d+%/);
const orderLabels = ["NFL Game Center", "Reigning Champion", "2026 Power Rankings", "2026 Matchups", "Predictor", "Legislative Hub", "2026 Payouts", "Recent Recap"];
let previousOrder = 0;
for (const label of orderLabels) {
  const match = home.match(new RegExp(`(?:\\\"${label}\\\"|${label}): \\\"lg:order-(\\d+)\\\"`));
  assert.ok(match, `missing desktop order for ${label}`);
  const order = Number(match?.[1]);
  assert.ok(order > previousOrder, `${label} is out of order`);
  previousOrder = order;
}
assert.match(page, /getHomeLiveSeasonState/);
assert.match(loader, /resolveWeeklyFinality/);
assert.match(loader, /getMatchups\(week\)/);
assert.match(loader, /selectWeeklyHighScore/);
console.log("Home live-season checks passed.");
