import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const page = readFileSync("app/predictor/page.tsx", "utf8");
const contract = readFileSync("lib/predictor/predictorContract.ts", "utf8");
const siteShell = readFileSync("components/SiteShell.tsx", "utf8");
const home = readFileSync("app/HomeClient.tsx", "utf8");

assert.match(page, /<SiteShell activePath="\/predictor">/);
assert.match(page, /getCanonicalPowerRankings/);
assert.match(page, /RIVER CITY PREDICTOR/);
assert.match(page, /WHAT ARE MY CHANCES\?/);
assert.match(page, /See where every team stands today/);
assert.match(page, /SIMULATOR CALIBRATING/);
assert.match(page, /getCurrentMember/);
assert.match(page, /Your Predictor Snapshot/);
assert.match(page, /League-wide Predictor outlook/);
assert.match(page, /href="\/power-rankings"/);
assert.match(page, /Projected Finish/);
assert.match(page, /Playoff Odds/);
assert.match(page, /Championship Odds/);
assert.match(page, /How Predictor Works/);
assert.match(page, /Calibration Status/);
assert.match(page, /real 2026 results/);
assert.match(page, /max-w-\[1600px\]/);
assert.match(page, /team\.leagueRelativeRank/);
assert.match(page, /team\.teamName/);
assert.doesNotMatch(page, /team\.components|team\.biggestStrength|team\.biggestWeakness|team\.tier|team\.confidence/);
assert.doesNotMatch(page, /Detailed current Power Rankings|Supporting Power Rankings|Current team strength/);
assert.match(page, /calibratingOutcome/);
assert.match(contract, /projectedWins: number \| null/);
assert.match(contract, /projectedLosses: number \| null/);
assert.match(contract, /projectedFinish: number \| null/);
assert.match(contract, /playoffProbability: number \| null/);
assert.match(contract, /championshipProbability: number \| null/);
assert.match(contract, /likelySeed: number \| null/);
assert.doesNotMatch(page, /(?:\d+%|toFixed\(1\))/);
assert.match(page, /report\.teams\.map/);
assert.match(page, /focus-visible:ring-2/);
assert.doesNotMatch(page, /<nav/);
assert.doesNotMatch(page, /AI Championship Predictor|Intelligence Dispatch/);
assert.equal(existsSync("components/PowerRankings.tsx"), false);
assert.match(siteShell, /MOBILE_SITE_NAV_ITEMS/);
const navigation = readFileSync("lib/navigation/siteNavigation.ts", "utf8");
assert.match(navigation, /\{ label: "Predictions", href: "\/predictor", match: "exact" \}/);
assert.match(home, /href="\/predictor"/);

console.log("Predictor presentation checks passed.");
