import assert from "node:assert/strict";
import { evaluateShadowRecommendation, reasonPolarity, validateLeagueTradeOwnership, type ExpertRosEvidence, type KeeperEvidence, type TradeMarketEvidence } from "../lib/tradeComparison/recommendationEngine";
import { buildLineupImpact } from "../lib/tradeComparison/lineupImpact";
import type { CurrentSeasonPlayerValue } from "../lib/tradeComparison/currentValue";
import type { TradeComparisonPlayer } from "../lib/tradeComparison/types";

const player = (playerId: string, name: string, position: "QB" | "RB" | "WR" | "TE"): TradeComparisonPlayer => ({ playerId, name, position, nflTeam: "RIV" });
const value = (p: TradeComparisonPlayer, rank: number, market: number): CurrentSeasonPlayerValue => ({ playerId: p.playerId, playerName: p.name ?? p.playerId, position: p.position!, nflTeam: p.nflTeam, overallRank: rank, positionalRank: null, currentValueScore: market, mode: "REDRAFT", generatedAt: "2026-08-31T00:00:00.000Z", ageDays: 0, freshness: "FRESH", confidence: "MEDIUM", sourceCount: 1, sources: [{ source: "FantasyCalc", rank, value: market }], safeAsPrimaryCurrentValue: true, contextOnly: false });
const ros = (p: TradeComparisonPlayer, rank: number, sourceCount = 2): ExpertRosEvidence => ({ playerId: p.playerId, playerName: p.name!, consensusOverallRank: rank, consensusPositionalRank: null, sourceCount, freshness: "FRESH", confidence: sourceCount >= 3 ? "HIGH" : "MEDIUM", sourceRanks: [] });
const market = (p: TradeComparisonPlayer, rank: number, v: number): TradeMarketEvidence => ({ playerId: p.playerId, fantasyCalcValue: v, overallRank: rank, positionalRank: null, trend30Day: 0, generatedAt: "2026-08-31T00:00:00.000Z", freshness: "FRESH" });
const keeper = (p: TradeComparisonPlayer, cost: number): KeeperEvidence => ({ playerId: p.playerId, playerName: p.name!, projectedCost: cost, confidence: "HIGH" });
const qbLow = player("qb-low", "QB Low", "QB"); const qbHigh = player("qb-high", "QB High", "QB"); const wr = player("wr", "WR", "WR");
const common = { franchiseId: "team", franchiseName: "Team", rosterBefore: [qbLow, wr], outgoing: [qbLow], incoming: [qbHigh], currentValues: new Map([ [qbLow.playerId, value(qbLow, 100, 10)], [qbHigh.playerId, value(qbHigh, 10, 20)], [wr.playerId, value(wr, 20, 15)] ]), expertRos: new Map([[qbLow.playerId, ros(qbLow, 100)], [qbHigh.playerId, ros(qbHigh, 10)]]), tradeMarket: new Map([[qbLow.playerId, market(qbLow, 100, 10)], [qbHigh.playerId, market(qbHigh, 10, 20)]]), keeper: new Map([[qbLow.playerId, keeper(qbLow, 20)], [qbHigh.playerId, keeper(qbHigh, 20)]]), starterSlots: ["QB", "WR"] };
const upgrade = evaluateShadowRecommendation(common);
assert.equal(upgrade.recommendation, "ACCEPT");
assert.equal(reasonPolarity("MARKET_VALUE_GAIN"), "POSITIVE");
assert.equal(upgrade.whyILikeIt.includes("Incoming package carries more FantasyCalc redraft market value."), true);
assert.equal(upgrade.whatGivesMePause.includes("Incoming package carries more FantasyCalc redraft market value."), false);
const reverse = evaluateShadowRecommendation({ ...common, rosterBefore: [qbHigh, wr], outgoing: [qbHigh], incoming: [qbLow] });
assert.equal(reverse.recommendation, "DECLINE");
assert.equal(reasonPolarity("MARKET_VALUE_LOSS"), "NEGATIVE");
assert.equal(reverse.whatGivesMePause.includes("Incoming package carries less FantasyCalc redraft market value."), true);
assert.equal(reasonPolarity("STARTING_LINEUP_IMPROVES"), "POSITIVE");
assert.equal(reasonPolarity("STARTING_LINEUP_DECLINES"), "NEGATIVE");
assert.equal(reasonPolarity("FILLS_POSITIONAL_NEED"), "POSITIVE");
assert.equal(reasonPolarity("CREATES_POSITIONAL_HOLE"), "NEGATIVE");
assert.equal(reasonPolarity("KEEPER_VALUE_GAIN"), "POSITIVE");
assert.equal(reasonPolarity("KEEPER_VALUE_LOSS"), "NEGATIVE");
assert.equal(reasonPolarity("FAIRNESS_SUPPORTS"), "NEUTRAL");
assert.equal(reasonPolarity("INCOMPLETE_KEEPER_DATA"), "NEUTRAL");
assert.equal(reverse.primaryReasons.some((item) => item.includes("declines on ordinal")), false);
assert.equal(reverse.whatGivesMePause.some((item) => item.includes("declines on ordinal")), true);
assert.equal(upgrade.whyILikeIt.some((item) => reverse.whatGivesMePause.includes(item)), false);
const neutral = evaluateShadowRecommendation({ ...common, outgoing: [qbLow], incoming: [qbLow] });
assert.equal(neutral.recommendation, "HOLD");
const fairnessConflict = evaluateShadowRecommendation({ ...common, fairness: { available: true, score: 90, verdict: "FAIR", leadingSide: "B" } });
assert.equal(fairnessConflict.recommendation, "ACCEPT");
assert.equal(fairnessConflict.fairness.relationshipToRecommendation, "CONFLICTS");
const missingFp = evaluateShadowRecommendation({ ...common, expertRos: new Map([[qbLow.playerId, ros(qbLow, 100)], [qbHigh.playerId, ros(qbHigh, 10)]]) });
assert.notEqual(missingFp.recommendation, "INSUFFICIENT_DATA");
const noMarket = evaluateShadowRecommendation({ ...common, tradeMarket: new Map() });
assert.notEqual(noMarket.confidence, "HIGH");
assert.equal(noMarket.reasonCodes.includes("INCOMPLETE_KEEPER_DATA"), false);
const marketOnly = evaluateShadowRecommendation({ ...common, expertRos: new Map() });
assert.equal(marketOnly.recommendation, "INSUFFICIENT_DATA");
assert.equal(marketOnly.confidence, "INSUFFICIENT");
const fairnessLikesDecline = evaluateShadowRecommendation({ ...common, rosterBefore: [qbHigh, wr], outgoing: [qbHigh], incoming: [qbLow], fairness: { available: true, score: 95, verdict: "FAIR", leadingSide: "A" } });
assert.equal(fairnessLikesDecline.recommendation, "DECLINE");
const keeperCannotOverride = evaluateShadowRecommendation({ ...common, rosterBefore: [qbHigh, wr], outgoing: [qbHigh], incoming: [qbLow], keeper: new Map([[qbHigh.playerId, keeper(qbHigh, 100)], [qbLow.playerId, keeper(qbLow, 1)]]) });
assert.equal(keeperCannotOverride.recommendation, "LEAN_DECLINE");
assert.equal(new Set(["ACCEPT", "LEAN_ACCEPT", "HOLD", "LEAN_DECLINE", "DECLINE", "INSUFFICIENT_DATA"]).has(upgrade.recommendation), true);
assert.deepEqual(validateLeagueTradeOwnership({ sendingFranchiseId: "a", receivingFranchiseId: "b", outgoing: [qbLow], incoming: [qbHigh], currentRosters: new Map([["a", [qbLow]], ["b", [qbHigh]]]) }).status, "VALID");
assert.equal(validateLeagueTradeOwnership({ sendingFranchiseId: "a", receivingFranchiseId: "b", outgoing: [qbHigh], incoming: [qbLow], currentRosters: new Map([["a", [qbLow]], ["b", [qbHigh]]]) }).status, "INVALID_OWNERSHIP");
assert.equal(validateLeagueTradeOwnership({ sendingFranchiseId: "a", receivingFranchiseId: "b", outgoing: [qbLow], incoming: [wr], currentRosters: new Map([["a", [qbLow]], ["b", [qbHigh]], ["c", [wr]]]) }).status, "MULTIPLE_COUNTERPARTIES");
const distinct = evaluateShadowRecommendation({ ...common, rosterBefore: [qbLow, wr], outgoing: [wr], incoming: [qbHigh] });
assert.equal(distinct.transactionChanges.find((change) => change.playerId === wr.playerId)?.direction, "OUTGOING");
assert.equal(distinct.starterChanges.length, 2);
assert.equal(distinct.transactionChanges.some((change) => change.playerId === qbHigh.playerId && change.isStarterAfter), true);
const missingSupport = evaluateShadowRecommendation({ ...common, tradeMarket: new Map(), fairness: null, keeper: new Map() });
assert.equal(missingSupport.reasonCodes.includes("MARKET_VALUE_LOSS"), false);
assert.equal(missingSupport.reasonCodes.includes("FAIRNESS_CONFLICTS"), false);
assert.equal(missingSupport.keeperImpact.assessment, "UNKNOWN");
const benchIncoming = evaluateShadowRecommendation({ ...common, rosterBefore: [qbHigh, qbLow, wr], outgoing: [qbLow], incoming: [qbLow] });
assert.equal(benchIncoming.lineupImpact.before.slots[0]?.playerId, qbHigh.playerId);
assert.equal(benchIncoming.lineupImpact.after.slots[0]?.playerId, qbHigh.playerId);
assert.equal(benchIncoming.transactionChanges.find((change) => change.playerId === qbLow.playerId)?.wasStarterBefore, false);
const skillOnly = evaluateShadowRecommendation({ ...common, starterSlots: ["QB", "WR", "K", "DEF"], rosterBefore: [qbLow, wr], outgoing: [], incoming: [] });
assert.equal(skillOnly.lineupImpact.coreCompleteness, "CORE_COMPLETE");
assert.equal(skillOnly.lineupImpact.fullCompleteness, "FULL_PARTIAL");
assert.notEqual(skillOnly.lineupImpact.status, "UNAVAILABLE");
const slotMoved = evaluateShadowRecommendation({ ...common, starterSlots: ["WR", "FLEX"], rosterBefore: [wr, { ...qbHigh, playerId: "wr2", name: "WR Two", position: "WR" }], outgoing: [], incoming: [] });
assert.equal(slotMoved.lineupImpact.startingUnitAdded.length, 0);
assert.equal(slotMoved.lineupImpact.startingUnitRemoved.length, 0);
assert.equal(slotMoved.lineupImpact.direction, "NEUTRAL");
assert.equal(slotMoved.reasonCodes.includes("STARTER_EVIDENCE_CONFLICT"), false);
const wr2 = { ...qbHigh, playerId: "wr2", name: "WR Two", position: "WR" as const };
const reshuffle = buildLineupImpact({ beforePlayers: [wr, wr2], afterPlayers: [wr, wr2, { ...wr2, playerId: "wr3", name: "WR Three" }], currentValues: new Map([[wr.playerId, value(wr, 20, 20)], [wr2.playerId, value(wr2, 30, 10)], ["wr3", value({ ...wr2, playerId: "wr3", name: "WR Three" }, 10, 30)]]), starterSlots: ["WR", "FLEX"] });
assert.deepEqual(reshuffle.startingUnitAdded.map((player) => player.playerId), ["wr3"]);
assert.deepEqual(reshuffle.startingUnitRemoved.map((player) => player.playerId), ["wr2"]);
assert.equal(Array.isArray(reshuffle.slotOnlyMoves), true);
const unknownLineup = buildLineupImpact({ beforePlayers: [{ ...wr, playerId: "unknown", name: "Unknown WR" }], afterPlayers: [{ ...wr, playerId: "unknown", name: "Unknown WR" }], currentValues: new Map(), starterSlots: ["WR"] });
assert.equal(unknownLineup.before.slots[0]?.selectionEvidence, "UNKNOWN");
assert.equal(unknownLineup.before.slots[0]?.value, null);
const missingPositive = evaluateShadowRecommendation({ ...common, incoming: [{ ...qbHigh, playerId: "qb-unknown", name: "QB Unknown" }], expertRos: new Map([[qbLow.playerId, ros(qbLow, 100)], ["qb-unknown", ros({ ...qbHigh, playerId: "qb-unknown", name: "QB Unknown" }, 10)]]), tradeMarket: new Map([[qbLow.playerId, market(qbLow, 100, 10)]]), keeper: new Map([[qbLow.playerId, keeper(qbLow, 20)]]) });
assert.equal(missingPositive.recommendation, "LEAN_ACCEPT");
assert.equal(missingPositive.confidence, "LOW");
const depthGain = evaluateShadowRecommendation({ ...common, starterSlots: ["QB"], rosterBefore: [qbLow], outgoing: [], incoming: [wr], tradeMarket: new Map([[qbLow.playerId, market(qbLow, 100, 10)], [wr.playerId, market(wr, 20, 20)]]), expertRos: new Map([[qbLow.playerId, ros(qbLow, 100)], [wr.playerId, ros(wr, 20)]]), keeper: new Map([[qbLow.playerId, keeper(qbLow, 20)], [wr.playerId, keeper(wr, 20)]]) });
assert.equal(depthGain.recommendation, "ACCEPT");
assert.equal(depthGain.reasonCodes.includes("DEPTH_IMPROVES"), true);
assert.equal(validateLeagueTradeOwnership({ sendingFranchiseId: "a", receivingFranchiseId: "b", outgoing: [qbLow], incoming: [{ ...qbHigh, playerId: "not-rostered" }], currentRosters: new Map([["a", [qbLow]], ["b", [qbHigh]]]) }).status, "UNKNOWN_PLAYER");
const seasonModes = (["PRESEASON", "EARLY_SEASON", "MID_SEASON", "LATE_SEASON"] as const).map((seasonMode) => evaluateShadowRecommendation({ ...common, seasonMode, preseasonContext: { auctionConsensus: 99999, adp: 1 } }));
assert.deepEqual(seasonModes.map((result) => result.preseasonContext.relevance), ["MEANINGFUL_SUPPORT", "TIEBREAKER_ONLY", "HISTORICAL_CONTEXT", "DISPLAY_ONLY"]);
assert.equal(seasonModes.every((result) => result.recommendation === "ACCEPT"), true);
assert.match(upgrade.bottomLine, /accept/i);
assert.match(marketOnly.bottomLine, /not enough primary current-season evidence/i);
assert.match(neutral.bottomLine, /neutral result/i);
console.log("Recommendation engine tests passed.");
