import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync("lib/tradeComparison/serverRecommendationAdapter.ts", "utf8");
const serverContext = readFileSync("lib/tradeComparison/serverAdapter.ts", "utf8");
const multiTeam = readFileSync("lib/tradeComparison/multiTeamFoundation.ts", "utf8");
const diagnosticRoute = readFileSync("app/api/commish/trade-recommendation-diagnostic/route.ts", "utf8");

assert.match(source, /import "server-only"/);
assert.match(source, /loadTradeComparisonContext\(\{ includeAcquisitionSnapshot: true \}\)/);
assert.match(source, /request\.mode !== "LEAGUE_TRADE"/);
assert.match(source, /SANDBOX_RECOMMENDATION_DISABLED/);
assert.match(source, /MULTI_TEAM_RECOMMENDATION_UNCALIBRATED/);
assert.match(source, /validateMultiTeamTradeRequest/);
assert.match(source, /buildMultiTeamRouting/);
assert.match(source, /buildTwoTeamFairnessActivation/);
assert.match(source, /evaluateShadowRecommendation/);
assert.match(source, /faabEvidence/);
assert.match(source, /faabIsolation/);
assert.match(source, /excludedFromFantasyCalc: true/);
assert.match(source, /excludedFromExpertRos: true/);
assert.match(source, /excludedFromFairnessNumericValue: true/);
assert.match(source, /noDollarConversion: true/);
assert.match(source, /participants: request\.participants\.map\(\(participant\) => \(\{ \.\.\.participant, faab: null \}\)\)/);
assert.doesNotMatch(source, /acquisitionCost|keeperCost.*request|request.*keeperCost/);
assert.match(serverContext, /getSleeperAuctionDraftSnapshot/);
assert.match(serverContext, /buildAcquisitionSnapshot/);
assert.match(serverContext, /readPublishedRosArtifact/);
assert.match(serverContext, /readPublishedFantasyCalcArtifact/);
assert.doesNotMatch(serverContext, /readShadowFantasyCalcMap|player-stats-2026\.fantasycalc-redraft-candidate/);
assert.doesNotMatch(serverContext, /readFile\("data\/trade-analyzer\/ros\/ros-consensus-2026-2026-08-31\.candidate\.json/);
assert.match(serverContext, /function seasonMode/);
assert.match(serverContext, /week <= 4/);
assert.match(serverContext, /week <= 10/);
assert.match(source, /preseasonContext/);
assert.match(source, /expertRosByPlayer/);
assert.match(source, /context\.fantasyCalcByPlayer/);
assert.doesNotMatch(source, /\[\.\.\.context\.marketByPlayer\]/);
assert.doesNotMatch(source, /request\.(currentValue|expertRos|tradeMarket|keeper|fairness|seasonMode|preseasonContext)/);
assert.match(multiTeam, /PLAYER_NOT_ROSTERED/);
assert.match(multiTeam, /request\.mode === "LEAGUE_TRADE"/);
assert.match(diagnosticRoute, /requireAuctionAccess\("maintenance"\)/);
assert.match(diagnosticRoute, /buildServerTradeRecommendation/);
assert.doesNotMatch(diagnosticRoute, /NextResponse.*recommendation/);
console.log("Recommendation server adapter contract checks passed.");
