import fs from "node:fs/promises";
import path from "node:path";
import { ACTUAL_EVIDENCE_SCHEMA, type ActualEvidenceArtifact } from "../lib/seasonSimulator/evidenceCollection";
import { captureWeeklyActualEvidence, type ActualEvidenceMatchup } from "../lib/seasonSimulator/actualEvidenceService";
import { checksum } from "../lib/seasonSimulator/evidenceSnapshot";
import { getLeagueInfo, getLeagueRosters, getLocalPlayerIdentityRegistry, getMatchups, getNFLState, LEAGUE_ID } from "../lib/sleeper";

export const ACTUAL_CAPTURE_DIRECTORY = path.join(process.cwd(), ".local-calibration");
export type CaptureInput = { season: number; week: number; state: Record<string, unknown>; league: Record<string, unknown>; rosters: Array<Record<string, unknown>>; matchups: ActualEvidenceMatchup[]; finalizedAt?: string };
export type CaptureOptions = { season: number; week: number; dryRun: boolean; targetDirectory: string };
export type CaptureSummary = { schema: typeof ACTUAL_EVIDENCE_SCHEMA; season: number; week: number; leagueId: string; teamsPresent: number; matchupCount: number; playerActualRowCount: number; starterCount: number; source: "SLEEPER"; finalityEvidence: Record<string, unknown>; checksum: string; artifactPath: string; writePerformed: boolean; calibrationEligibility: "INELIGIBLE / PATH C" | "ELIGIBLE IF PAIRED WITH VALID PROJECTION" };

function usage(): never { throw new Error("Usage: npm run season-simulator:capture-actuals -- --season 2026 --week 1 [--dry-run]"); }
export function parseCaptureArgs(args: readonly string[], targetDirectory = ACTUAL_CAPTURE_DIRECTORY): CaptureOptions { const value = (flag: string) => { const index = args.indexOf(flag); return index >= 0 ? args[index + 1] : undefined; }; const season = Number(value("--season")); const week = Number(value("--week")); if (!Number.isInteger(season) || !Number.isInteger(week) || season < 2018 || week < 1 || week > 18) usage(); return { season, week, dryRun: args.includes("--dry-run"), targetDirectory }; }
export function buildActualCapture(input: CaptureInput): ActualEvidenceArtifact { const result = captureWeeklyActualEvidence({ ...input, playerDirectory: getLocalPlayerIdentityRegistry() }); if (result.state !== "CAPTURED" || !result.artifact) throw new Error(`REFUSED: ${result.state === "WAITING_FOR_FINALITY" ? `requested Week ${input.week} is not yet current/finalized in Sleeper.` : result.reason ?? "Sleeper week was not finalized."}`); return result.artifact; }
export function validateActualReadback(value: ActualEvidenceArtifact) { const base = Object.fromEntries(Object.entries(value).filter(([key]) => key !== "actualInputChecksum" && key !== "schemaVersion")); if (value.schemaVersion !== ACTUAL_EVIDENCE_SCHEMA || value.actualInputChecksum !== checksum(base)) throw new Error("REFUSED: actual artifact checksum validation failed."); }
async function existingArtifacts(directory: string, season: number, week: number) { const prefix = `${season}-week-${String(week).padStart(2, "0")}-actual-evidence-`; return (await fs.readdir(directory).catch(() => [] as string[])).filter(file => file.startsWith(prefix) && file.endsWith(".json")); }
export async function writeActualCapture(artifact: ActualEvidenceArtifact, options: { targetDirectory: string; dryRun: boolean }) { const artifactPath = path.join(options.targetDirectory, `${artifact.season}-week-${String(artifact.week).padStart(2, "0")}-actual-evidence-${artifact.actualInputChecksum.slice(0, 16)}.json`); const existing = await existingArtifacts(options.targetDirectory, artifact.season, artifact.week); if (existing.length > 0) throw new Error(`REFUSED: authoritative actual evidence already exists: ${existing.join(", ")}.`); if (options.dryRun) return { artifactPath, writePerformed: false }; await fs.mkdir(options.targetDirectory, { recursive: true }); const handle = await fs.open(artifactPath, "wx"); try { await handle.writeFile(JSON.stringify(artifact, null, 2) + "\n", "utf8"); } finally { await handle.close(); } validateActualReadback(JSON.parse(await fs.readFile(artifactPath, "utf8")) as ActualEvidenceArtifact); return { artifactPath, writePerformed: true }; }
export async function runCapture(options: CaptureOptions): Promise<CaptureSummary> { const [state, league, rosters, matchups] = await Promise.all([getNFLState(), getLeagueInfo(LEAGUE_ID), getLeagueRosters(LEAGUE_ID), getMatchups(options.week, LEAGUE_ID)]); const artifact = buildActualCapture({ season: options.season, week: options.week, state: state as unknown as Record<string, unknown>, league: league as unknown as Record<string, unknown>, rosters: rosters as Array<Record<string, unknown>>, matchups: matchups as ActualEvidenceMatchup[] }); const write = await writeActualCapture(artifact, options); return { schema: artifact.schemaVersion, season: options.season, week: options.week, leagueId: LEAGUE_ID, teamsPresent: artifact.matchupResults.length, matchupCount: artifact.matchupResults.length / 2, playerActualRowCount: artifact.playerActuals.length, starterCount: artifact.matchupResults.reduce((total, result) => total + result.officialStarterIds.length, 0), source: "SLEEPER", finalityEvidence: artifact.finalityEvidence as Record<string, unknown>, checksum: artifact.actualInputChecksum, artifactPath: write.artifactPath, writePerformed: write.writePerformed, calibrationEligibility: artifact.calibrationEligibility === "INELIGIBLE_PATH_C" ? "INELIGIBLE / PATH C" : "ELIGIBLE IF PAIRED WITH VALID PROJECTION" }; }
if (process.argv[1]?.endsWith("season-simulator-capture-actuals.ts")) runCapture(parseCaptureArgs(process.argv.slice(2))).then(summary => console.log(JSON.stringify(summary, null, 2))).catch(error => { console.error(error instanceof Error ? error.message : "Capture refused"); process.exitCode = 1; });
