import assert from "node:assert/strict";
import { buildDurableEvidenceRecord, durableEvidencePath, MemoryImmutableEvidenceStore, validateDurableEvidenceRecord } from "../lib/seasonSimulator/durableEvidence";
import { defaultFreezePolicy, resolveFreezeWindow } from "../lib/seasonSimulator/freezeWindowPolicy";
import { KickoffScheduleUnavailableError, resolveFirstKickoff } from "../lib/nflKickoffSchedule";
import { buildRunRecord, classifyWeeklyLifecycle, operationId } from "../lib/weeklyOperationsOrchestrator";
import { freezeWeeklyProjections } from "../lib/seasonSimulator/freezeService";
import { buildProjectionEvidenceArtifact } from "../lib/seasonSimulator/evidenceCollection";

(async () => {
const games = [{ season: 2026, week: 2, kickoffAt: "2026-09-20T13:00:00-04:00", source: "fixture", gameId: "sun" }, { season: 2026, week: 2, kickoffAt: "2026-09-17T20:15:00-04:00", source: "fixture", gameId: "thu" }] as const;
assert.equal(resolveFirstKickoff(games).gameId, "thu");
assert.equal(resolveFirstKickoff([{ ...games[0], kickoffAt: "2026-09-19T09:30:00-04:00", gameId: "intl" }]).gameId, "intl");
assert.throws(() => resolveFirstKickoff([]), KickoffScheduleUnavailableError);
assert.throws(() => resolveFirstKickoff([{ ...games[0], kickoffAt: "bad" }, { ...games[0], gameId: "duplicate" }]), KickoffScheduleUnavailableError);
const policyWindow = await resolveFreezeWindow({ listGames: async () => games }, 2026, 2);
assert.equal(policyWindow.firstKickoff, "2026-09-17T20:15:00-04:00");
assert.equal(policyWindow.windowOpen, "2026-09-17T19:00:00.000Z");
assert.equal(defaultFreezePolicy.leadTimeMinutes, 315);
const evidence = buildDurableEvidenceRecord({ season: 2026, week: 2, kind: "PROJECTION", source: "fixture", sourceChecksum: "projection", capturedAt: "now", payload: { source: "fixture" } });
validateDurableEvidenceRecord(evidence);
assert.equal(durableEvidencePath(2026, 2, "PROJECTION", "projection"), "river-city/season-simulator/evidence/2026/week-02/projection-projection.json");
const store = new MemoryImmutableEvidenceStore();
const evidencePath = durableEvidencePath(2026, 2, "PROJECTION", "projection");
assert.equal(await store.create(evidencePath, evidence), "CREATED");
assert.equal(await store.create(evidencePath, evidence), "DUPLICATE");
await assert.rejects(() => store.create(evidencePath, { ...evidence, payload: { changed: true }, recordChecksum: "conflict" }), /conflict/);
assert.equal(operationId(2026, 2, "freeze"), "2026:week-02:freeze");
assert.equal(buildRunRecord({ season: 2026, week: 2, operation: "HEALTH_CHECK", result: "OK", startedAt: "start", completedAt: "end", retryCount: 0, error: null }).operationId, "2026:week-02:HEALTH_CHECK");
assert.equal(classifyWeeklyLifecycle({ season: 2026, week: 2, beforeFirstKickoff: false, freezeEligible: false, projectionBaselineExists: true, finalityReady: false, actualEvidenceExists: false, actualEvidencePathC: false, residualDatasetExists: false, recapDraftExists: false, recapPublished: false, settlementState: "WAITING" }).state, "WEEK_LIVE");
const freezeDeps = { schedule: { listGames: async () => games }, evidence: new MemoryImmutableEvidenceStore(), hasAuthoritativeBaseline: async () => false, buildCandidate: async () => { throw new Error("fixture provider unavailable"); }, now: new Date("2026-09-17T14:59:00-04:00") };
assert.equal((await freezeWeeklyProjections({ ...freezeDeps, season: 2026, week: 2 })).state, "WAITING");
assert.equal((await freezeWeeklyProjections({ ...freezeDeps, season: 2026, week: 2, now: new Date("2026-09-17T20:15:00-04:00") })).state, "MISSED");
assert.equal((await freezeWeeklyProjections({ ...freezeDeps, season: 2026, week: 2, hasAuthoritativeBaseline: async () => true })).state, "ALREADY_FROZEN");
const candidate = buildProjectionEvidenceArtifact({ modelVersion: "fixture", season: 2026, week: 2, createdAt: "now", evidenceAsOf: "now", projectionSource: "FANTASYPROS", providerVersion: "fixture", providerResponseAsOf: "now", rosterEvidenceAsOf: "now", lineupEvidenceAsOf: "now", scoringSettingsChecksum: "settings", projectionInputChecksum: "inputs", projections: [{ franchiseId: "1", playerId: "p1", playerName: "Player", position: "QB", nflTeam: "BUF", projectedPoints: 10, projectedStarter: true, mappingMethod: "fixture" }], projectedLineups: {}, expectedTeamScores: Object.fromEntries(Array.from({ length: 12 }, (_, index) => [String(index + 1), { expectedScore: 10, status: "AVAILABLE" }])), mappingDiagnostics: {}, coverageDiagnostics: {}, unavailableTeamDiagnostics: [], capturePurpose: "CALIBRATION_BASELINE", capturedWithinApprovedWindow: true });
const candidateContent = Object.fromEntries(Object.entries(candidate).filter(([key]) => key !== "schemaVersion" && key !== "checksum"));
const coverageFailure = buildProjectionEvidenceArtifact({ ...candidateContent, expectedTeamScores: Object.fromEntries(Object.entries(candidate.expectedTeamScores).slice(0, 11)) } as never);
assert.equal((await freezeWeeklyProjections({ ...freezeDeps, season: 2026, week: 2, now: new Date("2026-09-17T15:01:00-04:00"), buildCandidate: async () => coverageFailure })).state, "FREEZE_COVERAGE_INCOMPLETE");
const recoveringEvidence = new MemoryImmutableEvidenceStore();
let providerAvailable = false;
const recovery = { ...freezeDeps, evidence: recoveringEvidence, now: new Date("2026-09-17T15:01:00-04:00"), buildCandidate: async () => { if (!providerAvailable) throw new Error("provider unavailable"); return candidate; } };
assert.equal((await freezeWeeklyProjections({ ...recovery, season: 2026, week: 2 })).state, "PROVIDER_UNAVAILABLE");
providerAvailable = true;
const frozen = await freezeWeeklyProjections({ ...recovery, season: 2026, week: 2 });
assert.equal(frozen.state, "FROZEN");
assert.equal(frozen.writePerformed, true);
assert.equal((await freezeWeeklyProjections({ ...recovery, season: 2026, week: 2, hasAuthoritativeBaseline: async () => Boolean(await recoveringEvidence.read(frozen.objectPath!)) })).state, "ALREADY_FROZEN");
console.log("weekly operations Package A tests passed");
})().catch(error => { console.error(error); process.exitCode = 1; });
