import Link from "next/link";
import type { DraftReportCard } from "@/lib/draftReportCard";

function score(value: number | null | undefined) { return typeof value === "number" ? value.toFixed(2) : "N/A"; }
function money(value: number | null | undefined) { return typeof value === "number" ? `$${value.toFixed(0)}` : "N/A"; }
function sentence(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
function ordinal(value: number) { return `${value}${value % 100 >= 11 && value % 100 <= 13 ? "th" : ({ 1: "st", 2: "nd", 3: "rd" } as Record<number, string>)[value % 10] ?? "th"}`; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-900/10 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#121212] sm:p-6"><h2 className="text-xl font-black uppercase italic">{title}</h2>{children}</section>; }

export default function DraftReportCardView({ report }: { report: DraftReportCard }) {
  const { publicRecord, grade, analysis } = report;
  const metrics = publicRecord.metrics;
  const parts = grade ? [["Value", grade.valueEfficiency], ["Roster Construction", grade.rosterConstruction], ["Budget", grade.budgetManagement], ["Keeper", grade.keeperEfficiency]] as const : [];
  const ranked = new Set(["QB", "RB", "WR", "TE", "FLEX"]);
  const misses = [
    grade?.valueEfficiency.score !== null && grade?.valueEfficiency.score !== undefined && grade.valueEfficiency.score < 60 ? "Value capture was the clearest grading weakness." : null,
    grade?.rosterConstruction.score !== null && grade?.rosterConstruction.score !== undefined && grade.rosterConstruction.score < 60 ? "Roster construction needs attention in the next roster cycle." : null,
    metrics.biggestReach ? `${metrics.biggestReach.playerName} was the biggest reach, costing ${money(metrics.biggestReach.purchasePrice)} and finishing ${money(Math.abs(metrics.biggestReach.valueDifferential))} above the external auction reference.` : null,
    analysis.concerns[0] ?? null,
  ].filter((item): item is string => Boolean(item)).slice(0, 4);
  const strongest = analysis.positionStrengths.filter((row) => ranked.has(row.position) && row.rank !== null).sort((a, b) => (a.rank ?? 99) - (b.rank ?? 99))[0];
  const weakest = analysis.positionStrengths.filter((row) => ranked.has(row.position) && row.rank !== null).sort((a, b) => (b.rank ?? -1) - (a.rank ?? -1))[0];
  const verdict = grade?.draftScore === null || grade?.draftScore === undefined
    ? "The available draft evidence is not sufficient to issue an overall verdict."
    : `This ${grade.letterGrade ?? "ungraded"} draft scored ${grade.draftScore.toFixed(2)} and ranks ${report.rank ? ordinal(report.rank) : "outside the available order"} in the league. ${strongest && weakest && strongest.position !== weakest.position ? `${sentence(strongest.position)} was the clearest strength while ${sentence(weakest.position)} was the main area to improve.` : "The available evidence shows a relatively balanced build."}`;
  const keeperExplanation = grade?.keeperEfficiency.score === null || grade?.keeperEfficiency.score === undefined
    ? "The keeper category could not be scored from the available keeper-value evidence."
    : metrics.keeperValueDifferential === null
      ? "Keeper costs are recorded, but complete keeper market-value evidence is unavailable; missing values are not treated as zero."
      : metrics.keeperValueDifferential > 0
        ? `The keepers contributed ${money(metrics.keeperValueDifferential)} of published value above their draft-night costs.`
        : metrics.keeperValueDifferential < 0
          ? `The keepers finished ${money(Math.abs(metrics.keeperValueDifferential))} below their draft-night costs in the available published values.`
          : "The keepers were value-neutral against their draft-night costs in the available published values.";
  return <main className="mx-auto max-w-6xl space-y-5 px-4 py-8 sm:px-6">
    <Link href={report.accessMode === "COMMISSIONER_PREVIEW" ? "/commish/post-draft" : "/"} className="inline-flex min-h-11 items-center rounded-xl border border-slate-900/10 px-4 text-xs font-black uppercase tracking-widest dark:border-white/10">Back</Link>
    <header className="rounded-3xl bg-[#071a33] p-6 text-white shadow-xl sm:p-8"><p className="text-[10px] font-black uppercase tracking-[0.3em] text-orange-300">{report.accessMode === "COMMISSIONER_PREVIEW" ? "Commissioner Preview" : "Owner Report Card"} · {publicRecord.season}</p><h1 className="mt-2 text-3xl font-black uppercase italic tracking-tight sm:text-5xl">2026 Draft Report Card</h1><p className="mt-3 text-lg font-bold">{publicRecord.teamName}</p><p className="mt-1 text-sm font-semibold text-white/70">{report.ownerNames.join(" / ") || "Owner unavailable"}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-orange-300">Overall grade</p><p className="mt-1 text-5xl font-black">{grade?.letterGrade ?? "N/A"}</p></div><div><p className="text-[10px] font-black uppercase tracking-widest text-orange-300">Score</p><p className="mt-1 text-4xl font-black">{score(grade?.draftScore)}</p></div><div><p className="text-[10px] font-black uppercase tracking-widest text-orange-300">League rank</p><p className="mt-1 text-4xl font-black">{report.rank ? `${report.rank} of 12` : "N/A"}</p></div></div></header>
    {grade?.status === "partial" ? <p className="rounded-xl border border-orange-600/25 bg-orange-600/10 p-4 text-sm font-semibold">Some player-market data was unavailable, so certain category calculations have partial coverage.</p> : null}
    <Card title="Draft verdict"><p className="mt-4 text-sm font-semibold leading-7">{verdict}</p></Card>
    <Card title="Category grades"><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{parts.map(([label, part]) => <div key={label} className="rounded-xl bg-slate-50 p-4 dark:bg-white/[0.04]"><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{score(part.score)}</p>{part.status !== "complete" ? <p className="mt-1 text-xs font-semibold text-orange-700">{part.status === "not-applicable" ? "Not applicable" : part.status === "not-ready" ? "Unavailable" : "Partial coverage"}</p> : null}</div>)}</div></Card>
    <div className="grid gap-5 lg:grid-cols-2"><Card title="What you did well"><ul className="mt-4 grid gap-2 text-sm font-semibold">{(analysis.strengths.length ? analysis.strengths : analysis.insights.slice(0, 3).map((item) => item.text)).slice(0, 4).map((item) => <li key={item} className="rounded-lg bg-emerald-600/10 p-3">{item}</li>)}</ul></Card><Card title="Where you missed"><ul className="mt-4 grid gap-2 text-sm font-semibold">{(misses.length ? misses : ["No material weakness was identified by the available evidence."]).map((item) => <li key={item} className="rounded-lg bg-orange-600/10 p-3">{item}</li>)}</ul></Card></div>
    <div className="grid gap-5 lg:grid-cols-2"><Card title="Best buy / biggest reach"><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-emerald-600/10 p-4"><p className="text-[10px] font-black uppercase tracking-widest">Best buy</p><p className="mt-2 font-black">{metrics.bestBuy?.playerName ?? "N/A"}</p><p className="mt-1 text-sm font-semibold">{metrics.bestBuy ? `${money(metrics.bestBuy.purchasePrice)} paid · ${money(metrics.bestBuy.valueDifferential)} below external reference` : "No comparable value evidence."}</p></div><div className="rounded-xl bg-orange-600/10 p-4"><p className="text-[10px] font-black uppercase tracking-widest">Biggest reach</p><p className="mt-2 font-black">{metrics.biggestReach?.playerName ?? "No major reach identified"}</p><p className="mt-1 text-sm font-semibold">{metrics.biggestReach ? `${money(metrics.biggestReach.purchasePrice)} paid · ${money(Math.abs(metrics.biggestReach.valueDifferential))} above external reference` : "No comparable overpay evidence."}</p></div></div></Card><Card title="Budget"><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">Spent</p><p className="mt-1 text-xl font-black">{money(metrics.totalSpend)}</p></div><div><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">Budget</p><p className="mt-1 text-xl font-black">$200</p></div><div><p className="text-[10px] font-black uppercase tracking-widest text-slate-500">Left</p><p className="mt-1 text-xl font-black">{money(metrics.remainingBudget)}</p></div></div></Card></div>
    <Card title="Roster construction"><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{analysis.positionStrengths.filter((row) => ranked.has(row.position)).map((row) => <div key={row.position} className="rounded-xl border border-slate-900/10 p-3 dark:border-white/10"><p className="font-black">{row.position}</p><p className="mt-1 text-xs font-bold">{row.rank ? `Rank #${row.rank} · ${row.label}` : "Limited evidence"}</p><p className="mt-2 text-xs text-slate-500">{row.starters.length ? `${row.starters.length} starter${row.starters.length === 1 ? "" : "s"} covered` : "Starter evidence unavailable"}</p></div>)}</div><p className="mt-4 text-sm font-semibold">{metrics.coveredStarterSlots}/{Object.values(metrics.requiredStarterSlots).reduce((sum, count) => sum + count, 0)} required starter slots covered · {metrics.totalDepth} useful depth players.</p></Card>
    <div className="grid gap-5 lg:grid-cols-2"><Card title="Keeper context"><p className="mt-4 text-sm font-semibold">{report.keepers.length ? report.keepers.map((keeper) => `${keeper.playerName} (${money(keeper.price)} draft-night cost)`).join(" · ") : "No draft-night keepers recorded."}</p><p className="mt-3 text-sm font-semibold">Keeper category score: {score(grade?.keeperEfficiency.score)}</p><p className="mt-2 text-sm font-semibold">Available keeper value evidence: {metrics.keeperPublishedValue === null ? "Incomplete" : money(metrics.keeperPublishedValue)}</p><p className="mt-2 text-sm text-slate-600 dark:text-white/60">{keeperExplanation}</p></Card><details className="rounded-2xl border border-slate-900/10 bg-white p-5 dark:border-white/10 dark:bg-[#121212]"><summary className="cursor-pointer text-xl font-black uppercase italic">Data coverage</summary><div className="mt-4 space-y-2 text-sm font-semibold"><p>This report uses the completed 2026 auction roster at draft night.</p><p>Post-draft transactions do not alter the grade.</p><p>This factual card does not depend on a manually captured snapshot or narrative publication.</p><p>Missing market values are not converted to zero.</p><p>Kicker and defense market rankings are limited where comparable values are unavailable.</p></div></details></div>
  </main>;
}
